/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/* Generated by json2cpp */

#ifndef OPENOCPP_OCPP21_LC_CHARGEPOINTPROXY21_H
#define OPENOCPP_OCPP21_LC_CHARGEPOINTPROXY21_H

#include "ChargePointHandler21.h"
#include "GenericMessageSender.h"
#include "IChargePointProxy21.h"
#include "Logger.h"
#include "MessageDispatcher.h"
#include "MessagesValidator21.h"
#include "RpcServer.h"
#include "UserMessageHandler.h"

namespace ocpp
{
namespace config
{
class ILocalControllerConfig21;
} // namespace config
namespace localcontroller
{
namespace ocpp21
{

/** @brief Charge point proxy */
class ChargePointProxy21 : public IChargePointProxy21, public ocpp::rpc::IRpc::IListener, public ocpp::rpc::IRpc::ISpy
{
  public:
    /**
     * @brief Constructor
     * @param identifier Charge point's identifier
     * @param rpc RPC connection with the charge point
     * @param messages_validator JSON schemas needed to validate payloads
     * @param messages_converter Converter from/to OCPP to/from JSON messages
     * @param stack_config Stack configuration
     * @param central_system Proxy to forward requests to the central system
     */
    ChargePointProxy21(const std::string&                               identifier,
                     std::shared_ptr<ocpp::rpc::RpcServer::Client>    rpc,
                     const ocpp::messages::ocpp21::MessagesValidator21& messages_validator,
                     ocpp::messages::ocpp21::MessagesConverter21&       messages_converter,
                     const ocpp::config::ILocalControllerConfig21&      stack_config,
                     std::shared_ptr<ICentralSystemProxy21>             central_system);
    /** @brief Destructor */
    virtual ~ChargePointProxy21();

    // IChargePointProxy21 interface

    /** @copydoc const std::string& IChargePointProxy21::ipAddress() const */
    const std::string& ipAddress() const override;

    /** @copydoc const std::string& IChargePointProxy21::identifier() const */
    const std::string& identifier() const override { return m_identifier; }

    /** @copydoc void IChargePointProxy21::setTimeout(std::chrono::milliseconds) */
    void setTimeout(std::chrono::milliseconds timeout) override;

    /** @copydoc void IChargePointProxy21::disconnect() */
    void disconnect() override;

    /** @copydoc std::shared_ptr<ICentralSystemProxy> IChargePointProxy21::centralSystemProxy() */
    std::shared_ptr<ICentralSystemProxy21> centralSystemProxy() override { return m_central_system; }

    /** @copydoc void IChargePointProxy21::registerListener(ILocalControllerProxyEventsHandler21&) */
    void registerListener(ILocalControllerProxyEventsHandler21& listener) override
    {
        m_listener = &listener;
        m_central_system->registerListener(listener);
    }

    // OCPP operations
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::AFRRSignalReq&,
     *                                          ocpp::messages::ocpp21::AFRRSignalConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::AFRRSignalReq& request,
              ocpp::messages::ocpp21::AFRRSignalConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::AdjustPeriodicEventStreamReq&,
     *                                          ocpp::messages::ocpp21::AdjustPeriodicEventStreamConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::AdjustPeriodicEventStreamReq& request,
              ocpp::messages::ocpp21::AdjustPeriodicEventStreamConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::CancelReservationReq&,
     *                                          ocpp::messages::ocpp21::CancelReservationConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::CancelReservationReq& request,
              ocpp::messages::ocpp21::CancelReservationConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::CertificateSignedReq&,
     *                                          ocpp::messages::ocpp21::CertificateSignedConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::CertificateSignedReq& request,
              ocpp::messages::ocpp21::CertificateSignedConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ChangeAvailabilityReq&,
     *                                          ocpp::messages::ocpp21::ChangeAvailabilityConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::ChangeAvailabilityReq& request,
              ocpp::messages::ocpp21::ChangeAvailabilityConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ChangeTransactionTariffReq&,
     *                                          ocpp::messages::ocpp21::ChangeTransactionTariffConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::ChangeTransactionTariffReq& request,
              ocpp::messages::ocpp21::ChangeTransactionTariffConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ClearCacheReq&,
     *                                          ocpp::messages::ocpp21::ClearCacheConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::ClearCacheReq& request,
              ocpp::messages::ocpp21::ClearCacheConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ClearChargingProfileReq&,
     *                                          ocpp::messages::ocpp21::ClearChargingProfileConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::ClearChargingProfileReq& request,
              ocpp::messages::ocpp21::ClearChargingProfileConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ClearDERControlReq&,
     *                                          ocpp::messages::ocpp21::ClearDERControlConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::ClearDERControlReq& request,
              ocpp::messages::ocpp21::ClearDERControlConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ClearDisplayMessageReq&,
     *                                          ocpp::messages::ocpp21::ClearDisplayMessageConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::ClearDisplayMessageReq& request,
              ocpp::messages::ocpp21::ClearDisplayMessageConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ClearTariffsReq&,
     *                                          ocpp::messages::ocpp21::ClearTariffsConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::ClearTariffsReq& request,
              ocpp::messages::ocpp21::ClearTariffsConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ClearVariableMonitoringReq&,
     *                                          ocpp::messages::ocpp21::ClearVariableMonitoringConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::ClearVariableMonitoringReq& request,
              ocpp::messages::ocpp21::ClearVariableMonitoringConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ClosePeriodicEventStreamReq&,
     *                                          ocpp::messages::ocpp21::ClosePeriodicEventStreamConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::ClosePeriodicEventStreamReq& request,
              ocpp::messages::ocpp21::ClosePeriodicEventStreamConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::CustomerInformationReq&,
     *                                          ocpp::messages::ocpp21::CustomerInformationConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::CustomerInformationReq& request,
              ocpp::messages::ocpp21::CustomerInformationConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::DataTransferReq&,
     *                                          ocpp::messages::ocpp21::DataTransferConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::DataTransferReq& request,
              ocpp::messages::ocpp21::DataTransferConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::DeleteCertificateReq&,
     *                                          ocpp::messages::ocpp21::DeleteCertificateConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::DeleteCertificateReq& request,
              ocpp::messages::ocpp21::DeleteCertificateConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::Get15118EVCertificateReq&,
     *                                          ocpp::messages::ocpp21::Get15118EVCertificateConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::Get15118EVCertificateReq& request,
              ocpp::messages::ocpp21::Get15118EVCertificateConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetBaseReportReq&,
     *                                          ocpp::messages::ocpp21::GetBaseReportConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::GetBaseReportReq& request,
              ocpp::messages::ocpp21::GetBaseReportConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetCertificateChainStatusReq&,
     *                                          ocpp::messages::ocpp21::GetCertificateChainStatusConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::GetCertificateChainStatusReq& request,
              ocpp::messages::ocpp21::GetCertificateChainStatusConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetCertificateStatusReq&,
     *                                          ocpp::messages::ocpp21::GetCertificateStatusConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::GetCertificateStatusReq& request,
              ocpp::messages::ocpp21::GetCertificateStatusConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetChargingProfilesReq&,
     *                                          ocpp::messages::ocpp21::GetChargingProfilesConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::GetChargingProfilesReq& request,
              ocpp::messages::ocpp21::GetChargingProfilesConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetCompositeScheduleReq&,
     *                                          ocpp::messages::ocpp21::GetCompositeScheduleConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::GetCompositeScheduleReq& request,
              ocpp::messages::ocpp21::GetCompositeScheduleConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetDERControlReq&,
     *                                          ocpp::messages::ocpp21::GetDERControlConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::GetDERControlReq& request,
              ocpp::messages::ocpp21::GetDERControlConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetDisplayMessagesReq&,
     *                                          ocpp::messages::ocpp21::GetDisplayMessagesConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::GetDisplayMessagesReq& request,
              ocpp::messages::ocpp21::GetDisplayMessagesConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetInstalledCertificateIdsReq&,
     *                                          ocpp::messages::ocpp21::GetInstalledCertificateIdsConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::GetInstalledCertificateIdsReq& request,
              ocpp::messages::ocpp21::GetInstalledCertificateIdsConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetLocalListVersionReq&,
     *                                          ocpp::messages::ocpp21::GetLocalListVersionConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::GetLocalListVersionReq& request,
              ocpp::messages::ocpp21::GetLocalListVersionConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetLogReq&,
     *                                          ocpp::messages::ocpp21::GetLogConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::GetLogReq& request,
              ocpp::messages::ocpp21::GetLogConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetMonitoringReportReq&,
     *                                          ocpp::messages::ocpp21::GetMonitoringReportConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::GetMonitoringReportReq& request,
              ocpp::messages::ocpp21::GetMonitoringReportConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetPeriodicEventStreamReq&,
     *                                          ocpp::messages::ocpp21::GetPeriodicEventStreamConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::GetPeriodicEventStreamReq& request,
              ocpp::messages::ocpp21::GetPeriodicEventStreamConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetReportReq&,
     *                                          ocpp::messages::ocpp21::GetReportConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::GetReportReq& request,
              ocpp::messages::ocpp21::GetReportConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetTariffsReq&,
     *                                          ocpp::messages::ocpp21::GetTariffsConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::GetTariffsReq& request,
              ocpp::messages::ocpp21::GetTariffsConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetTransactionStatusReq&,
     *                                          ocpp::messages::ocpp21::GetTransactionStatusConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::GetTransactionStatusReq& request,
              ocpp::messages::ocpp21::GetTransactionStatusConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetVariablesReq&,
     *                                          ocpp::messages::ocpp21::GetVariablesConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::GetVariablesReq& request,
              ocpp::messages::ocpp21::GetVariablesConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::InstallCertificateReq&,
     *                                          ocpp::messages::ocpp21::InstallCertificateConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::InstallCertificateReq& request,
              ocpp::messages::ocpp21::InstallCertificateConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::OpenPeriodicEventStreamReq&,
     *                                          ocpp::messages::ocpp21::OpenPeriodicEventStreamConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::OpenPeriodicEventStreamReq& request,
              ocpp::messages::ocpp21::OpenPeriodicEventStreamConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::PublishFirmwareReq&,
     *                                          ocpp::messages::ocpp21::PublishFirmwareConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::PublishFirmwareReq& request,
              ocpp::messages::ocpp21::PublishFirmwareConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::RequestBatterySwapReq&,
     *                                          ocpp::messages::ocpp21::RequestBatterySwapConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::RequestBatterySwapReq& request,
              ocpp::messages::ocpp21::RequestBatterySwapConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::RequestStartTransactionReq&,
     *                                          ocpp::messages::ocpp21::RequestStartTransactionConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::RequestStartTransactionReq& request,
              ocpp::messages::ocpp21::RequestStartTransactionConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::RequestStopTransactionReq&,
     *                                          ocpp::messages::ocpp21::RequestStopTransactionConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::RequestStopTransactionReq& request,
              ocpp::messages::ocpp21::RequestStopTransactionConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ReserveNowReq&,
     *                                          ocpp::messages::ocpp21::ReserveNowConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::ReserveNowReq& request,
              ocpp::messages::ocpp21::ReserveNowConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ResetReq&,
     *                                          ocpp::messages::ocpp21::ResetConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::ResetReq& request,
              ocpp::messages::ocpp21::ResetConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::SendLocalListReq&,
     *                                          ocpp::messages::ocpp21::SendLocalListConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::SendLocalListReq& request,
              ocpp::messages::ocpp21::SendLocalListConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::SetChargingProfileReq&,
     *                                          ocpp::messages::ocpp21::SetChargingProfileConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::SetChargingProfileReq& request,
              ocpp::messages::ocpp21::SetChargingProfileConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::SetDefaultTariffReq&,
     *                                          ocpp::messages::ocpp21::SetDefaultTariffConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::SetDefaultTariffReq& request,
              ocpp::messages::ocpp21::SetDefaultTariffConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::SetDERControlReq&,
     *                                          ocpp::messages::ocpp21::SetDERControlConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::SetDERControlReq& request,
              ocpp::messages::ocpp21::SetDERControlConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::SetDisplayMessageReq&,
     *                                          ocpp::messages::ocpp21::SetDisplayMessageConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::SetDisplayMessageReq& request,
              ocpp::messages::ocpp21::SetDisplayMessageConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::SetMonitoringBaseReq&,
     *                                          ocpp::messages::ocpp21::SetMonitoringBaseConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::SetMonitoringBaseReq& request,
              ocpp::messages::ocpp21::SetMonitoringBaseConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::SetMonitoringLevelReq&,
     *                                          ocpp::messages::ocpp21::SetMonitoringLevelConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::SetMonitoringLevelReq& request,
              ocpp::messages::ocpp21::SetMonitoringLevelConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::SetNetworkProfileReq&,
     *                                          ocpp::messages::ocpp21::SetNetworkProfileConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::SetNetworkProfileReq& request,
              ocpp::messages::ocpp21::SetNetworkProfileConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::SetVariableMonitoringReq&,
     *                                          ocpp::messages::ocpp21::SetVariableMonitoringConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::SetVariableMonitoringReq& request,
              ocpp::messages::ocpp21::SetVariableMonitoringConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::SetVariablesReq&,
     *                                          ocpp::messages::ocpp21::SetVariablesConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::SetVariablesReq& request,
              ocpp::messages::ocpp21::SetVariablesConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::TriggerMessageReq&,
     *                                          ocpp::messages::ocpp21::TriggerMessageConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::TriggerMessageReq& request,
              ocpp::messages::ocpp21::TriggerMessageConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::UnlockConnectorReq&,
     *                                          ocpp::messages::ocpp21::UnlockConnectorConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::UnlockConnectorReq& request,
              ocpp::messages::ocpp21::UnlockConnectorConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::UnpublishFirmwareReq&,
     *                                          ocpp::messages::ocpp21::UnpublishFirmwareConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::UnpublishFirmwareReq& request,
              ocpp::messages::ocpp21::UnpublishFirmwareConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::UpdateDynamicScheduleReq&,
     *                                          ocpp::messages::ocpp21::UpdateDynamicScheduleConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::UpdateDynamicScheduleReq& request,
              ocpp::messages::ocpp21::UpdateDynamicScheduleConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::UpdateFirmwareReq&,
     *                                          ocpp::messages::ocpp21::UpdateFirmwareConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::UpdateFirmwareReq& request,
              ocpp::messages::ocpp21::UpdateFirmwareConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::UsePriorityChargingReq&,
     *                                          ocpp::messages::ocpp21::UsePriorityChargingConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::UsePriorityChargingReq& request,
              ocpp::messages::ocpp21::UsePriorityChargingConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::AuthorizeReq&, ocpp::messages::ocpp16::AuthorizeConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::AuthorizeReq&,
                                            ocpp::messages::ocpp21::AuthorizeConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::BatterySwapReq&, ocpp::messages::ocpp16::BatterySwapConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::BatterySwapReq&,
                                            ocpp::messages::ocpp21::BatterySwapConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::BootNotificationReq&, ocpp::messages::ocpp16::BootNotificationConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::BootNotificationReq&,
                                            ocpp::messages::ocpp21::BootNotificationConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::ClearedChargingLimitReq&, ocpp::messages::ocpp16::ClearedChargingLimitConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::ClearedChargingLimitReq&,
                                            ocpp::messages::ocpp21::ClearedChargingLimitConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::CostUpdatedReq&, ocpp::messages::ocpp16::CostUpdatedConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::CostUpdatedReq&,
                                            ocpp::messages::ocpp21::CostUpdatedConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::DataTransferReq&, ocpp::messages::ocpp16::DataTransferConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::DataTransferReq&,
                                            ocpp::messages::ocpp21::DataTransferConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::FirmwareStatusNotificationReq&, ocpp::messages::ocpp16::FirmwareStatusNotificationConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::FirmwareStatusNotificationReq&,
                                            ocpp::messages::ocpp21::FirmwareStatusNotificationConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::HeartbeatReq&, ocpp::messages::ocpp16::HeartbeatConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::HeartbeatReq&,
                                            ocpp::messages::ocpp21::HeartbeatConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::LogStatusNotificationReq&, ocpp::messages::ocpp16::LogStatusNotificationConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::LogStatusNotificationReq&,
                                            ocpp::messages::ocpp21::LogStatusNotificationConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::MeterValuesReq&, ocpp::messages::ocpp16::MeterValuesConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::MeterValuesReq&,
                                            ocpp::messages::ocpp21::MeterValuesConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyAllowedEnergyTransferReq&, ocpp::messages::ocpp16::NotifyAllowedEnergyTransferConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::NotifyAllowedEnergyTransferReq&,
                                            ocpp::messages::ocpp21::NotifyAllowedEnergyTransferConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyChargingLimitReq&, ocpp::messages::ocpp16::NotifyChargingLimitConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::NotifyChargingLimitReq&,
                                            ocpp::messages::ocpp21::NotifyChargingLimitConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyCustomerInformationReq&, ocpp::messages::ocpp16::NotifyCustomerInformationConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::NotifyCustomerInformationReq&,
                                            ocpp::messages::ocpp21::NotifyCustomerInformationConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyDERAlarmReq&, ocpp::messages::ocpp16::NotifyDERAlarmConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::NotifyDERAlarmReq&,
                                            ocpp::messages::ocpp21::NotifyDERAlarmConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyDERStartStopReq&, ocpp::messages::ocpp16::NotifyDERStartStopConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::NotifyDERStartStopReq&,
                                            ocpp::messages::ocpp21::NotifyDERStartStopConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyDisplayMessagesReq&, ocpp::messages::ocpp16::NotifyDisplayMessagesConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::NotifyDisplayMessagesReq&,
                                            ocpp::messages::ocpp21::NotifyDisplayMessagesConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyEVChargingNeedsReq&, ocpp::messages::ocpp16::NotifyEVChargingNeedsConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::NotifyEVChargingNeedsReq&,
                                            ocpp::messages::ocpp21::NotifyEVChargingNeedsConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyEVChargingScheduleReq&, ocpp::messages::ocpp16::NotifyEVChargingScheduleConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::NotifyEVChargingScheduleReq&,
                                            ocpp::messages::ocpp21::NotifyEVChargingScheduleConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyEventReq&, ocpp::messages::ocpp16::NotifyEventConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::NotifyEventReq&,
                                            ocpp::messages::ocpp21::NotifyEventConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyMonitoringReportReq&, ocpp::messages::ocpp16::NotifyMonitoringReportConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::NotifyMonitoringReportReq&,
                                            ocpp::messages::ocpp21::NotifyMonitoringReportConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyPeriodicEventStreamReq&, ocpp::messages::ocpp16::NotifyPeriodicEventStreamConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::NotifyPeriodicEventStreamReq&,
                                            ocpp::messages::ocpp21::NotifyPeriodicEventStreamConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyPriorityChargingReq&, ocpp::messages::ocpp16::NotifyPriorityChargingConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::NotifyPriorityChargingReq&,
                                            ocpp::messages::ocpp21::NotifyPriorityChargingConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyReportReq&, ocpp::messages::ocpp16::NotifyReportConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::NotifyReportReq&,
                                            ocpp::messages::ocpp21::NotifyReportConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifySettlementReq&, ocpp::messages::ocpp16::NotifySettlementConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::NotifySettlementReq&,
                                            ocpp::messages::ocpp21::NotifySettlementConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyWebPaymentStartedReq&, ocpp::messages::ocpp16::NotifyWebPaymentStartedConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::NotifyWebPaymentStartedReq&,
                                            ocpp::messages::ocpp21::NotifyWebPaymentStartedConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::PublishFirmwareStatusNotificationReq&, ocpp::messages::ocpp16::PublishFirmwareStatusNotificationConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::PublishFirmwareStatusNotificationReq&,
                                            ocpp::messages::ocpp21::PublishFirmwareStatusNotificationConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::PullDynamicScheduleUpdateReq&, ocpp::messages::ocpp16::PullDynamicScheduleUpdateConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::PullDynamicScheduleUpdateReq&,
                                            ocpp::messages::ocpp21::PullDynamicScheduleUpdateConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::ReportChargingProfilesReq&, ocpp::messages::ocpp16::ReportChargingProfilesConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::ReportChargingProfilesReq&,
                                            ocpp::messages::ocpp21::ReportChargingProfilesConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::ReportDERControlReq&, ocpp::messages::ocpp16::ReportDERControlConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::ReportDERControlReq&,
                                            ocpp::messages::ocpp21::ReportDERControlConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::ReservationStatusUpdateReq&, ocpp::messages::ocpp16::ReservationStatusUpdateConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::ReservationStatusUpdateReq&,
                                            ocpp::messages::ocpp21::ReservationStatusUpdateConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::SecurityEventNotificationReq&, ocpp::messages::ocpp16::SecurityEventNotificationConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::SecurityEventNotificationReq&,
                                            ocpp::messages::ocpp21::SecurityEventNotificationConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::SignCertificateReq&, ocpp::messages::ocpp16::SignCertificateConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::SignCertificateReq&,
                                            ocpp::messages::ocpp21::SignCertificateConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::StatusNotificationReq&, ocpp::messages::ocpp16::StatusNotificationConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::StatusNotificationReq&,
                                            ocpp::messages::ocpp21::StatusNotificationConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::TransactionEventReq&, ocpp::messages::ocpp16::TransactionEventConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::TransactionEventReq&,
                                            ocpp::messages::ocpp21::TransactionEventConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::VatNumberValidationReq&, ocpp::messages::ocpp16::VatNumberValidationConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::VatNumberValidationReq&,
                                            ocpp::messages::ocpp21::VatNumberValidationConf&,
                                            std::string&,
                                            std::string&)> handler) override;

    // IRpc::IListener interface

    /** @copydoc void IRpc::IListener::rpcDisconnected() */
    void rpcDisconnected() override;

    /** @copydoc void IRpc::IListener::rpcError() */
    void rpcError() override;

    /** @copydoc bool IRpc::IListener::rpcCallReceived(const std::string&,
                                                       const rapidjson::Value&,
                                                       rapidjson::Document&,
                                                       std::string&,
                                                       std::string&) */
    bool rpcCallReceived(const std::string&      action,
                         const rapidjson::Value& payload,
                         rapidjson::Document&    response,
                         std::string&            error_code,
                         std::string&            error_message) override;

    // IRpc::ISpy interface

    /** @copydoc void IRpc::ISpy::rcpMessageReceived(const std::string& msg) */
    void rcpMessageReceived(const std::string& msg) override;

    /** @copydoc void IRpc::ISpy::rcpMessageSent(const std::string& msg) */
    void rcpMessageSent(const std::string& msg) override;

  private:
    /** @brief Charge point's identifier */
    std::string m_identifier;
    /** @brief RPC connection */
    std::shared_ptr<ocpp::rpc::RpcServer::Client> m_rpc;
    /** @brief Messages converter */
    ocpp::messages::ocpp21::MessagesConverter21& m_messages_converter;
    /** @brief Message dispatcher */
    ocpp::messages::MessageDispatcher m_msg_dispatcher;
    /** @brief Message sender */
    ocpp::messages::GenericMessageSender m_msg_sender;
    /** @brief Proxy to forward requests to the central system */
    std::shared_ptr<ICentralSystemProxy21> m_central_system;
    /** @brief Request handler */
    ChargePointHandler21 m_handler;
    /** @brief Listener to the proxy events */
    ILocalControllerProxyEventsHandler21* m_listener;
    /** @brief User message handlers */
    std::vector<std::shared_ptr<ocpp::messages::IMessageDispatcher::IMessageHandler>> m_user_handlers;

    /**
     * @brief Execute a call request
     * @param action RPC action for the request
     * @param request Request payload
     * @param response Response payload
     * @param error Error (Empty if not a CallError)
     * @param message Error message (Empty if not a CallError)
     * @return true if the request has been sent and a response has been received, false otherwise
     */
    template <typename RequestType, typename ResponseType>
    bool call(const std::string& action, const RequestType& request, ResponseType& response, std::string& error, std::string& message)
    {
        bool ret = true;

        LOG_DEBUG << "[" << m_identifier << "] - " << action;

        ocpp::messages::CallResult res = m_msg_sender.call(action, request, response, error, message);
        if (res != ocpp::messages::CallResult::Ok)
        {
            LOG_ERROR << "[" << m_identifier << "] - " << action << " => "
                      << (res == ocpp::messages::CallResult::Failed ? "Timeout" : "Error");
            ret = false;
        }

        return ret;
    }

    /**
     * @brief Register a user handler for an incoming request
     * @param action RPC action for the request
     * @param handler Handler function
     * @return true if the handler has been registered, false otherwise
     */
    template <typename RequestType, typename ResponseType>
    bool registerHandler(const std::string&                                                                 action,
                         std::function<bool(const RequestType&, ResponseType&, std::string&, std::string&)> handler)
    {
        ocpp::messages::UserMessageHandler<RequestType, ResponseType>* msg_handler =
            new ocpp::messages::UserMessageHandler<RequestType, ResponseType>(action, m_messages_converter, handler);
        m_user_handlers.push_back(std::shared_ptr<ocpp::messages::IMessageDispatcher::IMessageHandler>(msg_handler));
        return m_msg_dispatcher.registerHandler(action, *msg_handler, true);
    }
};

} // namespace ocpp21
} // namespace localcontroller
} // namespace ocpp

#endif // OPENOCPP_OCPP21_LC_CHARGEPOINTPROXY21_H