/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/* Generated by json2cpp */

#include "ChargePointProxy21.h"
#include "../centralsystem/chargepoint/ChargePointProxy21.h"
#include "CentralSystemProxy21.h"
#include "ILocalControllerConfig21.h"
#include "ILocalControllerProxyEventsHandler21.h"
#include "MessagesConverter21.h"

using namespace ocpp::messages;
using namespace ocpp::messages::ocpp21;
using namespace ocpp::types;
using namespace ocpp::types::ocpp21;

namespace ocpp
{
namespace localcontroller
{
namespace ocpp21
{

/** @brief Instanciate local controller's charge point proxy from a central system's charge point proxy */
std::shared_ptr<IChargePointProxy21> IChargePointProxy21::createFrom(
    std::shared_ptr<ocpp::centralsystem::ocpp21::ICentralSystem21::IChargePoint21>& central_system_proxy,
    const ocpp::config::ILocalControllerConfig21&                         stack_config,
    ocpp::rpc::RpcPool&                                                 rpc_pool)
{
    std::shared_ptr<IChargePointProxy21> proxy;

    // Instanciation can only be done from centralsytem::ChargePointProxy instance
    ocpp::centralsystem::ocpp21::ChargePointProxy21* cs_proxy = dynamic_cast<ocpp::centralsystem::ocpp21::ChargePointProxy21*>(central_system_proxy.get());
    if (cs_proxy)
    {
        // Create associated Central System proxy
        CentralSystemProxy21* centralsystem = new CentralSystemProxy21(
            cs_proxy->identifier(), cs_proxy->messagesValidator(), cs_proxy->messagesConverter(), stack_config, rpc_pool);

        // Create the proxy
        proxy = std::shared_ptr<IChargePointProxy21>(new ChargePointProxy21(cs_proxy->identifier(),
                                                                        cs_proxy->rpcClient(),
                                                                        cs_proxy->messagesValidator(),
                                                                        cs_proxy->messagesConverter(),
                                                                        stack_config,
                                                                        std::shared_ptr<ICentralSystemProxy21>(centralsystem)));

        // Associate both
        centralsystem->setChargePointProxy(proxy);

        // Unregister old proxy from RPC spy events
        cs_proxy->unregisterFromRpcSpy();
    }

    return proxy;
}

/** @brief Constructor */
ChargePointProxy21::ChargePointProxy21(const std::string&                               identifier,
                                   std::shared_ptr<ocpp::rpc::RpcServer::Client>    rpc,
                                   const ocpp::messages::ocpp21::MessagesValidator21& messages_validator,
                                   ocpp::messages::ocpp21::MessagesConverter21&       messages_converter,
                                   const ocpp::config::ILocalControllerConfig21&      stack_config,
                                   std::shared_ptr<ICentralSystemProxy21>             central_system)
    : m_identifier(identifier),
      m_rpc(rpc),
      m_messages_converter(messages_converter),
      m_msg_dispatcher(messages_validator),
      m_msg_sender(*m_rpc, messages_converter, messages_validator, stack_config.callRequestTimeout()),
      m_central_system(central_system),
      m_handler(m_identifier, messages_converter, m_msg_dispatcher, *central_system.get()),
      m_listener(nullptr),
      m_user_handlers()
{
    m_rpc->registerSpy(*this);
    m_rpc->registerListener(*this);
}

/** @brief Destructor */
ChargePointProxy21::~ChargePointProxy21()
{
    // Disconnect from the charge point
    m_rpc->disconnect(false);

    // Disconnect from the central system
    m_central_system->disconnect();
}

// IChargePointProxy interface

/** @copydoc const std::string& IChargePointProxy::ipAddress() const */
const std::string& ChargePointProxy21::ipAddress() const
{
    return m_rpc->ipAddress();
}

/** @copydoc void IChargePointProxy::setTimeout(std::chrono::milliseconds) */
void ChargePointProxy21::setTimeout(std::chrono::milliseconds timeout)
{
    m_msg_sender.setTimeout(timeout);
}

/** @copydoc void IChargePointProxy::disconnect() */
void ChargePointProxy21::disconnect()
{
    // Disconnect from the charge point
    m_rpc->disconnect(true);

    // Disconnect from the central system
    m_central_system->disconnect();
}

// OCPP operations
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::AFRRSignalReq&,
 *                                          ocpp::messages::ocpp21::AFRRSignalConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::AFRRSignalReq& request,
                              ocpp::messages::ocpp21::AFRRSignalConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(AFRRSIGNAL_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::AdjustPeriodicEventStreamReq&,
 *                                          ocpp::messages::ocpp21::AdjustPeriodicEventStreamConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::AdjustPeriodicEventStreamReq& request,
                              ocpp::messages::ocpp21::AdjustPeriodicEventStreamConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(ADJUSTPERIODICEVENTSTREAM_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::CancelReservationReq&,
 *                                          ocpp::messages::ocpp21::CancelReservationConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::CancelReservationReq& request,
                              ocpp::messages::ocpp21::CancelReservationConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(CANCELRESERVATION_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::CertificateSignedReq&,
 *                                          ocpp::messages::ocpp21::CertificateSignedConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::CertificateSignedReq& request,
                              ocpp::messages::ocpp21::CertificateSignedConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(CERTIFICATESIGNED_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ChangeAvailabilityReq&,
 *                                          ocpp::messages::ocpp21::ChangeAvailabilityConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::ChangeAvailabilityReq& request,
                              ocpp::messages::ocpp21::ChangeAvailabilityConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(CHANGEAVAILABILITY_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ChangeTransactionTariffReq&,
 *                                          ocpp::messages::ocpp21::ChangeTransactionTariffConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::ChangeTransactionTariffReq& request,
                              ocpp::messages::ocpp21::ChangeTransactionTariffConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(CHANGETRANSACTIONTARIFF_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ClearCacheReq&,
 *                                          ocpp::messages::ocpp21::ClearCacheConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::ClearCacheReq& request,
                              ocpp::messages::ocpp21::ClearCacheConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(CLEARCACHE_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ClearChargingProfileReq&,
 *                                          ocpp::messages::ocpp21::ClearChargingProfileConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::ClearChargingProfileReq& request,
                              ocpp::messages::ocpp21::ClearChargingProfileConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(CLEARCHARGINGPROFILE_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ClearDERControlReq&,
 *                                          ocpp::messages::ocpp21::ClearDERControlConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::ClearDERControlReq& request,
                              ocpp::messages::ocpp21::ClearDERControlConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(CLEARDERCONTROL_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ClearDisplayMessageReq&,
 *                                          ocpp::messages::ocpp21::ClearDisplayMessageConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::ClearDisplayMessageReq& request,
                              ocpp::messages::ocpp21::ClearDisplayMessageConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(CLEARDISPLAYMESSAGE_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ClearTariffsReq&,
 *                                          ocpp::messages::ocpp21::ClearTariffsConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::ClearTariffsReq& request,
                              ocpp::messages::ocpp21::ClearTariffsConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(CLEARTARIFFS_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ClearVariableMonitoringReq&,
 *                                          ocpp::messages::ocpp21::ClearVariableMonitoringConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::ClearVariableMonitoringReq& request,
                              ocpp::messages::ocpp21::ClearVariableMonitoringConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(CLEARVARIABLEMONITORING_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ClosePeriodicEventStreamReq&,
 *                                          ocpp::messages::ocpp21::ClosePeriodicEventStreamConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::ClosePeriodicEventStreamReq& request,
                              ocpp::messages::ocpp21::ClosePeriodicEventStreamConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(CLOSEPERIODICEVENTSTREAM_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::CustomerInformationReq&,
 *                                          ocpp::messages::ocpp21::CustomerInformationConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::CustomerInformationReq& request,
                              ocpp::messages::ocpp21::CustomerInformationConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(CUSTOMERINFORMATION_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::DataTransferReq&,
 *                                          ocpp::messages::ocpp21::DataTransferConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::DataTransferReq& request,
                              ocpp::messages::ocpp21::DataTransferConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(DATATRANSFER_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::DeleteCertificateReq&,
 *                                          ocpp::messages::ocpp21::DeleteCertificateConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::DeleteCertificateReq& request,
                              ocpp::messages::ocpp21::DeleteCertificateConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(DELETECERTIFICATE_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::Get15118EVCertificateReq&,
 *                                          ocpp::messages::ocpp21::Get15118EVCertificateConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::Get15118EVCertificateReq& request,
                              ocpp::messages::ocpp21::Get15118EVCertificateConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(GET15118EVCERTIFICATE_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetBaseReportReq&,
 *                                          ocpp::messages::ocpp21::GetBaseReportConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::GetBaseReportReq& request,
                              ocpp::messages::ocpp21::GetBaseReportConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(GETBASEREPORT_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetCertificateChainStatusReq&,
 *                                          ocpp::messages::ocpp21::GetCertificateChainStatusConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::GetCertificateChainStatusReq& request,
                              ocpp::messages::ocpp21::GetCertificateChainStatusConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(GETCERTIFICATECHAINSTATUS_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetCertificateStatusReq&,
 *                                          ocpp::messages::ocpp21::GetCertificateStatusConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::GetCertificateStatusReq& request,
                              ocpp::messages::ocpp21::GetCertificateStatusConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(GETCERTIFICATESTATUS_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetChargingProfilesReq&,
 *                                          ocpp::messages::ocpp21::GetChargingProfilesConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::GetChargingProfilesReq& request,
                              ocpp::messages::ocpp21::GetChargingProfilesConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(GETCHARGINGPROFILES_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetCompositeScheduleReq&,
 *                                          ocpp::messages::ocpp21::GetCompositeScheduleConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::GetCompositeScheduleReq& request,
                              ocpp::messages::ocpp21::GetCompositeScheduleConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(GETCOMPOSITESCHEDULE_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetDERControlReq&,
 *                                          ocpp::messages::ocpp21::GetDERControlConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::GetDERControlReq& request,
                              ocpp::messages::ocpp21::GetDERControlConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(GETDERCONTROL_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetDisplayMessagesReq&,
 *                                          ocpp::messages::ocpp21::GetDisplayMessagesConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::GetDisplayMessagesReq& request,
                              ocpp::messages::ocpp21::GetDisplayMessagesConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(GETDISPLAYMESSAGES_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetInstalledCertificateIdsReq&,
 *                                          ocpp::messages::ocpp21::GetInstalledCertificateIdsConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::GetInstalledCertificateIdsReq& request,
                              ocpp::messages::ocpp21::GetInstalledCertificateIdsConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(GETINSTALLEDCERTIFICATEIDS_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetLocalListVersionReq&,
 *                                          ocpp::messages::ocpp21::GetLocalListVersionConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::GetLocalListVersionReq& request,
                              ocpp::messages::ocpp21::GetLocalListVersionConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(GETLOCALLISTVERSION_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetLogReq&,
 *                                          ocpp::messages::ocpp21::GetLogConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::GetLogReq& request,
                              ocpp::messages::ocpp21::GetLogConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(GETLOG_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetMonitoringReportReq&,
 *                                          ocpp::messages::ocpp21::GetMonitoringReportConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::GetMonitoringReportReq& request,
                              ocpp::messages::ocpp21::GetMonitoringReportConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(GETMONITORINGREPORT_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetPeriodicEventStreamReq&,
 *                                          ocpp::messages::ocpp21::GetPeriodicEventStreamConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::GetPeriodicEventStreamReq& request,
                              ocpp::messages::ocpp21::GetPeriodicEventStreamConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(GETPERIODICEVENTSTREAM_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetReportReq&,
 *                                          ocpp::messages::ocpp21::GetReportConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::GetReportReq& request,
                              ocpp::messages::ocpp21::GetReportConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(GETREPORT_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetTariffsReq&,
 *                                          ocpp::messages::ocpp21::GetTariffsConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::GetTariffsReq& request,
                              ocpp::messages::ocpp21::GetTariffsConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(GETTARIFFS_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetTransactionStatusReq&,
 *                                          ocpp::messages::ocpp21::GetTransactionStatusConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::GetTransactionStatusReq& request,
                              ocpp::messages::ocpp21::GetTransactionStatusConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(GETTRANSACTIONSTATUS_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::GetVariablesReq&,
 *                                          ocpp::messages::ocpp21::GetVariablesConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::GetVariablesReq& request,
                              ocpp::messages::ocpp21::GetVariablesConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(GETVARIABLES_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::InstallCertificateReq&,
 *                                          ocpp::messages::ocpp21::InstallCertificateConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::InstallCertificateReq& request,
                              ocpp::messages::ocpp21::InstallCertificateConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(INSTALLCERTIFICATE_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::OpenPeriodicEventStreamReq&,
 *                                          ocpp::messages::ocpp21::OpenPeriodicEventStreamConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::OpenPeriodicEventStreamReq& request,
                              ocpp::messages::ocpp21::OpenPeriodicEventStreamConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(OPENPERIODICEVENTSTREAM_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::PublishFirmwareReq&,
 *                                          ocpp::messages::ocpp21::PublishFirmwareConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::PublishFirmwareReq& request,
                              ocpp::messages::ocpp21::PublishFirmwareConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(PUBLISHFIRMWARE_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::RequestBatterySwapReq&,
 *                                          ocpp::messages::ocpp21::RequestBatterySwapConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::RequestBatterySwapReq& request,
                              ocpp::messages::ocpp21::RequestBatterySwapConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(REQUESTBATTERYSWAP_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::RequestStartTransactionReq&,
 *                                          ocpp::messages::ocpp21::RequestStartTransactionConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::RequestStartTransactionReq& request,
                              ocpp::messages::ocpp21::RequestStartTransactionConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(REQUESTSTARTTRANSACTION_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::RequestStopTransactionReq&,
 *                                          ocpp::messages::ocpp21::RequestStopTransactionConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::RequestStopTransactionReq& request,
                              ocpp::messages::ocpp21::RequestStopTransactionConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(REQUESTSTOPTRANSACTION_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ReserveNowReq&,
 *                                          ocpp::messages::ocpp21::ReserveNowConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::ReserveNowReq& request,
                              ocpp::messages::ocpp21::ReserveNowConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(RESERVENOW_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::ResetReq&,
 *                                          ocpp::messages::ocpp21::ResetConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::ResetReq& request,
                              ocpp::messages::ocpp21::ResetConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(RESET_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::SendLocalListReq&,
 *                                          ocpp::messages::ocpp21::SendLocalListConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::SendLocalListReq& request,
                              ocpp::messages::ocpp21::SendLocalListConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(SENDLOCALLIST_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::SetChargingProfileReq&,
 *                                          ocpp::messages::ocpp21::SetChargingProfileConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::SetChargingProfileReq& request,
                              ocpp::messages::ocpp21::SetChargingProfileConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(SETCHARGINGPROFILE_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::SetDefaultTariffReq&,
 *                                          ocpp::messages::ocpp21::SetDefaultTariffConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::SetDefaultTariffReq& request,
                              ocpp::messages::ocpp21::SetDefaultTariffConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(SETDEFAULTTARIFF_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::SetDERControlReq&,
 *                                          ocpp::messages::ocpp21::SetDERControlConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::SetDERControlReq& request,
                              ocpp::messages::ocpp21::SetDERControlConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(SETDERCONTROL_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::SetDisplayMessageReq&,
 *                                          ocpp::messages::ocpp21::SetDisplayMessageConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::SetDisplayMessageReq& request,
                              ocpp::messages::ocpp21::SetDisplayMessageConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(SETDISPLAYMESSAGE_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::SetMonitoringBaseReq&,
 *                                          ocpp::messages::ocpp21::SetMonitoringBaseConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::SetMonitoringBaseReq& request,
                              ocpp::messages::ocpp21::SetMonitoringBaseConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(SETMONITORINGBASE_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::SetMonitoringLevelReq&,
 *                                          ocpp::messages::ocpp21::SetMonitoringLevelConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::SetMonitoringLevelReq& request,
                              ocpp::messages::ocpp21::SetMonitoringLevelConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(SETMONITORINGLEVEL_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::SetNetworkProfileReq&,
 *                                          ocpp::messages::ocpp21::SetNetworkProfileConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::SetNetworkProfileReq& request,
                              ocpp::messages::ocpp21::SetNetworkProfileConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(SETNETWORKPROFILE_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::SetVariableMonitoringReq&,
 *                                          ocpp::messages::ocpp21::SetVariableMonitoringConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::SetVariableMonitoringReq& request,
                              ocpp::messages::ocpp21::SetVariableMonitoringConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(SETVARIABLEMONITORING_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::SetVariablesReq&,
 *                                          ocpp::messages::ocpp21::SetVariablesConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::SetVariablesReq& request,
                              ocpp::messages::ocpp21::SetVariablesConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(SETVARIABLES_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::TriggerMessageReq&,
 *                                          ocpp::messages::ocpp21::TriggerMessageConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::TriggerMessageReq& request,
                              ocpp::messages::ocpp21::TriggerMessageConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(TRIGGERMESSAGE_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::UnlockConnectorReq&,
 *                                          ocpp::messages::ocpp21::UnlockConnectorConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::UnlockConnectorReq& request,
                              ocpp::messages::ocpp21::UnlockConnectorConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(UNLOCKCONNECTOR_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::UnpublishFirmwareReq&,
 *                                          ocpp::messages::ocpp21::UnpublishFirmwareConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::UnpublishFirmwareReq& request,
                              ocpp::messages::ocpp21::UnpublishFirmwareConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(UNPUBLISHFIRMWARE_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::UpdateDynamicScheduleReq&,
 *                                          ocpp::messages::ocpp21::UpdateDynamicScheduleConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::UpdateDynamicScheduleReq& request,
                              ocpp::messages::ocpp21::UpdateDynamicScheduleConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(UPDATEDYNAMICSCHEDULE_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::UpdateFirmwareReq&,
 *                                          ocpp::messages::ocpp21::UpdateFirmwareConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::UpdateFirmwareReq& request,
                              ocpp::messages::ocpp21::UpdateFirmwareConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(UPDATEFIRMWARE_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::call(const ocpp::messages::ocpp21::UsePriorityChargingReq&,
 *                                          ocpp::messages::ocpp21::UsePriorityChargingConf&,
 *                                          std::string&,
 *                                          std::string&) */
bool ChargePointProxy21::call(const ocpp::messages::ocpp21::UsePriorityChargingReq& request,
                              ocpp::messages::ocpp21::UsePriorityChargingConf&      response,
                              std::string&                                       error,
                              std::string&                                       message)
{
    return call(USEPRIORITYCHARGING_ACTION, request, response, error, message);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::AuthorizeReq&, ocpp::messages::ocpp21::AuthorizeConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::AuthorizeReq&, ocpp::messages::ocpp21::AuthorizeConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(AUTHORIZE_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::BatterySwapReq&, ocpp::messages::ocpp21::BatterySwapConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::BatterySwapReq&, ocpp::messages::ocpp21::BatterySwapConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(BATTERYSWAP_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::BootNotificationReq&, ocpp::messages::ocpp21::BootNotificationConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::BootNotificationReq&, ocpp::messages::ocpp21::BootNotificationConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(BOOTNOTIFICATION_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::ClearedChargingLimitReq&, ocpp::messages::ocpp21::ClearedChargingLimitConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::ClearedChargingLimitReq&, ocpp::messages::ocpp21::ClearedChargingLimitConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(CLEAREDCHARGINGLIMIT_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::CostUpdatedReq&, ocpp::messages::ocpp21::CostUpdatedConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::CostUpdatedReq&, ocpp::messages::ocpp21::CostUpdatedConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(COSTUPDATED_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::DataTransferReq&, ocpp::messages::ocpp21::DataTransferConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::DataTransferReq&, ocpp::messages::ocpp21::DataTransferConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(DATATRANSFER_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::FirmwareStatusNotificationReq&, ocpp::messages::ocpp21::FirmwareStatusNotificationConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::FirmwareStatusNotificationReq&, ocpp::messages::ocpp21::FirmwareStatusNotificationConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(FIRMWARESTATUSNOTIFICATION_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::HeartbeatReq&, ocpp::messages::ocpp21::HeartbeatConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::HeartbeatReq&, ocpp::messages::ocpp21::HeartbeatConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(HEARTBEAT_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::LogStatusNotificationReq&, ocpp::messages::ocpp21::LogStatusNotificationConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::LogStatusNotificationReq&, ocpp::messages::ocpp21::LogStatusNotificationConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(LOGSTATUSNOTIFICATION_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::MeterValuesReq&, ocpp::messages::ocpp21::MeterValuesConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::MeterValuesReq&, ocpp::messages::ocpp21::MeterValuesConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(METERVALUES_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyAllowedEnergyTransferReq&, ocpp::messages::ocpp21::NotifyAllowedEnergyTransferConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::NotifyAllowedEnergyTransferReq&, ocpp::messages::ocpp21::NotifyAllowedEnergyTransferConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(NOTIFYALLOWEDENERGYTRANSFER_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyChargingLimitReq&, ocpp::messages::ocpp21::NotifyChargingLimitConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::NotifyChargingLimitReq&, ocpp::messages::ocpp21::NotifyChargingLimitConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(NOTIFYCHARGINGLIMIT_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyCustomerInformationReq&, ocpp::messages::ocpp21::NotifyCustomerInformationConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::NotifyCustomerInformationReq&, ocpp::messages::ocpp21::NotifyCustomerInformationConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(NOTIFYCUSTOMERINFORMATION_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyDERAlarmReq&, ocpp::messages::ocpp21::NotifyDERAlarmConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::NotifyDERAlarmReq&, ocpp::messages::ocpp21::NotifyDERAlarmConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(NOTIFYDERALARM_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyDERStartStopReq&, ocpp::messages::ocpp21::NotifyDERStartStopConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::NotifyDERStartStopReq&, ocpp::messages::ocpp21::NotifyDERStartStopConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(NOTIFYDERSTARTSTOP_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyDisplayMessagesReq&, ocpp::messages::ocpp21::NotifyDisplayMessagesConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::NotifyDisplayMessagesReq&, ocpp::messages::ocpp21::NotifyDisplayMessagesConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(NOTIFYDISPLAYMESSAGES_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyEVChargingNeedsReq&, ocpp::messages::ocpp21::NotifyEVChargingNeedsConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::NotifyEVChargingNeedsReq&, ocpp::messages::ocpp21::NotifyEVChargingNeedsConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(NOTIFYEVCHARGINGNEEDS_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyEVChargingScheduleReq&, ocpp::messages::ocpp21::NotifyEVChargingScheduleConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::NotifyEVChargingScheduleReq&, ocpp::messages::ocpp21::NotifyEVChargingScheduleConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(NOTIFYEVCHARGINGSCHEDULE_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyEventReq&, ocpp::messages::ocpp21::NotifyEventConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::NotifyEventReq&, ocpp::messages::ocpp21::NotifyEventConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(NOTIFYEVENT_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyMonitoringReportReq&, ocpp::messages::ocpp21::NotifyMonitoringReportConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::NotifyMonitoringReportReq&, ocpp::messages::ocpp21::NotifyMonitoringReportConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(NOTIFYMONITORINGREPORT_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyPeriodicEventStreamReq&, ocpp::messages::ocpp21::NotifyPeriodicEventStreamConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::NotifyPeriodicEventStreamReq&, ocpp::messages::ocpp21::NotifyPeriodicEventStreamConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(NOTIFYPERIODICEVENTSTREAM_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyPriorityChargingReq&, ocpp::messages::ocpp21::NotifyPriorityChargingConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::NotifyPriorityChargingReq&, ocpp::messages::ocpp21::NotifyPriorityChargingConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(NOTIFYPRIORITYCHARGING_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyReportReq&, ocpp::messages::ocpp21::NotifyReportConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::NotifyReportReq&, ocpp::messages::ocpp21::NotifyReportConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(NOTIFYREPORT_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifySettlementReq&, ocpp::messages::ocpp21::NotifySettlementConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::NotifySettlementReq&, ocpp::messages::ocpp21::NotifySettlementConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(NOTIFYSETTLEMENT_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::NotifyWebPaymentStartedReq&, ocpp::messages::ocpp21::NotifyWebPaymentStartedConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::NotifyWebPaymentStartedReq&, ocpp::messages::ocpp21::NotifyWebPaymentStartedConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(NOTIFYWEBPAYMENTSTARTED_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::PublishFirmwareStatusNotificationReq&, ocpp::messages::ocpp21::PublishFirmwareStatusNotificationConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::PublishFirmwareStatusNotificationReq&, ocpp::messages::ocpp21::PublishFirmwareStatusNotificationConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(PUBLISHFIRMWARESTATUSNOTIFICATION_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::PullDynamicScheduleUpdateReq&, ocpp::messages::ocpp21::PullDynamicScheduleUpdateConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::PullDynamicScheduleUpdateReq&, ocpp::messages::ocpp21::PullDynamicScheduleUpdateConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(PULLDYNAMICSCHEDULEUPDATE_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::ReportChargingProfilesReq&, ocpp::messages::ocpp21::ReportChargingProfilesConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::ReportChargingProfilesReq&, ocpp::messages::ocpp21::ReportChargingProfilesConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(REPORTCHARGINGPROFILES_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::ReportDERControlReq&, ocpp::messages::ocpp21::ReportDERControlConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::ReportDERControlReq&, ocpp::messages::ocpp21::ReportDERControlConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(REPORTDERCONTROL_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::ReservationStatusUpdateReq&, ocpp::messages::ocpp21::ReservationStatusUpdateConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::ReservationStatusUpdateReq&, ocpp::messages::ocpp21::ReservationStatusUpdateConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(RESERVATIONSTATUSUPDATE_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::SecurityEventNotificationReq&, ocpp::messages::ocpp21::SecurityEventNotificationConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::SecurityEventNotificationReq&, ocpp::messages::ocpp21::SecurityEventNotificationConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(SECURITYEVENTNOTIFICATION_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::SignCertificateReq&, ocpp::messages::ocpp21::SignCertificateConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::SignCertificateReq&, ocpp::messages::ocpp21::SignCertificateConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(SIGNCERTIFICATE_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::StatusNotificationReq&, ocpp::messages::ocpp21::StatusNotificationConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::StatusNotificationReq&, ocpp::messages::ocpp21::StatusNotificationConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(STATUSNOTIFICATION_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::TransactionEventReq&, ocpp::messages::ocpp21::TransactionEventConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::TransactionEventReq&, ocpp::messages::ocpp21::TransactionEventConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(TRANSACTIONEVENT_ACTION, handler);
}
/** @copydoc bool IChargePointProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::VatNumberValidationReq&, ocpp::messages::ocpp21::VatNumberValidationConf&, std::string&, std::string&)>) */
bool ChargePointProxy21::registerHandler(
    std::function<bool(
        const ocpp::messages::ocpp21::VatNumberValidationReq&, ocpp::messages::ocpp21::VatNumberValidationConf&, std::string&, std::string&)>
        handler)
{
    return registerHandler(VATNUMBERVALIDATION_ACTION, handler);
}

// IRpc::IListener interface

/** @copydoc void IRpc::IListener::rpcDisconnected() */
void ChargePointProxy21::rpcDisconnected()
{
    LOG_WARNING << "[" << m_identifier << "] - Disconnected from Charge Point";

    // Disconnect from the central system
    m_central_system->disconnect();

    // Notify listener
    if (m_listener)
    {
        m_listener->disconnectedFromChargePoint();
    }
}

/** @copydoc void IRpc::IListener::rpcError() */
void ChargePointProxy21::rpcError()
{
    LOG_ERROR << "[" << m_identifier << "] - Connection error";
}

/** @copydoc bool IRpc::IListener::rpcCallReceived(const std::string&,
                                                   const rapidjson::Value&,
                                                   rapidjson::Document&,
                                                   std::string&,
                                                   std::string&) */
bool ChargePointProxy21::rpcCallReceived(const std::string&      action,
                                       const rapidjson::Value& payload,
                                       rapidjson::Document&    response,
                                       std::string&            error_code,
                                       std::string&            error_message)
{
    return m_msg_dispatcher.dispatchMessage(action, payload, response, error_code, error_message);
}

// IRpc::ISpy interface

/** @copydoc void IRpc::ISpy::rcpMessageReceived(const std::string& msg) */
void ChargePointProxy21::rcpMessageReceived(const std::string& msg)
{
    LOG_COM << "[" << m_identifier << "] - RX : " << msg;
}

void ChargePointProxy21::rcpMessageSent(const std::string& msg)
{
    LOG_COM << "[" << m_identifier << "] - TX : " << msg;
}

} // namespace ocpp21
} // namespace localcontroller
} // namespace ocpp