/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/* Generated by json2cpp */

#ifndef OPENOCPP_OCPP20_ICHARGEPOINT20_H
#define OPENOCPP_OCPP20_ICHARGEPOINT20_H

#include "Authorize20.h"
#include "BootNotification20.h"
#include "DataTransfer20.h"
#include "FirmwareStatusNotification20.h"
#include "Heartbeat20.h"
#include "IChargePointConfig20.h"
#include "IChargePointEventsHandler20.h"
#include "IDeviceModel20.h"
#include "INotifyManager20.h"
#include "ISecurityManager20.h"
#include "ITransactionManager20.h"
#include "LogStatusNotification20.h"
#include "MeterValues20.h"
#include "IMeterValuesManager20.h"
#include "ISmartChargingManager20.h"
#include "PublishFirmwareStatusNotification20.h"
#include "ReportChargingProfiles20.h"
#include "ReservationStatusUpdate20.h"
#include "StatusNotification20.h"
#include "TransactionEvent20.h"

#include <memory>

namespace ocpp
{
namespace helpers
{
class ITimerPool;
class WorkerThreadPool;
} // namespace helpers
namespace database
{
class Database;
} // namespace database

namespace chargepoint
{
namespace ocpp20
{

/** @brief Interface for charge point implementations */
class IChargePoint20
{
  public:
    /**
     * @brief Instanciate a charge point
     * @param stack_config Stack configuration
     * @param event_handler Stack event handler
     */
    static std::unique_ptr<IChargePoint20> create(const ocpp::config::IChargePointConfig20& stack_config,
                                                  IChargePointEventsHandler20&              events_handler);

    /**
     * @brief Instanciate a charge point with a device model
     * @param stack_config Stack configuration
     * @param device_model Device model
     * @param event_handler Stack event handler
     */
    static std::unique_ptr<IChargePoint20> create(const ocpp::config::IChargePointConfig20& stack_config,
                                                  IDeviceModel&                             device_model,
                                                  IChargePointEventsHandler20&              events_handler);

    /**
     * @brief Instanciate a charge point with the provided timer and worker pools
     *        To use when you have to instanciate multiple Central System / Charge Point
     *        => Allow to reduce thread and memory usage
     * @param stack_config Stack configuration
     * @param event_handler Stack event handler
     * @param timer_pool Timer pool
     * @param worker_pool Worker thread pool
     */
    static std::unique_ptr<IChargePoint20> create(const ocpp::config::IChargePointConfig20&        stack_config,
                                                  IChargePointEventsHandler20&                     events_handler,
                                                  std::shared_ptr<ocpp::helpers::ITimerPool>       timer_pool,
                                                  std::shared_ptr<ocpp::helpers::WorkerThreadPool> worker_pool);

    /**
     * @brief Instanciate a charge point with the provided timer and worker pools and a device model
     * @param stack_config Stack configuration
     * @param device_model Device model
     * @param event_handler Stack event handler
     * @param timer_pool Timer pool
     * @param worker_pool Worker thread pool
     */
    static std::unique_ptr<IChargePoint20> create(const ocpp::config::IChargePointConfig20&        stack_config,
                                                  IDeviceModel&                                    device_model,
                                                  IChargePointEventsHandler20&                     events_handler,
                                                  std::shared_ptr<ocpp::helpers::ITimerPool>       timer_pool,
                                                  std::shared_ptr<ocpp::helpers::WorkerThreadPool> worker_pool);

    /** @brief Destructor */
    virtual ~IChargePoint20() { }

    /**
     * @brief Get the timer pool associated to the charge point
     * @return Timer pool associated to the charge point
     */
    virtual ocpp::helpers::ITimerPool& getTimerPool() = 0;

    /**
     * @brief Get the worker pool associated to the charge point
     * @return Worker pool associated to the charge point
     */
    virtual ocpp::helpers::WorkerThreadPool& getWorkerPool() = 0;

    /**
     * @brief Get the Notify messages manager associated to the charge point
     * @return Notify messages manager associated to the charge point
     */
    virtual INotifyManager20& getNotifyManager() = 0;

    /**
     * @brief Get the security manager associated to the charge point
     * @return Security manager associated to the charge point
     */
    virtual ISecurityManager20& getSecurityManager() = 0;

    /**
     * @brief Get the smart charging manager associated to the charge point
     * @return Smart charging manager associated to the charge point
     */
    virtual ISmartChargingManager20& getSmartChargingManager() = 0;

    /**
     * @brief Get the transaction manager associated to the charge point
     * @return Transaction manager associated to the charge point
     */
    virtual ITransactionManager20& getTransactionManager() = 0;

    /**
     * @brief Reset the charge point's internal data (can be done only when the charge point is stopped)
     * @return true if the data has been reset, false otherwise
     */
    virtual bool resetData() = 0;

    /**
     * @brief Start the charge point
     * @return true if the charge point has been started, false otherwise
     */
    virtual bool start() = 0;

    /**
     * @brief Stop the charge point
     * @return true if the charge point has been stopped, false otherwise
     */
    virtual bool stop() = 0;

    /**
     * @brief Triggers a reconnexion of the charge point to the Central System
     * @return true if the reconnexion has been scheduled, false otherwise
     */
    virtual bool reconnect() = 0;

    /**
     * @brief Start a transaction and send the corresponding TransactionEvent
     * @param evse_id EVSE identifier
     * @param connector_id Connector identifier
     * @param id_token Id token used to authorize the transaction
     * @param trigger_reason Reason for the transaction event
     * @param transaction_id Generated transaction id
     * @return true if the transaction has been started, false otherwise
     */
    virtual bool startTransaction(unsigned int                                evse_id,
                                  unsigned int                                connector_id,
                                  const ocpp::types::ocpp20::IdTokenType&     id_token,
                                  ocpp::types::ocpp20::TriggerReasonEnumType trigger_reason,
                                  std::string&                                transaction_id) = 0;

    /**
     * @brief Start a transaction initiated by a remote start request and send the corresponding TransactionEvent
     * @param evse_id EVSE identifier
     * @param connector_id Connector identifier
     * @param id_token Id token used to authorize the transaction
     * @param trigger_reason Reason for the transaction event
     * @param remote_start_id Remote start identifier received from the CSMS
     * @param transaction_id Generated transaction id
     * @return true if the transaction has been started, false otherwise
     */
    virtual bool startTransaction(unsigned int                                evse_id,
                                  unsigned int                                connector_id,
                                  const ocpp::types::ocpp20::IdTokenType&     id_token,
                                  ocpp::types::ocpp20::TriggerReasonEnumType trigger_reason,
                                  int                                         remote_start_id,
                                  std::string&                                transaction_id) = 0;

    /**
     * @brief Start a transaction and send the corresponding TransactionEvent
     * @param evse_id EVSE identifier
     * @param connector_id Connector identifier
     * @param id_token Id token string used to authorize the transaction
     * @param transaction_id Generated transaction id
     * @return true if the transaction has been started, false otherwise
     */
    virtual bool startTransaction(unsigned int       evse_id,
                                  unsigned int       connector_id,
                                  const std::string& id_token,
                                  std::string&       transaction_id) = 0;

    /**
     * @brief Send an update for an ongoing transaction
     * @param transaction_id Transaction id
     * @param trigger_reason Reason for the transaction event
     * @param meter_values Optional meter values to include
     * @return true if the transaction update has been sent, false otherwise
     */
    virtual bool updateTransaction(const std::string&                                      transaction_id,
                                   ocpp::types::ocpp20::TriggerReasonEnumType              trigger_reason,
                                   const std::vector<ocpp::types::ocpp20::MeterValueType>& meter_values) = 0;

    /**
     * @brief Check if a transaction is active
     * @param transaction_id Transaction id
     * @return true if the transaction is active, false otherwise
     */
    virtual bool hasActiveTransaction(const std::string& transaction_id) = 0;

    /**
     * @brief Stop a transaction and send the corresponding TransactionEvent
     * @param transaction_id Transaction id
     * @param reason Stop reason
     * @param trigger_reason Reason for the transaction event
     * @param id_token Optional id token used to stop the transaction
     * @param meter_values Optional meter values to include
     * @return true if the transaction has been stopped, false otherwise
     */
    virtual bool stopTransaction(const std::string&                                      transaction_id,
                                 ocpp::types::ocpp20::ReasonEnumType                    reason,
                                 ocpp::types::ocpp20::TriggerReasonEnumType             trigger_reason,
                                 const ocpp::types::ocpp20::IdTokenType*                id_token,
                                 const std::vector<ocpp::types::ocpp20::MeterValueType>& meter_values) = 0;

    /**
     * @brief Stop a transaction and send the corresponding TransactionEvent
     * @param transaction_id Transaction id
     * @param id_token Id token string used to stop the transaction (leave empty if no id token)
     * @param reason Stop reason
     * @return true if the transaction has been stopped, false otherwise
     */
    virtual bool stopTransaction(const std::string&                       transaction_id,
                                 const std::string&                       id_token,
                                 ocpp::types::ocpp20::ReasonEnumType     reason) = 0;

    /**
     * @brief Start periodic MeterValues sampling for an EVSE
     * @param evse_id EVSE identifier
     * @param interval Sampling interval
     */
    virtual void startPeriodicMeterValues(unsigned int evse_id, std::chrono::seconds interval) = 0;

    /**
     * @brief Stop periodic MeterValues sampling for an EVSE
     * @param evse_id EVSE identifier
     */
    virtual void stopPeriodicMeterValues(unsigned int evse_id) = 0;

    /**
     * @brief Start transaction sampled meter values
     * @param transaction_id Transaction id
     * @param evse_id EVSE identifier
     * @param interval Sampling interval
     */
    virtual void startTransactionSampledMeterValues(const std::string& transaction_id,
                                                    unsigned int       evse_id,
                                                    std::chrono::seconds interval) = 0;

    /**
     * @brief Stop transaction sampled meter values
     * @param transaction_id Transaction id
     */
    virtual void stopTransactionSampledMeterValues(const std::string& transaction_id) = 0;

    /**
     * @brief Get stored transaction stop meter values
     * @param transaction_id Transaction id
     * @param meter_values Stored meter values
     */
    virtual void getTxStopMeterValues(const std::string& transaction_id,
                                      std::vector<ocpp::types::ocpp20::MeterValueType>& meter_values) = 0;

    /**
     * @brief Get the active smart charging setpoints for an EVSE and for the whole charging station
     * @param evse_id Id of the EVSE
     * @param charging_station_setpoint Charging station setpoint, if any
     * @param evse_setpoint EVSE setpoint, if any
     * @param unit Expected setpoint unit
     * @return true if at least one setpoint has been computed, false otherwise
     */
    virtual bool getSetpoint(unsigned int                                                 evse_id,
                             ocpp::types::Optional<ISmartChargingManager20::SmartChargingSetpoint>& charging_station_setpoint,
                             ocpp::types::Optional<ISmartChargingManager20::SmartChargingSetpoint>& evse_setpoint,
                             ocpp::types::ocpp20::ChargingRateUnitEnumType unit = ocpp::types::ocpp20::ChargingRateUnitEnumType::A) = 0;

    /**
     * @brief Notify a new status for a connector
     * @param evse_id Id of the EVSE
     * @param connector_id Id of the connector
     * @param status Status of the connector
     * @return true if the status has been notified, false otherwise
     */
    virtual bool statusNotification(unsigned int                                 evse_id,
                                    unsigned int                                 connector_id,
                                    ocpp::types::ocpp20::ConnectorStatusEnumType status) = 0;

};

} // namespace ocpp20
} // namespace chargepoint
} // namespace ocpp

#endif // OPENOCPP_OCPP20_ICHARGEPOINT20_H
