/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/* Generated by json2cpp */

#ifndef OPENOCPP_OCPP21_CENTRALSYSTEMPROXY21_H
#define OPENOCPP_OCPP21_CENTRALSYSTEMPROXY21_H

#include "GenericMessageSender.h"
#include "CentralSystemHandler21.h"
#include "ICentralSystemProxy21.h"
#include "MessagesConverter21.h"
#include "MessagesValidator21.h"
#include "MessageDispatcher.h"
#include "RpcClient.h"
#include "UserMessageHandler.h"

namespace ocpp
{
namespace config
{
class ILocalControllerConfig21;
} // namespace config
namespace rpc
{
class RpcPool;
} // namespace rpc

namespace localcontroller
{
namespace ocpp21
{

/** @brief Central system proxy */
class CentralSystemProxy21 : public ICentralSystemProxy21,
                           public ocpp::rpc::IRpc::IListener,
                           public ocpp::rpc::IRpc::ISpy,
                           public ocpp::rpc::RpcClient::IListener
{
  public:
    /**
     * @brief Constructor
     * @param identifier Charge point's identifier
     * @param messages_validator JSON schemas needed to validate payloads
     * @param messages_converter Converter from/to OCPP to/from JSON messages
     * @param stack_config Stack configuration
     * @param rpc_pool RPC pool
     */
    CentralSystemProxy21(const std::string&                               identifier,
                       const ocpp::messages::ocpp21::MessagesValidator21& messages_validator,
                       ocpp::messages::ocpp21::MessagesConverter21&       messages_converter,
                       const ocpp::config::ILocalControllerConfig21&      stack_config,
                       ocpp::rpc::RpcPool&                              rpc_pool);

    /** @brief Destructor */
    virtual ~CentralSystemProxy21();

    /**
     * @brief Set the proxy to forward requests to the charge point
     * @param central_system Proxy to forward requests to the charge point
     */
    void setChargePointProxy(std::weak_ptr<IChargePointProxy21> charge_point)
    {
        m_charge_point = charge_point;
        m_handler.setChargePointProxy(charge_point);
    }

    /** @copydoc const std::string& ICentralSystemProxy21::disconnect() const */
    const std::string& identifier() const override { return m_identifier; }

    /** @copydoc void ICentralSystemProxy21::setTimeout(std::chrono::milliseconds) */
    void setTimeout(std::chrono::milliseconds timeout) override;

    /** @copydoc bool ICentralSystemProxy21::connect(const std::string&,
                                                   const ocpp::websockets::IWebsocketClient::Credentials&,
                                                   std::chrono::milliseconds,
                                                   std::chrono::milliseconds,
                                                   std::chrono::milliseconds) */
    bool connect(const std::string&                                     url,
                 const ocpp::websockets::IWebsocketClient::Credentials& credentials,
                 std::chrono::milliseconds                              connect_timeout,
                 std::chrono::milliseconds                              retry_interval,
                 std::chrono::milliseconds                              ping_interval) override;

    /** @copydoc void ICentralSystemProxy21::disconnect() */
    void disconnect() override;

    /** @brief Indicate if the connection with the central system is active */
    bool isConnected() const override;

    /** @copydoc void ICentralSystemProxy21::registerListener(ILocalControllerProxyEventsHandler21&) */
    void registerListener(ILocalControllerProxyEventsHandler21& listener) override { m_listener = &listener; }

    // OCPP actions
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::AuthorizeReq&,
     *                                          ocpp::messages::ocpp21::AuthorizeConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::AuthorizeReq& request,
              ocpp::messages::ocpp21::AuthorizeConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::BatterySwapReq&,
     *                                          ocpp::messages::ocpp21::BatterySwapConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::BatterySwapReq& request,
              ocpp::messages::ocpp21::BatterySwapConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::BootNotificationReq&,
     *                                          ocpp::messages::ocpp21::BootNotificationConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::BootNotificationReq& request,
              ocpp::messages::ocpp21::BootNotificationConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::ClearedChargingLimitReq&,
     *                                          ocpp::messages::ocpp21::ClearedChargingLimitConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::ClearedChargingLimitReq& request,
              ocpp::messages::ocpp21::ClearedChargingLimitConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::CostUpdatedReq&,
     *                                          ocpp::messages::ocpp21::CostUpdatedConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::CostUpdatedReq& request,
              ocpp::messages::ocpp21::CostUpdatedConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::DataTransferReq&,
     *                                          ocpp::messages::ocpp21::DataTransferConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::DataTransferReq& request,
              ocpp::messages::ocpp21::DataTransferConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::FirmwareStatusNotificationReq&,
     *                                          ocpp::messages::ocpp21::FirmwareStatusNotificationConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::FirmwareStatusNotificationReq& request,
              ocpp::messages::ocpp21::FirmwareStatusNotificationConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::HeartbeatReq&,
     *                                          ocpp::messages::ocpp21::HeartbeatConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::HeartbeatReq& request,
              ocpp::messages::ocpp21::HeartbeatConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::LogStatusNotificationReq&,
     *                                          ocpp::messages::ocpp21::LogStatusNotificationConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::LogStatusNotificationReq& request,
              ocpp::messages::ocpp21::LogStatusNotificationConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::MeterValuesReq&,
     *                                          ocpp::messages::ocpp21::MeterValuesConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::MeterValuesReq& request,
              ocpp::messages::ocpp21::MeterValuesConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::NotifyAllowedEnergyTransferReq&,
     *                                          ocpp::messages::ocpp21::NotifyAllowedEnergyTransferConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::NotifyAllowedEnergyTransferReq& request,
              ocpp::messages::ocpp21::NotifyAllowedEnergyTransferConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::NotifyChargingLimitReq&,
     *                                          ocpp::messages::ocpp21::NotifyChargingLimitConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::NotifyChargingLimitReq& request,
              ocpp::messages::ocpp21::NotifyChargingLimitConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::NotifyCustomerInformationReq&,
     *                                          ocpp::messages::ocpp21::NotifyCustomerInformationConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::NotifyCustomerInformationReq& request,
              ocpp::messages::ocpp21::NotifyCustomerInformationConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::NotifyDERAlarmReq&,
     *                                          ocpp::messages::ocpp21::NotifyDERAlarmConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::NotifyDERAlarmReq& request,
              ocpp::messages::ocpp21::NotifyDERAlarmConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::NotifyDERStartStopReq&,
     *                                          ocpp::messages::ocpp21::NotifyDERStartStopConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::NotifyDERStartStopReq& request,
              ocpp::messages::ocpp21::NotifyDERStartStopConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::NotifyDisplayMessagesReq&,
     *                                          ocpp::messages::ocpp21::NotifyDisplayMessagesConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::NotifyDisplayMessagesReq& request,
              ocpp::messages::ocpp21::NotifyDisplayMessagesConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::NotifyEVChargingNeedsReq&,
     *                                          ocpp::messages::ocpp21::NotifyEVChargingNeedsConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::NotifyEVChargingNeedsReq& request,
              ocpp::messages::ocpp21::NotifyEVChargingNeedsConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::NotifyEVChargingScheduleReq&,
     *                                          ocpp::messages::ocpp21::NotifyEVChargingScheduleConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::NotifyEVChargingScheduleReq& request,
              ocpp::messages::ocpp21::NotifyEVChargingScheduleConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::NotifyEventReq&,
     *                                          ocpp::messages::ocpp21::NotifyEventConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::NotifyEventReq& request,
              ocpp::messages::ocpp21::NotifyEventConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::NotifyMonitoringReportReq&,
     *                                          ocpp::messages::ocpp21::NotifyMonitoringReportConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::NotifyMonitoringReportReq& request,
              ocpp::messages::ocpp21::NotifyMonitoringReportConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::NotifyPeriodicEventStreamReq&,
     *                                          ocpp::messages::ocpp21::NotifyPeriodicEventStreamConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::NotifyPeriodicEventStreamReq& request,
              ocpp::messages::ocpp21::NotifyPeriodicEventStreamConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::NotifyPriorityChargingReq&,
     *                                          ocpp::messages::ocpp21::NotifyPriorityChargingConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::NotifyPriorityChargingReq& request,
              ocpp::messages::ocpp21::NotifyPriorityChargingConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::NotifyReportReq&,
     *                                          ocpp::messages::ocpp21::NotifyReportConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::NotifyReportReq& request,
              ocpp::messages::ocpp21::NotifyReportConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::NotifySettlementReq&,
     *                                          ocpp::messages::ocpp21::NotifySettlementConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::NotifySettlementReq& request,
              ocpp::messages::ocpp21::NotifySettlementConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::NotifyWebPaymentStartedReq&,
     *                                          ocpp::messages::ocpp21::NotifyWebPaymentStartedConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::NotifyWebPaymentStartedReq& request,
              ocpp::messages::ocpp21::NotifyWebPaymentStartedConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::PublishFirmwareStatusNotificationReq&,
     *                                          ocpp::messages::ocpp21::PublishFirmwareStatusNotificationConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::PublishFirmwareStatusNotificationReq& request,
              ocpp::messages::ocpp21::PublishFirmwareStatusNotificationConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::PullDynamicScheduleUpdateReq&,
     *                                          ocpp::messages::ocpp21::PullDynamicScheduleUpdateConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::PullDynamicScheduleUpdateReq& request,
              ocpp::messages::ocpp21::PullDynamicScheduleUpdateConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::ReportChargingProfilesReq&,
     *                                          ocpp::messages::ocpp21::ReportChargingProfilesConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::ReportChargingProfilesReq& request,
              ocpp::messages::ocpp21::ReportChargingProfilesConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::ReportDERControlReq&,
     *                                          ocpp::messages::ocpp21::ReportDERControlConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::ReportDERControlReq& request,
              ocpp::messages::ocpp21::ReportDERControlConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::ReservationStatusUpdateReq&,
     *                                          ocpp::messages::ocpp21::ReservationStatusUpdateConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::ReservationStatusUpdateReq& request,
              ocpp::messages::ocpp21::ReservationStatusUpdateConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::SecurityEventNotificationReq&,
     *                                          ocpp::messages::ocpp21::SecurityEventNotificationConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::SecurityEventNotificationReq& request,
              ocpp::messages::ocpp21::SecurityEventNotificationConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::SignCertificateReq&,
     *                                          ocpp::messages::ocpp21::SignCertificateConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::SignCertificateReq& request,
              ocpp::messages::ocpp21::SignCertificateConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::StatusNotificationReq&,
     *                                          ocpp::messages::ocpp21::StatusNotificationConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::StatusNotificationReq& request,
              ocpp::messages::ocpp21::StatusNotificationConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::TransactionEventReq&,
     *                                          ocpp::messages::ocpp21::TransactionEventConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::TransactionEventReq& request,
              ocpp::messages::ocpp21::TransactionEventConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::call(const ocpp::messages::ocpp21::VatNumberValidationReq&,
     *                                          ocpp::messages::ocpp21::VatNumberValidationConf&,
     *                                          std::string&,
     *                                          std::string&) */
    bool call(const ocpp::messages::ocpp21::VatNumberValidationReq& request,
              ocpp::messages::ocpp21::VatNumberValidationConf&      response,
              std::string&                                       error,
              std::string&                                       message) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::AFRRSignalReq&, ocpp::messages::ocpp21::AFRRSignalConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::AFRRSignalReq&,
                                            ocpp::messages::ocpp21::AFRRSignalConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::AdjustPeriodicEventStreamReq&, ocpp::messages::ocpp21::AdjustPeriodicEventStreamConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::AdjustPeriodicEventStreamReq&,
                                            ocpp::messages::ocpp21::AdjustPeriodicEventStreamConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::CancelReservationReq&, ocpp::messages::ocpp21::CancelReservationConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::CancelReservationReq&,
                                            ocpp::messages::ocpp21::CancelReservationConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::CertificateSignedReq&, ocpp::messages::ocpp21::CertificateSignedConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::CertificateSignedReq&,
                                            ocpp::messages::ocpp21::CertificateSignedConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::ChangeAvailabilityReq&, ocpp::messages::ocpp21::ChangeAvailabilityConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::ChangeAvailabilityReq&,
                                            ocpp::messages::ocpp21::ChangeAvailabilityConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::ChangeTransactionTariffReq&, ocpp::messages::ocpp21::ChangeTransactionTariffConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::ChangeTransactionTariffReq&,
                                            ocpp::messages::ocpp21::ChangeTransactionTariffConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::ClearCacheReq&, ocpp::messages::ocpp21::ClearCacheConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::ClearCacheReq&,
                                            ocpp::messages::ocpp21::ClearCacheConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::ClearChargingProfileReq&, ocpp::messages::ocpp21::ClearChargingProfileConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::ClearChargingProfileReq&,
                                            ocpp::messages::ocpp21::ClearChargingProfileConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::ClearDERControlReq&, ocpp::messages::ocpp21::ClearDERControlConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::ClearDERControlReq&,
                                            ocpp::messages::ocpp21::ClearDERControlConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::ClearDisplayMessageReq&, ocpp::messages::ocpp21::ClearDisplayMessageConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::ClearDisplayMessageReq&,
                                            ocpp::messages::ocpp21::ClearDisplayMessageConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::ClearTariffsReq&, ocpp::messages::ocpp21::ClearTariffsConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::ClearTariffsReq&,
                                            ocpp::messages::ocpp21::ClearTariffsConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::ClearVariableMonitoringReq&, ocpp::messages::ocpp21::ClearVariableMonitoringConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::ClearVariableMonitoringReq&,
                                            ocpp::messages::ocpp21::ClearVariableMonitoringConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::ClosePeriodicEventStreamReq&, ocpp::messages::ocpp21::ClosePeriodicEventStreamConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::ClosePeriodicEventStreamReq&,
                                            ocpp::messages::ocpp21::ClosePeriodicEventStreamConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::CustomerInformationReq&, ocpp::messages::ocpp21::CustomerInformationConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::CustomerInformationReq&,
                                            ocpp::messages::ocpp21::CustomerInformationConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::DataTransferReq&, ocpp::messages::ocpp21::DataTransferConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::DataTransferReq&,
                                            ocpp::messages::ocpp21::DataTransferConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::DeleteCertificateReq&, ocpp::messages::ocpp21::DeleteCertificateConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::DeleteCertificateReq&,
                                            ocpp::messages::ocpp21::DeleteCertificateConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::Get15118EVCertificateReq&, ocpp::messages::ocpp21::Get15118EVCertificateConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::Get15118EVCertificateReq&,
                                            ocpp::messages::ocpp21::Get15118EVCertificateConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::GetBaseReportReq&, ocpp::messages::ocpp21::GetBaseReportConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::GetBaseReportReq&,
                                            ocpp::messages::ocpp21::GetBaseReportConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::GetCertificateChainStatusReq&, ocpp::messages::ocpp21::GetCertificateChainStatusConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::GetCertificateChainStatusReq&,
                                            ocpp::messages::ocpp21::GetCertificateChainStatusConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::GetCertificateStatusReq&, ocpp::messages::ocpp21::GetCertificateStatusConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::GetCertificateStatusReq&,
                                            ocpp::messages::ocpp21::GetCertificateStatusConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::GetChargingProfilesReq&, ocpp::messages::ocpp21::GetChargingProfilesConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::GetChargingProfilesReq&,
                                            ocpp::messages::ocpp21::GetChargingProfilesConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::GetCompositeScheduleReq&, ocpp::messages::ocpp21::GetCompositeScheduleConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::GetCompositeScheduleReq&,
                                            ocpp::messages::ocpp21::GetCompositeScheduleConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::GetDERControlReq&, ocpp::messages::ocpp21::GetDERControlConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::GetDERControlReq&,
                                            ocpp::messages::ocpp21::GetDERControlConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::GetDisplayMessagesReq&, ocpp::messages::ocpp21::GetDisplayMessagesConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::GetDisplayMessagesReq&,
                                            ocpp::messages::ocpp21::GetDisplayMessagesConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::GetInstalledCertificateIdsReq&, ocpp::messages::ocpp21::GetInstalledCertificateIdsConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::GetInstalledCertificateIdsReq&,
                                            ocpp::messages::ocpp21::GetInstalledCertificateIdsConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::GetLocalListVersionReq&, ocpp::messages::ocpp21::GetLocalListVersionConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::GetLocalListVersionReq&,
                                            ocpp::messages::ocpp21::GetLocalListVersionConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::GetLogReq&, ocpp::messages::ocpp21::GetLogConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::GetLogReq&,
                                            ocpp::messages::ocpp21::GetLogConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::GetMonitoringReportReq&, ocpp::messages::ocpp21::GetMonitoringReportConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::GetMonitoringReportReq&,
                                            ocpp::messages::ocpp21::GetMonitoringReportConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::GetPeriodicEventStreamReq&, ocpp::messages::ocpp21::GetPeriodicEventStreamConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::GetPeriodicEventStreamReq&,
                                            ocpp::messages::ocpp21::GetPeriodicEventStreamConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::GetReportReq&, ocpp::messages::ocpp21::GetReportConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::GetReportReq&,
                                            ocpp::messages::ocpp21::GetReportConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::GetTariffsReq&, ocpp::messages::ocpp21::GetTariffsConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::GetTariffsReq&,
                                            ocpp::messages::ocpp21::GetTariffsConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::GetTransactionStatusReq&, ocpp::messages::ocpp21::GetTransactionStatusConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::GetTransactionStatusReq&,
                                            ocpp::messages::ocpp21::GetTransactionStatusConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::GetVariablesReq&, ocpp::messages::ocpp21::GetVariablesConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::GetVariablesReq&,
                                            ocpp::messages::ocpp21::GetVariablesConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::InstallCertificateReq&, ocpp::messages::ocpp21::InstallCertificateConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::InstallCertificateReq&,
                                            ocpp::messages::ocpp21::InstallCertificateConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::OpenPeriodicEventStreamReq&, ocpp::messages::ocpp21::OpenPeriodicEventStreamConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::OpenPeriodicEventStreamReq&,
                                            ocpp::messages::ocpp21::OpenPeriodicEventStreamConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::PublishFirmwareReq&, ocpp::messages::ocpp21::PublishFirmwareConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::PublishFirmwareReq&,
                                            ocpp::messages::ocpp21::PublishFirmwareConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::RequestBatterySwapReq&, ocpp::messages::ocpp21::RequestBatterySwapConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::RequestBatterySwapReq&,
                                            ocpp::messages::ocpp21::RequestBatterySwapConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::RequestStartTransactionReq&, ocpp::messages::ocpp21::RequestStartTransactionConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::RequestStartTransactionReq&,
                                            ocpp::messages::ocpp21::RequestStartTransactionConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::RequestStopTransactionReq&, ocpp::messages::ocpp21::RequestStopTransactionConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::RequestStopTransactionReq&,
                                            ocpp::messages::ocpp21::RequestStopTransactionConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::ReserveNowReq&, ocpp::messages::ocpp21::ReserveNowConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::ReserveNowReq&,
                                            ocpp::messages::ocpp21::ReserveNowConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::ResetReq&, ocpp::messages::ocpp21::ResetConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::ResetReq&,
                                            ocpp::messages::ocpp21::ResetConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::SendLocalListReq&, ocpp::messages::ocpp21::SendLocalListConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::SendLocalListReq&,
                                            ocpp::messages::ocpp21::SendLocalListConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::SetChargingProfileReq&, ocpp::messages::ocpp21::SetChargingProfileConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::SetChargingProfileReq&,
                                            ocpp::messages::ocpp21::SetChargingProfileConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::SetDefaultTariffReq&, ocpp::messages::ocpp21::SetDefaultTariffConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::SetDefaultTariffReq&,
                                            ocpp::messages::ocpp21::SetDefaultTariffConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::SetDERControlReq&, ocpp::messages::ocpp21::SetDERControlConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::SetDERControlReq&,
                                            ocpp::messages::ocpp21::SetDERControlConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::SetDisplayMessageReq&, ocpp::messages::ocpp21::SetDisplayMessageConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::SetDisplayMessageReq&,
                                            ocpp::messages::ocpp21::SetDisplayMessageConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::SetMonitoringBaseReq&, ocpp::messages::ocpp21::SetMonitoringBaseConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::SetMonitoringBaseReq&,
                                            ocpp::messages::ocpp21::SetMonitoringBaseConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::SetMonitoringLevelReq&, ocpp::messages::ocpp21::SetMonitoringLevelConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::SetMonitoringLevelReq&,
                                            ocpp::messages::ocpp21::SetMonitoringLevelConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::SetNetworkProfileReq&, ocpp::messages::ocpp21::SetNetworkProfileConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::SetNetworkProfileReq&,
                                            ocpp::messages::ocpp21::SetNetworkProfileConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::SetVariableMonitoringReq&, ocpp::messages::ocpp21::SetVariableMonitoringConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::SetVariableMonitoringReq&,
                                            ocpp::messages::ocpp21::SetVariableMonitoringConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::SetVariablesReq&, ocpp::messages::ocpp21::SetVariablesConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::SetVariablesReq&,
                                            ocpp::messages::ocpp21::SetVariablesConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::TriggerMessageReq&, ocpp::messages::ocpp21::TriggerMessageConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::TriggerMessageReq&,
                                            ocpp::messages::ocpp21::TriggerMessageConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::UnlockConnectorReq&, ocpp::messages::ocpp21::UnlockConnectorConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::UnlockConnectorReq&,
                                            ocpp::messages::ocpp21::UnlockConnectorConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::UnpublishFirmwareReq&, ocpp::messages::ocpp21::UnpublishFirmwareConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::UnpublishFirmwareReq&,
                                            ocpp::messages::ocpp21::UnpublishFirmwareConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::UpdateDynamicScheduleReq&, ocpp::messages::ocpp21::UpdateDynamicScheduleConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::UpdateDynamicScheduleReq&,
                                            ocpp::messages::ocpp21::UpdateDynamicScheduleConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::UpdateFirmwareReq&, ocpp::messages::ocpp21::UpdateFirmwareConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::UpdateFirmwareReq&,
                                            ocpp::messages::ocpp21::UpdateFirmwareConf&,
                                            std::string&,
                                            std::string&)> handler) override;
    /** @copydoc bool ICentralSystemProxy21::registerHandler(
                      std::function<bool(const ocpp::messages::ocpp21::UsePriorityChargingReq&, ocpp::messages::ocpp21::UsePriorityChargingConf&, std::string&, std::string&)>) */
    bool registerHandler(std::function<bool(const ocpp::messages::ocpp21::UsePriorityChargingReq&,
                                            ocpp::messages::ocpp21::UsePriorityChargingConf&,
                                            std::string&,
                                            std::string&)> handler) override;

    // IRpc::IListener interface

    /** @copydoc void IRpc::IListener::rpcDisconnected() */
    void rpcDisconnected() override;

    /** @copydoc void IRpc::IListener::rpcError() */
    void rpcError() override;

    /** @copydoc bool IRpc::IListener::rpcCallReceived(const std::string&,
                                                       const rapidjson::Value&,
                                                       rapidjson::Document&,
                                                       std::string&,
                                                       std::string&) */
    bool rpcCallReceived(const std::string&      action,
                         const rapidjson::Value& payload,
                         rapidjson::Document&    response,
                         std::string&            error_code,
                         std::string&            error_message) override;

    // IRpc::ISpy interface

    /** @copydoc void IRpc::ISpy::rcpMessageReceived(const std::string& msg) */
    void rcpMessageReceived(const std::string& msg) override;

    /** @copydoc void IRpc::ISpy::rcpMessageSent(const std::string& msg) */
    void rcpMessageSent(const std::string& msg) override;

    // RpcClient::IListener interface

    /** @brief Called when connection is successfull */
    void rpcClientConnected() override;

    /** @brief Called when connection failed */
    void rpcClientFailed() override;

  private:
    /** @brief Charge point's identifier */
    std::string m_identifier;
    /** @brief Stack configuration */
    const ocpp::config::ILocalControllerConfig21& m_stack_config;
    /** @brief Client websocket */
    std::unique_ptr<ocpp::websockets::IWebsocketClient> m_websocket;
    /** @brief RPC connection */
    ocpp::rpc::RpcClient m_rpc;
    /** @brief Messages converter */
    ocpp::messages::ocpp21::MessagesConverter21& m_messages_converter;
    /** @brief Message dispatcher */
    ocpp::messages::MessageDispatcher m_msg_dispatcher;
    /** @brief Message sender */
    ocpp::messages::GenericMessageSender m_msg_sender;
    /** @brief Request handler */
    CentralSystemHandler21 m_handler;
    /** @brief Proxy to forward requests to the charge point */
    std::weak_ptr<IChargePointProxy21> m_charge_point;
    /** @brief Listener to the proxy events */
    ILocalControllerProxyEventsHandler21* m_listener;
    /** @brief User message handlers */
    std::vector<std::shared_ptr<ocpp::messages::IMessageDispatcher::IMessageHandler>> m_user_handlers;

    /**
     * @brief Execute a call request
     * @param action RPC action for the request
     * @param request Request payload
     * @param response Response payload
     * @param error Error (Empty if not a CallError)
     * @param message Error message (Empty if not a CallError)
     * @return true if the request has been sent and a response has been received, false otherwise
     */
    template <typename RequestType, typename ResponseType>
    bool call(const std::string& action, const RequestType& request, ResponseType& response, std::string& error, std::string& message)
    {
        bool ret = true;

        LOG_DEBUG << "[" << m_identifier << "] - " << action;

        ocpp::messages::CallResult res = m_msg_sender.call(action, request, response, error, message);
        if (res != ocpp::messages::CallResult::Ok)
        {
            LOG_ERROR << "[" << m_identifier << "] - " << action << " => "
                      << (res == ocpp::messages::CallResult::Failed ? "Timeout" : "Error");
            ret = false;
        }

        return ret;
    }

    /**
     * @brief Register a user handler for an incoming request
     * @param action RPC action for the request
     * @param handler Handler function
     * @return true if the handler has been registered, false otherwise
     */
    template <typename RequestType, typename ResponseType>
    bool registerHandler(const std::string&                                                                 action,
                         std::function<bool(const RequestType&, ResponseType&, std::string&, std::string&)> handler)
    {
        ocpp::messages::UserMessageHandler<RequestType, ResponseType>* msg_handler =
            new ocpp::messages::UserMessageHandler<RequestType, ResponseType>(action, m_messages_converter, handler);
        m_user_handlers.push_back(std::shared_ptr<ocpp::messages::IMessageDispatcher::IMessageHandler>(msg_handler));
        return m_msg_dispatcher.registerHandler(action, *msg_handler, true);
    }
};

} // namespace ocpp21
} // namespace localcontroller
} // namespace ocpp

#endif // OPENOCPP_OCPP21_CENTRALSYSTEMPROXY21_H