/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:NotifyChargingLimitRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#include "AbsolutePriceScheduleType21.h"

#include "IRpc.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief Convert a AbsolutePriceScheduleType from a JSON representation */
bool AbsolutePriceScheduleTypeConverter::fromJson(const rapidjson::Value&       json,
                                      AbsolutePriceScheduleType&                data,
                                      std::string&                  error_code,
                                      [[maybe_unused]] std::string& error_message)
{
    bool ret = true;

    // timeAnchor
    ret = ret && extract(json, "timeAnchor", data.timeAnchor, error_message);

    // priceScheduleID
    extract(json, "priceScheduleID", data.priceScheduleID);

    // priceScheduleDescription
    extract(json, "priceScheduleDescription", data.priceScheduleDescription);

    // currency
    extract(json, "currency", data.currency);

    // language
    extract(json, "language", data.language);

    // priceAlgorithm
    extract(json, "priceAlgorithm", data.priceAlgorithm);

    // minimumCost
    if (json.HasMember("minimumCost"))
    {
    RationalNumberTypeConverter minimumCost_converter;
    ret = ret && minimumCost_converter.fromJson(json["minimumCost"], data.minimumCost, error_code, error_message);
    }

    // maximumCost
    if (json.HasMember("maximumCost"))
    {
    RationalNumberTypeConverter maximumCost_converter;
    ret = ret && maximumCost_converter.fromJson(json["maximumCost"], data.maximumCost, error_code, error_message);
    }

    // priceRuleStacks
    if (json.HasMember("priceRuleStacks"))
    {
        const rapidjson::Value& priceRuleStacks_json = json["priceRuleStacks"];
        PriceRuleStackTypeConverter priceRuleStacks_converter;
        for (auto it = priceRuleStacks_json.Begin(); ret && (it != priceRuleStacks_json.End()); ++it)
        {
            PriceRuleStackType& item = data.priceRuleStacks.emplace_back();
            ret = ret && priceRuleStacks_converter.fromJson(*it, item, error_code, error_message);
        }
    }

    // taxRules
    if (json.HasMember("taxRules"))
    {
        const rapidjson::Value& taxRules_json = json["taxRules"];
        TaxRuleTypeConverter taxRules_converter;
        for (auto it = taxRules_json.Begin(); ret && (it != taxRules_json.End()); ++it)
        {
            TaxRuleType& item = data.taxRules.emplace_back();
            ret = ret && taxRules_converter.fromJson(*it, item, error_code, error_message);
        }
    }

    // overstayRuleList
    if (json.HasMember("overstayRuleList"))
    {
    OverstayRuleListTypeConverter overstayRuleList_converter;
    ret = ret && overstayRuleList_converter.fromJson(json["overstayRuleList"], data.overstayRuleList, error_code, error_message);
    }

    // additionalSelectedServices
    if (json.HasMember("additionalSelectedServices"))
    {
        const rapidjson::Value& additionalSelectedServices_json = json["additionalSelectedServices"];
        AdditionalSelectedServicesTypeConverter additionalSelectedServices_converter;
        for (auto it = additionalSelectedServices_json.Begin(); ret && (it != additionalSelectedServices_json.End()); ++it)
        {
            AdditionalSelectedServicesType& item = data.additionalSelectedServices.emplace_back();
            ret = ret && additionalSelectedServices_converter.fromJson(*it, item, error_code, error_message);
        }
    }

    // customData
    if (json.HasMember("customData"))
    {
    CustomDataTypeConverter customData_converter;
    ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a AbsolutePriceScheduleType to a JSON representation */
bool AbsolutePriceScheduleTypeConverter::toJson(const AbsolutePriceScheduleType& data, rapidjson::Document& json) 
{
    bool ret = true;

    // timeAnchor
    fill(json, "timeAnchor", data.timeAnchor);

    // priceScheduleID
    fill(json, "priceScheduleID", data.priceScheduleID);

    // priceScheduleDescription
    fill(json, "priceScheduleDescription", data.priceScheduleDescription);

    // currency
    fill(json, "currency", data.currency);

    // language
    fill(json, "language", data.language);

    // priceAlgorithm
    fill(json, "priceAlgorithm", data.priceAlgorithm);

    // minimumCost
    if (data.minimumCost.isSet())
    {
    RationalNumberTypeConverter minimumCost_converter;
    minimumCost_converter.setAllocator(allocator);
    rapidjson::Document minimumCost_doc(rapidjson::kObjectType);
    ret = ret && minimumCost_converter.toJson(data.minimumCost, minimumCost_doc);
    json.AddMember(rapidjson::StringRef("minimumCost"), minimumCost_doc.Move(), *allocator);
    }

    // maximumCost
    if (data.maximumCost.isSet())
    {
    RationalNumberTypeConverter maximumCost_converter;
    maximumCost_converter.setAllocator(allocator);
    rapidjson::Document maximumCost_doc(rapidjson::kObjectType);
    ret = ret && maximumCost_converter.toJson(data.maximumCost, maximumCost_doc);
    json.AddMember(rapidjson::StringRef("maximumCost"), maximumCost_doc.Move(), *allocator);
    }

    // priceRuleStacks

        rapidjson::Value priceRuleStacks_json(rapidjson::kArrayType);
        PriceRuleStackTypeConverter priceRuleStacks_converter;
        priceRuleStacks_converter.setAllocator(allocator);
        for (const PriceRuleStackType& item : data.priceRuleStacks)
        {
            rapidjson::Document item_doc(rapidjson::kObjectType);
            ret = ret && priceRuleStacks_converter.toJson(item, item_doc);
            priceRuleStacks_json.PushBack(item_doc.Move(), *allocator);
        }
        json.AddMember(rapidjson::StringRef("priceRuleStacks"), priceRuleStacks_json.Move(), *allocator);

    // taxRules
    if (!data.taxRules.empty())
    {

        rapidjson::Value taxRules_json(rapidjson::kArrayType);
        TaxRuleTypeConverter taxRules_converter;
        taxRules_converter.setAllocator(allocator);
        for (const TaxRuleType& item : data.taxRules)
        {
            rapidjson::Document item_doc(rapidjson::kObjectType);
            ret = ret && taxRules_converter.toJson(item, item_doc);
            taxRules_json.PushBack(item_doc.Move(), *allocator);
        }
        json.AddMember(rapidjson::StringRef("taxRules"), taxRules_json.Move(), *allocator);
    }

    // overstayRuleList
    if (data.overstayRuleList.isSet())
    {
    OverstayRuleListTypeConverter overstayRuleList_converter;
    overstayRuleList_converter.setAllocator(allocator);
    rapidjson::Document overstayRuleList_doc(rapidjson::kObjectType);
    ret = ret && overstayRuleList_converter.toJson(data.overstayRuleList, overstayRuleList_doc);
    json.AddMember(rapidjson::StringRef("overstayRuleList"), overstayRuleList_doc.Move(), *allocator);
    }

    // additionalSelectedServices
    if (!data.additionalSelectedServices.empty())
    {

        rapidjson::Value additionalSelectedServices_json(rapidjson::kArrayType);
        AdditionalSelectedServicesTypeConverter additionalSelectedServices_converter;
        additionalSelectedServices_converter.setAllocator(allocator);
        for (const AdditionalSelectedServicesType& item : data.additionalSelectedServices)
        {
            rapidjson::Document item_doc(rapidjson::kObjectType);
            ret = ret && additionalSelectedServices_converter.toJson(item, item_doc);
            additionalSelectedServices_json.PushBack(item_doc.Move(), *allocator);
        }
        json.AddMember(rapidjson::StringRef("additionalSelectedServices"), additionalSelectedServices_json.Move(), *allocator);
    }

    // customData
    if (data.customData.isSet())
    {
    CustomDataTypeConverter customData_converter;
    customData_converter.setAllocator(allocator);
    rapidjson::Document customData_doc(rapidjson::kObjectType);
    ret = ret && customData_converter.toJson(data.customData, customData_doc);
    json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    return ret;
}

} // namespace ocpp21
} // namespace types
} // namespace ocpp