/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:GetCertificateChainStatusRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_CERTIFICATESTATUSTYPE_H
#define OPENOCPP_OCPP21_CERTIFICATESTATUSTYPE_H


#include "CertificateHashDataType21.h"
#include "CertificateStatusSourceEnumType21.h"
#include "CertificateStatusEnumType21.h"
#include "CustomDataType21.h"

#include "DateTime.h"
#include "Optional.h"
#include "IMessageConverter.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief Revocation status of certificate
 */
struct CertificateStatusType
{
    /** @brief  */
    CertificateHashDataType certificateHashData;
    /** @brief  */
    CertificateStatusSourceEnumType source;
    /** @brief  */
    CertificateStatusEnumType status;
    /** @brief  */
    ocpp::types::DateTime nextUpdate;
    /** @brief  */
    ocpp::types::Optional<CustomDataType> customData;
};

/** @brief Converter class for CertificateStatusType type */
class CertificateStatusTypeConverter : public ocpp::messages::IMessageConverter<CertificateStatusType>
{
  public:
    /** @brief Clone the converter */
    ocpp::messages::IMessageConverter<CertificateStatusType>* clone() const override { return new CertificateStatusTypeConverter(); }

    /** @brief Convert a CertificateStatusType from a JSON representation */
    bool fromJson(const rapidjson::Value&       json,
                  CertificateStatusType&                data,
                  std::string&                  error_code,
                  [[maybe_unused]] std::string& error_message) override;

    /** @brief Convert a CertificateStatusType to a JSON representation */
    bool toJson(const CertificateStatusType& data, rapidjson::Document& json) override;
};

} // namespace ocpp21
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_OCPP21_CERTIFICATESTATUSTYPE_H