/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:ReportChargingProfilesRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_CHARGINGPROFILETYPE_H
#define OPENOCPP_OCPP21_CHARGINGPROFILETYPE_H


#include "ChargingProfilePurposeEnumType21.h"
#include "ChargingProfileKindEnumType21.h"
#include "RecurrencyKindEnumType21.h"
#include "ChargingScheduleType21.h"
#include "CustomDataType21.h"

#include "Optional.h"
#include "DateTime.h"
#include "CiStringType.h"
#include <vector>
#include "IMessageConverter.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief A ChargingProfile consists of 1 to 3 ChargingSchedules with a list of ChargingSchedulePeriods, describing the amount of power or current that can be delivered per time interval.

image::images/ChargingProfile-Simple.png[]

 */
struct ChargingProfileType
{
    /** @brief Id of ChargingProfile. Unique within charging station. Id can have a negative value. This is useful to distinguish charging profiles from an external actor (external constraints) from charging profiles received from CSMS. */
    int id;
    /** @brief Value determining level in hierarchy stack of profiles. Higher values have precedence over lower values. Lowest level is 0. */
    int stackLevel;
    /** @brief  */
    ChargingProfilePurposeEnumType chargingProfilePurpose;
    /** @brief  */
    ChargingProfileKindEnumType chargingProfileKind;
    /** @brief  */
    ocpp::types::Optional<RecurrencyKindEnumType> recurrencyKind;
    /** @brief Point in time at which the profile starts to be valid. If absent, the profile is valid as soon as it is received by the Charging Station. */
    ocpp::types::Optional<ocpp::types::DateTime> validFrom;
    /** @brief Point in time at which the profile stops to be valid. If absent, the profile is valid until it is replaced by another profile. */
    ocpp::types::Optional<ocpp::types::DateTime> validTo;
    /** @brief SHALL only be included if ChargingProfilePurpose is set to TxProfile in a SetChargingProfileRequest. The transactionId is used to match the profile to a specific transaction. */
    ocpp::types::Optional<ocpp::types::CiStringType<36u>> transactionId;
    /** @brief *(2.1)* Period in seconds that this charging profile remains valid after the Charging Station has gone offline. After this period the charging profile becomes invalid for as long as it is offline and the Charging Station reverts back to a valid profile with a lower stack level. 
If _invalidAfterOfflineDuration_ is true, then this charging profile will become permanently invalid.
A value of 0 means that the charging profile is immediately invalid while offline. When the field is absent, then  no timeout applies and the charging profile remains valid when offline. */
    ocpp::types::Optional<int> maxOfflineDuration;
    /** @brief  */
    std::vector<ChargingScheduleType> chargingSchedule;
    /** @brief *(2.1)* When set to true this charging profile will not be valid anymore after being offline for more than _maxOfflineDuration_. +
    When absent defaults to false. */
    ocpp::types::Optional<bool> invalidAfterOfflineDuration;
    /** @brief *(2.1)*  Interval in seconds after receipt of last update, when to request a profile update by sending a PullDynamicScheduleUpdateRequest message.
    A value of 0 or no value means that no update interval applies. +
    Only relevant in a dynamic charging profile. */
    ocpp::types::Optional<int> dynUpdateInterval;
    /** @brief *(2.1)* Time at which limits or setpoints in this charging profile were last updated by a PullDynamicScheduleUpdateRequest or UpdateDynamicScheduleRequest or by an external actor. +
    Only relevant in a dynamic charging profile. */
    ocpp::types::Optional<ocpp::types::DateTime> dynUpdateTime;
    /** @brief *(2.1)* ISO 15118-20 signature for all price schedules in _chargingSchedules_. +
Note: for 256-bit elliptic curves (like secp256k1) the ECDSA signature is 512 bits (64 bytes) and for 521-bit curves (like secp521r1) the signature is 1042 bits. This equals 131 bytes, which can be encoded as base64 in 176 bytes. */
    ocpp::types::Optional<ocpp::types::CiStringType<256u>> priceScheduleSignature;
    /** @brief  */
    ocpp::types::Optional<CustomDataType> customData;
};

/** @brief Converter class for ChargingProfileType type */
class ChargingProfileTypeConverter : public ocpp::messages::IMessageConverter<ChargingProfileType>
{
  public:
    /** @brief Clone the converter */
    ocpp::messages::IMessageConverter<ChargingProfileType>* clone() const override { return new ChargingProfileTypeConverter(); }

    /** @brief Convert a ChargingProfileType from a JSON representation */
    bool fromJson(const rapidjson::Value&       json,
                  ChargingProfileType&                data,
                  std::string&                  error_code,
                  [[maybe_unused]] std::string& error_message) override;

    /** @brief Convert a ChargingProfileType to a JSON representation */
    bool toJson(const ChargingProfileType& data, rapidjson::Document& json) override;
};

} // namespace ocpp21
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_OCPP21_CHARGINGPROFILETYPE_H