/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:TransactionEventRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#include "ChargingPeriodType21.h"

#include "IRpc.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief Convert a ChargingPeriodType from a JSON representation */
bool ChargingPeriodTypeConverter::fromJson(const rapidjson::Value&       json,
                                      ChargingPeriodType&                data,
                                      std::string&                  error_code,
                                      [[maybe_unused]] std::string& error_message)
{
    bool ret = true;

    // dimensions
    if (json.HasMember("dimensions"))
    {
        const rapidjson::Value& dimensions_json = json["dimensions"];
        CostDimensionTypeConverter dimensions_converter;
        for (auto it = dimensions_json.Begin(); ret && (it != dimensions_json.End()); ++it)
        {
            CostDimensionType& item = data.dimensions.emplace_back();
            ret = ret && dimensions_converter.fromJson(*it, item, error_code, error_message);
        }
    }

    // tariffId
    extract(json, "tariffId", data.tariffId);

    // startPeriod
    ret = ret && extract(json, "startPeriod", data.startPeriod, error_message);

    // customData
    if (json.HasMember("customData"))
    {
    CustomDataTypeConverter customData_converter;
    ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a ChargingPeriodType to a JSON representation */
bool ChargingPeriodTypeConverter::toJson(const ChargingPeriodType& data, rapidjson::Document& json) 
{
    bool ret = true;

    // dimensions
    if (!data.dimensions.empty())
    {

        rapidjson::Value dimensions_json(rapidjson::kArrayType);
        CostDimensionTypeConverter dimensions_converter;
        dimensions_converter.setAllocator(allocator);
        for (const CostDimensionType& item : data.dimensions)
        {
            rapidjson::Document item_doc(rapidjson::kObjectType);
            ret = ret && dimensions_converter.toJson(item, item_doc);
            dimensions_json.PushBack(item_doc.Move(), *allocator);
        }
        json.AddMember(rapidjson::StringRef("dimensions"), dimensions_json.Move(), *allocator);
    }

    // tariffId
    fill(json, "tariffId", data.tariffId);

    // startPeriod
    fill(json, "startPeriod", data.startPeriod);

    // customData
    if (data.customData.isSet())
    {
    CustomDataTypeConverter customData_converter;
    customData_converter.setAllocator(allocator);
    rapidjson::Document customData_doc(rapidjson::kObjectType);
    ret = ret && customData_converter.toJson(data.customData, customData_doc);
    json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    return ret;
}

} // namespace ocpp21
} // namespace types
} // namespace ocpp