/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:NotifyEVChargingNeedsRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#include "ChargingNeedsType21.h"

#include "IRpc.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief Convert a ChargingNeedsType from a JSON representation */
bool ChargingNeedsTypeConverter::fromJson(const rapidjson::Value&       json,
                                      ChargingNeedsType&                data,
                                      std::string&                  error_code,
                                      [[maybe_unused]] std::string& error_message)
{
    bool ret = true;

    // acChargingParameters
    if (json.HasMember("acChargingParameters"))
    {
    ACChargingParametersTypeConverter acChargingParameters_converter;
    ret = ret && acChargingParameters_converter.fromJson(json["acChargingParameters"], data.acChargingParameters, error_code, error_message);
    }

    // derChargingParameters
    if (json.HasMember("derChargingParameters"))
    {
    DERChargingParametersTypeConverter derChargingParameters_converter;
    ret = ret && derChargingParameters_converter.fromJson(json["derChargingParameters"], data.derChargingParameters, error_code, error_message);
    }

    // evEnergyOffer
    if (json.HasMember("evEnergyOffer"))
    {
    EVEnergyOfferTypeConverter evEnergyOffer_converter;
    ret = ret && evEnergyOffer_converter.fromJson(json["evEnergyOffer"], data.evEnergyOffer, error_code, error_message);
    }

    // requestedEnergyTransfer
    data.requestedEnergyTransfer = EnergyTransferModeEnumTypeHelper.fromString(json["requestedEnergyTransfer"].GetString());

    // dcChargingParameters
    if (json.HasMember("dcChargingParameters"))
    {
    DCChargingParametersTypeConverter dcChargingParameters_converter;
    ret = ret && dcChargingParameters_converter.fromJson(json["dcChargingParameters"], data.dcChargingParameters, error_code, error_message);
    }

    // v2xChargingParameters
    if (json.HasMember("v2xChargingParameters"))
    {
    V2XChargingParametersTypeConverter v2xChargingParameters_converter;
    ret = ret && v2xChargingParameters_converter.fromJson(json["v2xChargingParameters"], data.v2xChargingParameters, error_code, error_message);
    }

    // availableEnergyTransfer
    if (json.HasMember("availableEnergyTransfer"))
    {
        const rapidjson::Value& availableEnergyTransfer_json = json["availableEnergyTransfer"];
        for (auto it = availableEnergyTransfer_json.Begin(); ret && (it != availableEnergyTransfer_json.End()); ++it)
        {
            EnergyTransferModeEnumType& item = data.availableEnergyTransfer.emplace_back();
            item = EnergyTransferModeEnumTypeHelper.fromString(it->GetString());
        }
    }

    // controlMode
    if (json.HasMember("controlMode"))
    {
    data.controlMode = ControlModeEnumTypeHelper.fromString(json["controlMode"].GetString());
    }

    // mobilityNeedsMode
    if (json.HasMember("mobilityNeedsMode"))
    {
    data.mobilityNeedsMode = MobilityNeedsModeEnumTypeHelper.fromString(json["mobilityNeedsMode"].GetString());
    }

    // departureTime
    ret = ret && extract(json, "departureTime", data.departureTime, error_message);

    // customData
    if (json.HasMember("customData"))
    {
    CustomDataTypeConverter customData_converter;
    ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a ChargingNeedsType to a JSON representation */
bool ChargingNeedsTypeConverter::toJson(const ChargingNeedsType& data, rapidjson::Document& json) 
{
    bool ret = true;

    // acChargingParameters
    if (data.acChargingParameters.isSet())
    {
    ACChargingParametersTypeConverter acChargingParameters_converter;
    acChargingParameters_converter.setAllocator(allocator);
    rapidjson::Document acChargingParameters_doc(rapidjson::kObjectType);
    ret = ret && acChargingParameters_converter.toJson(data.acChargingParameters, acChargingParameters_doc);
    json.AddMember(rapidjson::StringRef("acChargingParameters"), acChargingParameters_doc.Move(), *allocator);
    }

    // derChargingParameters
    if (data.derChargingParameters.isSet())
    {
    DERChargingParametersTypeConverter derChargingParameters_converter;
    derChargingParameters_converter.setAllocator(allocator);
    rapidjson::Document derChargingParameters_doc(rapidjson::kObjectType);
    ret = ret && derChargingParameters_converter.toJson(data.derChargingParameters, derChargingParameters_doc);
    json.AddMember(rapidjson::StringRef("derChargingParameters"), derChargingParameters_doc.Move(), *allocator);
    }

    // evEnergyOffer
    if (data.evEnergyOffer.isSet())
    {
    EVEnergyOfferTypeConverter evEnergyOffer_converter;
    evEnergyOffer_converter.setAllocator(allocator);
    rapidjson::Document evEnergyOffer_doc(rapidjson::kObjectType);
    ret = ret && evEnergyOffer_converter.toJson(data.evEnergyOffer, evEnergyOffer_doc);
    json.AddMember(rapidjson::StringRef("evEnergyOffer"), evEnergyOffer_doc.Move(), *allocator);
    }

    // requestedEnergyTransfer
    fill(json, "requestedEnergyTransfer", EnergyTransferModeEnumTypeHelper.toString(data.requestedEnergyTransfer));

    // dcChargingParameters
    if (data.dcChargingParameters.isSet())
    {
    DCChargingParametersTypeConverter dcChargingParameters_converter;
    dcChargingParameters_converter.setAllocator(allocator);
    rapidjson::Document dcChargingParameters_doc(rapidjson::kObjectType);
    ret = ret && dcChargingParameters_converter.toJson(data.dcChargingParameters, dcChargingParameters_doc);
    json.AddMember(rapidjson::StringRef("dcChargingParameters"), dcChargingParameters_doc.Move(), *allocator);
    }

    // v2xChargingParameters
    if (data.v2xChargingParameters.isSet())
    {
    V2XChargingParametersTypeConverter v2xChargingParameters_converter;
    v2xChargingParameters_converter.setAllocator(allocator);
    rapidjson::Document v2xChargingParameters_doc(rapidjson::kObjectType);
    ret = ret && v2xChargingParameters_converter.toJson(data.v2xChargingParameters, v2xChargingParameters_doc);
    json.AddMember(rapidjson::StringRef("v2xChargingParameters"), v2xChargingParameters_doc.Move(), *allocator);
    }

    // availableEnergyTransfer
    if (!data.availableEnergyTransfer.empty())
    {

        rapidjson::Value availableEnergyTransfer_json(rapidjson::kArrayType);
        for (const EnergyTransferModeEnumType& item : data.availableEnergyTransfer)
        {
            availableEnergyTransfer_json.PushBack(rapidjson::Value(EnergyTransferModeEnumTypeHelper.toString(item).c_str(), *allocator).Move(), *allocator);
        }
        json.AddMember(rapidjson::StringRef("availableEnergyTransfer"), availableEnergyTransfer_json.Move(), *allocator);
    }

    // controlMode
    if (data.controlMode.isSet())
    {
    fill(json, "controlMode", ControlModeEnumTypeHelper.toString(data.controlMode));
    }

    // mobilityNeedsMode
    if (data.mobilityNeedsMode.isSet())
    {
    fill(json, "mobilityNeedsMode", MobilityNeedsModeEnumTypeHelper.toString(data.mobilityNeedsMode));
    }

    // departureTime
    fill(json, "departureTime", data.departureTime);

    // customData
    if (data.customData.isSet())
    {
    CustomDataTypeConverter customData_converter;
    customData_converter.setAllocator(allocator);
    rapidjson::Document customData_doc(rapidjson::kObjectType);
    ret = ret && customData_converter.toJson(data.customData, customData_doc);
    json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    return ret;
}

} // namespace ocpp21
} // namespace types
} // namespace ocpp