/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:BootNotificationRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_CHARGINGSTATIONTYPE_H
#define OPENOCPP_OCPP21_CHARGINGSTATIONTYPE_H


#include "ModemType21.h"
#include "CustomDataType21.h"

#include "CiStringType.h"
#include "Optional.h"
#include "IMessageConverter.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief The physical system where an Electrical Vehicle (EV) can be charged.
 */
struct ChargingStationType
{
    /** @brief Vendor-specific device identifier. */
    ocpp::types::Optional<ocpp::types::CiStringType<25u>> serialNumber;
    /** @brief Defines the model of the device. */
    ocpp::types::CiStringType<20u> model;
    /** @brief  */
    ocpp::types::Optional<ModemType> modem;
    /** @brief Identifies the vendor (not necessarily in a unique manner). */
    ocpp::types::CiStringType<50u> vendorName;
    /** @brief This contains the firmware version of the Charging Station. */
    ocpp::types::Optional<ocpp::types::CiStringType<50u>> firmwareVersion;
    /** @brief  */
    ocpp::types::Optional<CustomDataType> customData;
};

/** @brief Converter class for ChargingStationType type */
class ChargingStationTypeConverter : public ocpp::messages::IMessageConverter<ChargingStationType>
{
  public:
    /** @brief Clone the converter */
    ocpp::messages::IMessageConverter<ChargingStationType>* clone() const override { return new ChargingStationTypeConverter(); }

    /** @brief Convert a ChargingStationType from a JSON representation */
    bool fromJson(const rapidjson::Value&       json,
                  ChargingStationType&                data,
                  std::string&                  error_code,
                  [[maybe_unused]] std::string& error_message) override;

    /** @brief Convert a ChargingStationType to a JSON representation */
    bool toJson(const ChargingStationType& data, rapidjson::Document& json) override;
};

} // namespace ocpp21
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_OCPP21_CHARGINGSTATIONTYPE_H