/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:ClearTariffsRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_CLEARTARIFFSRESULTTYPE_H
#define OPENOCPP_OCPP21_CLEARTARIFFSRESULTTYPE_H


#include "StatusInfoType21.h"
#include "TariffClearStatusEnumType21.h"
#include "CustomDataType21.h"

#include "Optional.h"
#include "CiStringType.h"
#include "IMessageConverter.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief  */
struct ClearTariffsResultType
{
    /** @brief  */
    ocpp::types::Optional<StatusInfoType> statusInfo;
    /** @brief Id of tariff for which _status_ is reported. If no tariffs were found, then this field is absent, and _status_ will be `NoTariff`. */
    ocpp::types::Optional<ocpp::types::CiStringType<60u>> tariffId;
    /** @brief  */
    TariffClearStatusEnumType status;
    /** @brief  */
    ocpp::types::Optional<CustomDataType> customData;
};

/** @brief Converter class for ClearTariffsResultType type */
class ClearTariffsResultTypeConverter : public ocpp::messages::IMessageConverter<ClearTariffsResultType>
{
  public:
    /** @brief Clone the converter */
    ocpp::messages::IMessageConverter<ClearTariffsResultType>* clone() const override { return new ClearTariffsResultTypeConverter(); }

    /** @brief Convert a ClearTariffsResultType from a JSON representation */
    bool fromJson(const rapidjson::Value&       json,
                  ClearTariffsResultType&                data,
                  std::string&                  error_code,
                  [[maybe_unused]] std::string& error_message) override;

    /** @brief Convert a ClearTariffsResultType to a JSON representation */
    bool toJson(const ClearTariffsResultType& data, rapidjson::Document& json) override;
};

} // namespace ocpp21
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_OCPP21_CLEARTARIFFSRESULTTYPE_H