/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:GetPeriodicEventStreamRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#include "ConstantStreamDataType21.h"

#include "IRpc.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief Convert a ConstantStreamDataType from a JSON representation */
bool ConstantStreamDataTypeConverter::fromJson(const rapidjson::Value&       json,
                                      ConstantStreamDataType&                data,
                                      std::string&                  error_code,
                                      [[maybe_unused]] std::string& error_message)
{
    bool ret = true;

    // id
    extract(json, "id", data.id);

    // params
    PeriodicEventStreamParamsTypeConverter params_converter;
    ret = ret && params_converter.fromJson(json["params"], data.params, error_code, error_message);

    // variableMonitoringId
    extract(json, "variableMonitoringId", data.variableMonitoringId);

    // customData
    if (json.HasMember("customData"))
    {
    CustomDataTypeConverter customData_converter;
    ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a ConstantStreamDataType to a JSON representation */
bool ConstantStreamDataTypeConverter::toJson(const ConstantStreamDataType& data, rapidjson::Document& json) 
{
    bool ret = true;

    // id
    fill(json, "id", data.id);

    // params
    PeriodicEventStreamParamsTypeConverter params_converter;
    params_converter.setAllocator(allocator);
    rapidjson::Document params_doc(rapidjson::kObjectType);
    ret = ret && params_converter.toJson(data.params, params_doc);
    json.AddMember(rapidjson::StringRef("params"), params_doc.Move(), *allocator);

    // variableMonitoringId
    fill(json, "variableMonitoringId", data.variableMonitoringId);

    // customData
    if (data.customData.isSet())
    {
    CustomDataTypeConverter customData_converter;
    customData_converter.setAllocator(allocator);
    rapidjson::Document customData_doc(rapidjson::kObjectType);
    ret = ret && customData_converter.toJson(data.customData, customData_doc);
    json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    return ret;
}

} // namespace ocpp21
} // namespace types
} // namespace ocpp