/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:NotifyEVChargingNeedsRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#include "DERChargingParametersType21.h"

#include "IRpc.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief Convert a DERChargingParametersType from a JSON representation */
bool DERChargingParametersTypeConverter::fromJson(const rapidjson::Value&       json,
                                      DERChargingParametersType&                data,
                                      std::string&                  error_code,
                                      [[maybe_unused]] std::string& error_message)
{
    bool ret = true;

    // evSupportedDERControl
    if (json.HasMember("evSupportedDERControl"))
    {
        const rapidjson::Value& evSupportedDERControl_json = json["evSupportedDERControl"];
        for (auto it = evSupportedDERControl_json.Begin(); ret && (it != evSupportedDERControl_json.End()); ++it)
        {
            DERControlEnumType& item = data.evSupportedDERControl.emplace_back();
            item = DERControlEnumTypeHelper.fromString(it->GetString());
        }
    }

    // evOverExcitedMaxDischargePower
    extract(json, "evOverExcitedMaxDischargePower", data.evOverExcitedMaxDischargePower);

    // evOverExcitedPowerFactor
    extract(json, "evOverExcitedPowerFactor", data.evOverExcitedPowerFactor);

    // evUnderExcitedMaxDischargePower
    extract(json, "evUnderExcitedMaxDischargePower", data.evUnderExcitedMaxDischargePower);

    // evUnderExcitedPowerFactor
    extract(json, "evUnderExcitedPowerFactor", data.evUnderExcitedPowerFactor);

    // maxApparentPower
    extract(json, "maxApparentPower", data.maxApparentPower);

    // maxChargeApparentPower
    extract(json, "maxChargeApparentPower", data.maxChargeApparentPower);

    // maxChargeApparentPower_L2
    extract(json, "maxChargeApparentPower_L2", data.maxChargeApparentPower_L2);

    // maxChargeApparentPower_L3
    extract(json, "maxChargeApparentPower_L3", data.maxChargeApparentPower_L3);

    // maxDischargeApparentPower
    extract(json, "maxDischargeApparentPower", data.maxDischargeApparentPower);

    // maxDischargeApparentPower_L2
    extract(json, "maxDischargeApparentPower_L2", data.maxDischargeApparentPower_L2);

    // maxDischargeApparentPower_L3
    extract(json, "maxDischargeApparentPower_L3", data.maxDischargeApparentPower_L3);

    // maxChargeReactivePower
    extract(json, "maxChargeReactivePower", data.maxChargeReactivePower);

    // maxChargeReactivePower_L2
    extract(json, "maxChargeReactivePower_L2", data.maxChargeReactivePower_L2);

    // maxChargeReactivePower_L3
    extract(json, "maxChargeReactivePower_L3", data.maxChargeReactivePower_L3);

    // minChargeReactivePower
    extract(json, "minChargeReactivePower", data.minChargeReactivePower);

    // minChargeReactivePower_L2
    extract(json, "minChargeReactivePower_L2", data.minChargeReactivePower_L2);

    // minChargeReactivePower_L3
    extract(json, "minChargeReactivePower_L3", data.minChargeReactivePower_L3);

    // maxDischargeReactivePower
    extract(json, "maxDischargeReactivePower", data.maxDischargeReactivePower);

    // maxDischargeReactivePower_L2
    extract(json, "maxDischargeReactivePower_L2", data.maxDischargeReactivePower_L2);

    // maxDischargeReactivePower_L3
    extract(json, "maxDischargeReactivePower_L3", data.maxDischargeReactivePower_L3);

    // minDischargeReactivePower
    extract(json, "minDischargeReactivePower", data.minDischargeReactivePower);

    // minDischargeReactivePower_L2
    extract(json, "minDischargeReactivePower_L2", data.minDischargeReactivePower_L2);

    // minDischargeReactivePower_L3
    extract(json, "minDischargeReactivePower_L3", data.minDischargeReactivePower_L3);

    // nominalVoltage
    extract(json, "nominalVoltage", data.nominalVoltage);

    // nominalVoltageOffset
    extract(json, "nominalVoltageOffset", data.nominalVoltageOffset);

    // maxNominalVoltage
    extract(json, "maxNominalVoltage", data.maxNominalVoltage);

    // minNominalVoltage
    extract(json, "minNominalVoltage", data.minNominalVoltage);

    // evInverterManufacturer
    extract(json, "evInverterManufacturer", data.evInverterManufacturer);

    // evInverterModel
    extract(json, "evInverterModel", data.evInverterModel);

    // evInverterSerialNumber
    extract(json, "evInverterSerialNumber", data.evInverterSerialNumber);

    // evInverterSwVersion
    extract(json, "evInverterSwVersion", data.evInverterSwVersion);

    // evInverterHwVersion
    extract(json, "evInverterHwVersion", data.evInverterHwVersion);

    // evIslandingDetectionMethod
    if (json.HasMember("evIslandingDetectionMethod"))
    {
        const rapidjson::Value& evIslandingDetectionMethod_json = json["evIslandingDetectionMethod"];
        for (auto it = evIslandingDetectionMethod_json.Begin(); ret && (it != evIslandingDetectionMethod_json.End()); ++it)
        {
            IslandingDetectionEnumType& item = data.evIslandingDetectionMethod.emplace_back();
            item = IslandingDetectionEnumTypeHelper.fromString(it->GetString());
        }
    }

    // evIslandingTripTime
    extract(json, "evIslandingTripTime", data.evIslandingTripTime);

    // evMaximumLevel1DCInjection
    extract(json, "evMaximumLevel1DCInjection", data.evMaximumLevel1DCInjection);

    // evDurationLevel1DCInjection
    extract(json, "evDurationLevel1DCInjection", data.evDurationLevel1DCInjection);

    // evMaximumLevel2DCInjection
    extract(json, "evMaximumLevel2DCInjection", data.evMaximumLevel2DCInjection);

    // evDurationLevel2DCInjection
    extract(json, "evDurationLevel2DCInjection", data.evDurationLevel2DCInjection);

    // evReactiveSusceptance
    extract(json, "evReactiveSusceptance", data.evReactiveSusceptance);

    // evSessionTotalDischargeEnergyAvailable
    extract(json, "evSessionTotalDischargeEnergyAvailable", data.evSessionTotalDischargeEnergyAvailable);

    // customData
    if (json.HasMember("customData"))
    {
    CustomDataTypeConverter customData_converter;
    ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a DERChargingParametersType to a JSON representation */
bool DERChargingParametersTypeConverter::toJson(const DERChargingParametersType& data, rapidjson::Document& json) 
{
    bool ret = true;

    // evSupportedDERControl
    if (!data.evSupportedDERControl.empty())
    {

        rapidjson::Value evSupportedDERControl_json(rapidjson::kArrayType);
        for (const DERControlEnumType& item : data.evSupportedDERControl)
        {
            evSupportedDERControl_json.PushBack(rapidjson::Value(DERControlEnumTypeHelper.toString(item).c_str(), *allocator).Move(), *allocator);
        }
        json.AddMember(rapidjson::StringRef("evSupportedDERControl"), evSupportedDERControl_json.Move(), *allocator);
    }

    // evOverExcitedMaxDischargePower
    fill(json, "evOverExcitedMaxDischargePower", data.evOverExcitedMaxDischargePower);

    // evOverExcitedPowerFactor
    fill(json, "evOverExcitedPowerFactor", data.evOverExcitedPowerFactor);

    // evUnderExcitedMaxDischargePower
    fill(json, "evUnderExcitedMaxDischargePower", data.evUnderExcitedMaxDischargePower);

    // evUnderExcitedPowerFactor
    fill(json, "evUnderExcitedPowerFactor", data.evUnderExcitedPowerFactor);

    // maxApparentPower
    fill(json, "maxApparentPower", data.maxApparentPower);

    // maxChargeApparentPower
    fill(json, "maxChargeApparentPower", data.maxChargeApparentPower);

    // maxChargeApparentPower_L2
    fill(json, "maxChargeApparentPower_L2", data.maxChargeApparentPower_L2);

    // maxChargeApparentPower_L3
    fill(json, "maxChargeApparentPower_L3", data.maxChargeApparentPower_L3);

    // maxDischargeApparentPower
    fill(json, "maxDischargeApparentPower", data.maxDischargeApparentPower);

    // maxDischargeApparentPower_L2
    fill(json, "maxDischargeApparentPower_L2", data.maxDischargeApparentPower_L2);

    // maxDischargeApparentPower_L3
    fill(json, "maxDischargeApparentPower_L3", data.maxDischargeApparentPower_L3);

    // maxChargeReactivePower
    fill(json, "maxChargeReactivePower", data.maxChargeReactivePower);

    // maxChargeReactivePower_L2
    fill(json, "maxChargeReactivePower_L2", data.maxChargeReactivePower_L2);

    // maxChargeReactivePower_L3
    fill(json, "maxChargeReactivePower_L3", data.maxChargeReactivePower_L3);

    // minChargeReactivePower
    fill(json, "minChargeReactivePower", data.minChargeReactivePower);

    // minChargeReactivePower_L2
    fill(json, "minChargeReactivePower_L2", data.minChargeReactivePower_L2);

    // minChargeReactivePower_L3
    fill(json, "minChargeReactivePower_L3", data.minChargeReactivePower_L3);

    // maxDischargeReactivePower
    fill(json, "maxDischargeReactivePower", data.maxDischargeReactivePower);

    // maxDischargeReactivePower_L2
    fill(json, "maxDischargeReactivePower_L2", data.maxDischargeReactivePower_L2);

    // maxDischargeReactivePower_L3
    fill(json, "maxDischargeReactivePower_L3", data.maxDischargeReactivePower_L3);

    // minDischargeReactivePower
    fill(json, "minDischargeReactivePower", data.minDischargeReactivePower);

    // minDischargeReactivePower_L2
    fill(json, "minDischargeReactivePower_L2", data.minDischargeReactivePower_L2);

    // minDischargeReactivePower_L3
    fill(json, "minDischargeReactivePower_L3", data.minDischargeReactivePower_L3);

    // nominalVoltage
    fill(json, "nominalVoltage", data.nominalVoltage);

    // nominalVoltageOffset
    fill(json, "nominalVoltageOffset", data.nominalVoltageOffset);

    // maxNominalVoltage
    fill(json, "maxNominalVoltage", data.maxNominalVoltage);

    // minNominalVoltage
    fill(json, "minNominalVoltage", data.minNominalVoltage);

    // evInverterManufacturer
    fill(json, "evInverterManufacturer", data.evInverterManufacturer);

    // evInverterModel
    fill(json, "evInverterModel", data.evInverterModel);

    // evInverterSerialNumber
    fill(json, "evInverterSerialNumber", data.evInverterSerialNumber);

    // evInverterSwVersion
    fill(json, "evInverterSwVersion", data.evInverterSwVersion);

    // evInverterHwVersion
    fill(json, "evInverterHwVersion", data.evInverterHwVersion);

    // evIslandingDetectionMethod
    if (!data.evIslandingDetectionMethod.empty())
    {

        rapidjson::Value evIslandingDetectionMethod_json(rapidjson::kArrayType);
        for (const IslandingDetectionEnumType& item : data.evIslandingDetectionMethod)
        {
            evIslandingDetectionMethod_json.PushBack(rapidjson::Value(IslandingDetectionEnumTypeHelper.toString(item).c_str(), *allocator).Move(), *allocator);
        }
        json.AddMember(rapidjson::StringRef("evIslandingDetectionMethod"), evIslandingDetectionMethod_json.Move(), *allocator);
    }

    // evIslandingTripTime
    fill(json, "evIslandingTripTime", data.evIslandingTripTime);

    // evMaximumLevel1DCInjection
    fill(json, "evMaximumLevel1DCInjection", data.evMaximumLevel1DCInjection);

    // evDurationLevel1DCInjection
    fill(json, "evDurationLevel1DCInjection", data.evDurationLevel1DCInjection);

    // evMaximumLevel2DCInjection
    fill(json, "evMaximumLevel2DCInjection", data.evMaximumLevel2DCInjection);

    // evDurationLevel2DCInjection
    fill(json, "evDurationLevel2DCInjection", data.evDurationLevel2DCInjection);

    // evReactiveSusceptance
    fill(json, "evReactiveSusceptance", data.evReactiveSusceptance);

    // evSessionTotalDischargeEnergyAvailable
    fill(json, "evSessionTotalDischargeEnergyAvailable", data.evSessionTotalDischargeEnergyAvailable);

    // customData
    if (data.customData.isSet())
    {
    CustomDataTypeConverter customData_converter;
    customData_converter.setAllocator(allocator);
    rapidjson::Document customData_doc(rapidjson::kObjectType);
    ret = ret && customData_converter.toJson(data.customData, customData_doc);
    json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    return ret;
}

} // namespace ocpp21
} // namespace types
} // namespace ocpp