/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:NotifyEVChargingNeedsRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#include "EVAbsolutePriceScheduleType21.h"

#include "IRpc.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief Convert a EVAbsolutePriceScheduleType from a JSON representation */
bool EVAbsolutePriceScheduleTypeConverter::fromJson(const rapidjson::Value&       json,
                                      EVAbsolutePriceScheduleType&                data,
                                      std::string&                  error_code,
                                      [[maybe_unused]] std::string& error_message)
{
    bool ret = true;

    // timeAnchor
    ret = ret && extract(json, "timeAnchor", data.timeAnchor, error_message);

    // currency
    extract(json, "currency", data.currency);

    // evAbsolutePriceScheduleEntries
    if (json.HasMember("evAbsolutePriceScheduleEntries"))
    {
        const rapidjson::Value& evAbsolutePriceScheduleEntries_json = json["evAbsolutePriceScheduleEntries"];
        EVAbsolutePriceScheduleEntryTypeConverter evAbsolutePriceScheduleEntries_converter;
        for (auto it = evAbsolutePriceScheduleEntries_json.Begin(); ret && (it != evAbsolutePriceScheduleEntries_json.End()); ++it)
        {
            EVAbsolutePriceScheduleEntryType& item = data.evAbsolutePriceScheduleEntries.emplace_back();
            ret = ret && evAbsolutePriceScheduleEntries_converter.fromJson(*it, item, error_code, error_message);
        }
    }

    // priceAlgorithm
    extract(json, "priceAlgorithm", data.priceAlgorithm);

    // customData
    if (json.HasMember("customData"))
    {
    CustomDataTypeConverter customData_converter;
    ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a EVAbsolutePriceScheduleType to a JSON representation */
bool EVAbsolutePriceScheduleTypeConverter::toJson(const EVAbsolutePriceScheduleType& data, rapidjson::Document& json) 
{
    bool ret = true;

    // timeAnchor
    fill(json, "timeAnchor", data.timeAnchor);

    // currency
    fill(json, "currency", data.currency);

    // evAbsolutePriceScheduleEntries

        rapidjson::Value evAbsolutePriceScheduleEntries_json(rapidjson::kArrayType);
        EVAbsolutePriceScheduleEntryTypeConverter evAbsolutePriceScheduleEntries_converter;
        evAbsolutePriceScheduleEntries_converter.setAllocator(allocator);
        for (const EVAbsolutePriceScheduleEntryType& item : data.evAbsolutePriceScheduleEntries)
        {
            rapidjson::Document item_doc(rapidjson::kObjectType);
            ret = ret && evAbsolutePriceScheduleEntries_converter.toJson(item, item_doc);
            evAbsolutePriceScheduleEntries_json.PushBack(item_doc.Move(), *allocator);
        }
        json.AddMember(rapidjson::StringRef("evAbsolutePriceScheduleEntries"), evAbsolutePriceScheduleEntries_json.Move(), *allocator);

    // priceAlgorithm
    fill(json, "priceAlgorithm", data.priceAlgorithm);

    // customData
    if (data.customData.isSet())
    {
    CustomDataTypeConverter customData_converter;
    customData_converter.setAllocator(allocator);
    rapidjson::Document customData_doc(rapidjson::kObjectType);
    ret = ret && customData_converter.toJson(data.customData, customData_doc);
    json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    return ret;
}

} // namespace ocpp21
} // namespace types
} // namespace ocpp