/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:NotifyEVChargingNeedsRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#include "EVEnergyOfferType21.h"

#include "IRpc.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief Convert a EVEnergyOfferType from a JSON representation */
bool EVEnergyOfferTypeConverter::fromJson(const rapidjson::Value&       json,
                                      EVEnergyOfferType&                data,
                                      std::string&                  error_code,
                                      [[maybe_unused]] std::string& error_message)
{
    bool ret = true;

    // evAbsolutePriceSchedule
    if (json.HasMember("evAbsolutePriceSchedule"))
    {
    EVAbsolutePriceScheduleTypeConverter evAbsolutePriceSchedule_converter;
    ret = ret && evAbsolutePriceSchedule_converter.fromJson(json["evAbsolutePriceSchedule"], data.evAbsolutePriceSchedule, error_code, error_message);
    }

    // evPowerSchedule
    EVPowerScheduleTypeConverter evPowerSchedule_converter;
    ret = ret && evPowerSchedule_converter.fromJson(json["evPowerSchedule"], data.evPowerSchedule, error_code, error_message);

    // customData
    if (json.HasMember("customData"))
    {
    CustomDataTypeConverter customData_converter;
    ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a EVEnergyOfferType to a JSON representation */
bool EVEnergyOfferTypeConverter::toJson(const EVEnergyOfferType& data, rapidjson::Document& json) 
{
    bool ret = true;

    // evAbsolutePriceSchedule
    if (data.evAbsolutePriceSchedule.isSet())
    {
    EVAbsolutePriceScheduleTypeConverter evAbsolutePriceSchedule_converter;
    evAbsolutePriceSchedule_converter.setAllocator(allocator);
    rapidjson::Document evAbsolutePriceSchedule_doc(rapidjson::kObjectType);
    ret = ret && evAbsolutePriceSchedule_converter.toJson(data.evAbsolutePriceSchedule, evAbsolutePriceSchedule_doc);
    json.AddMember(rapidjson::StringRef("evAbsolutePriceSchedule"), evAbsolutePriceSchedule_doc.Move(), *allocator);
    }

    // evPowerSchedule
    EVPowerScheduleTypeConverter evPowerSchedule_converter;
    evPowerSchedule_converter.setAllocator(allocator);
    rapidjson::Document evPowerSchedule_doc(rapidjson::kObjectType);
    ret = ret && evPowerSchedule_converter.toJson(data.evPowerSchedule, evPowerSchedule_doc);
    json.AddMember(rapidjson::StringRef("evPowerSchedule"), evPowerSchedule_doc.Move(), *allocator);

    // customData
    if (data.customData.isSet())
    {
    CustomDataTypeConverter customData_converter;
    customData_converter.setAllocator(allocator);
    rapidjson::Document customData_doc(rapidjson::kObjectType);
    ret = ret && customData_converter.toJson(data.customData, customData_doc);
    json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    return ret;
}

} // namespace ocpp21
} // namespace types
} // namespace ocpp