/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:ReportDERControlRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#include "FixedVarType21.h"

#include "IRpc.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief Convert a FixedVarType from a JSON representation */
bool FixedVarTypeConverter::fromJson(const rapidjson::Value&       json,
                                      FixedVarType&                data,
                                      std::string&                  error_code,
                                      [[maybe_unused]] std::string& error_message)
{
    bool ret = true;

    // priority
    extract(json, "priority", data.priority);

    // setpoint
    extract(json, "setpoint", data.setpoint);

    // unit
    data.unit = DERUnitEnumTypeHelper.fromString(json["unit"].GetString());

    // startTime
    ret = ret && extract(json, "startTime", data.startTime, error_message);

    // duration
    extract(json, "duration", data.duration);

    // customData
    if (json.HasMember("customData"))
    {
    CustomDataTypeConverter customData_converter;
    ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a FixedVarType to a JSON representation */
bool FixedVarTypeConverter::toJson(const FixedVarType& data, rapidjson::Document& json) 
{
    bool ret = true;

    // priority
    fill(json, "priority", data.priority);

    // setpoint
    fill(json, "setpoint", data.setpoint);

    // unit
    fill(json, "unit", DERUnitEnumTypeHelper.toString(data.unit));

    // startTime
    fill(json, "startTime", data.startTime);

    // duration
    fill(json, "duration", data.duration);

    // customData
    if (data.customData.isSet())
    {
    CustomDataTypeConverter customData_converter;
    customData_converter.setAllocator(allocator);
    rapidjson::Document customData_doc(rapidjson::kObjectType);
    ret = ret && customData_converter.toJson(data.customData, customData_doc);
    json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    return ret;
}

} // namespace ocpp21
} // namespace types
} // namespace ocpp