/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:ReportDERControlRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#include "HysteresisType21.h"

#include "IRpc.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief Convert a HysteresisType from a JSON representation */
bool HysteresisTypeConverter::fromJson(const rapidjson::Value&       json,
                                      HysteresisType&                data,
                                      std::string&                  error_code,
                                      [[maybe_unused]] std::string& error_message)
{
    bool ret = true;

    // hysteresisHigh
    extract(json, "hysteresisHigh", data.hysteresisHigh);

    // hysteresisLow
    extract(json, "hysteresisLow", data.hysteresisLow);

    // hysteresisDelay
    extract(json, "hysteresisDelay", data.hysteresisDelay);

    // hysteresisGradient
    extract(json, "hysteresisGradient", data.hysteresisGradient);

    // customData
    if (json.HasMember("customData"))
    {
    CustomDataTypeConverter customData_converter;
    ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a HysteresisType to a JSON representation */
bool HysteresisTypeConverter::toJson(const HysteresisType& data, rapidjson::Document& json) 
{
    bool ret = true;

    // hysteresisHigh
    fill(json, "hysteresisHigh", data.hysteresisHigh);

    // hysteresisLow
    fill(json, "hysteresisLow", data.hysteresisLow);

    // hysteresisDelay
    fill(json, "hysteresisDelay", data.hysteresisDelay);

    // hysteresisGradient
    fill(json, "hysteresisGradient", data.hysteresisGradient);

    // customData
    if (data.customData.isSet())
    {
    CustomDataTypeConverter customData_converter;
    customData_converter.setAllocator(allocator);
    rapidjson::Document customData_doc(rapidjson::kObjectType);
    ret = ret && customData_converter.toJson(data.customData, customData_doc);
    json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    return ret;
}

} // namespace ocpp21
} // namespace types
} // namespace ocpp