/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:ReportDERControlRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_LIMITMAXDISCHARGEGETTYPE_H
#define OPENOCPP_OCPP21_LIMITMAXDISCHARGEGETTYPE_H


#include "LimitMaxDischargeType21.h"
#include "CustomDataType21.h"

#include "CiStringType.h"
#include "Optional.h"
#include "IMessageConverter.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief  */
struct LimitMaxDischargeGetType
{
    /** @brief Id of setting */
    ocpp::types::CiStringType<36u> id;
    /** @brief True if setting is a default control. */
    bool isDefault;
    /** @brief True if this setting is superseded by a higher priority setting (i.e. lower value of _priority_) */
    bool isSuperseded;
    /** @brief  */
    LimitMaxDischargeType limitMaxDischarge;
    /** @brief  */
    ocpp::types::Optional<CustomDataType> customData;
};

/** @brief Converter class for LimitMaxDischargeGetType type */
class LimitMaxDischargeGetTypeConverter : public ocpp::messages::IMessageConverter<LimitMaxDischargeGetType>
{
  public:
    /** @brief Clone the converter */
    ocpp::messages::IMessageConverter<LimitMaxDischargeGetType>* clone() const override { return new LimitMaxDischargeGetTypeConverter(); }

    /** @brief Convert a LimitMaxDischargeGetType from a JSON representation */
    bool fromJson(const rapidjson::Value&       json,
                  LimitMaxDischargeGetType&                data,
                  std::string&                  error_code,
                  [[maybe_unused]] std::string& error_message) override;

    /** @brief Convert a LimitMaxDischargeGetType to a JSON representation */
    bool toJson(const LimitMaxDischargeGetType& data, rapidjson::Document& json) override;
};

} // namespace ocpp21
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_OCPP21_LIMITMAXDISCHARGEGETTYPE_H