/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:TransactionEventRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#include "MeterValueType21.h"

#include "IRpc.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief Convert a MeterValueType from a JSON representation */
bool MeterValueTypeConverter::fromJson(const rapidjson::Value&       json,
                                      MeterValueType&                data,
                                      std::string&                  error_code,
                                      [[maybe_unused]] std::string& error_message)
{
    bool ret = true;

    // sampledValue
    if (json.HasMember("sampledValue"))
    {
        const rapidjson::Value& sampledValue_json = json["sampledValue"];
        SampledValueTypeConverter sampledValue_converter;
        for (auto it = sampledValue_json.Begin(); ret && (it != sampledValue_json.End()); ++it)
        {
            SampledValueType& item = data.sampledValue.emplace_back();
            ret = ret && sampledValue_converter.fromJson(*it, item, error_code, error_message);
        }
    }

    // timestamp
    ret = ret && extract(json, "timestamp", data.timestamp, error_message);

    // customData
    if (json.HasMember("customData"))
    {
    CustomDataTypeConverter customData_converter;
    ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a MeterValueType to a JSON representation */
bool MeterValueTypeConverter::toJson(const MeterValueType& data, rapidjson::Document& json) 
{
    bool ret = true;

    // sampledValue

        rapidjson::Value sampledValue_json(rapidjson::kArrayType);
        SampledValueTypeConverter sampledValue_converter;
        sampledValue_converter.setAllocator(allocator);
        for (const SampledValueType& item : data.sampledValue)
        {
            rapidjson::Document item_doc(rapidjson::kObjectType);
            ret = ret && sampledValue_converter.toJson(item, item_doc);
            sampledValue_json.PushBack(item_doc.Move(), *allocator);
        }
        json.AddMember(rapidjson::StringRef("sampledValue"), sampledValue_json.Move(), *allocator);

    // timestamp
    fill(json, "timestamp", data.timestamp);

    // customData
    if (data.customData.isSet())
    {
    CustomDataTypeConverter customData_converter;
    customData_converter.setAllocator(allocator);
    rapidjson::Document customData_doc(rapidjson::kObjectType);
    ret = ret && customData_converter.toJson(data.customData, customData_doc);
    json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    return ret;
}

} // namespace ocpp21
} // namespace types
} // namespace ocpp