/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:SetNetworkProfileRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_NETWORKCONNECTIONPROFILETYPE_H
#define OPENOCPP_OCPP21_NETWORKCONNECTIONPROFILETYPE_H


#include "APNType21.h"
#include "OCPPVersionEnumType21.h"
#include "OCPPInterfaceEnumType21.h"
#include "OCPPTransportEnumType21.h"
#include "VPNType21.h"
#include "CustomDataType21.h"

#include "Optional.h"
#include "CiStringType.h"
#include "IMessageConverter.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief The NetworkConnectionProfile defines the functional and technical parameters of a communication link.
 */
struct NetworkConnectionProfileType
{
    /** @brief  */
    ocpp::types::Optional<APNType> apn;
    /** @brief  */
    ocpp::types::Optional<OCPPVersionEnumType> ocppVersion;
    /** @brief  */
    OCPPInterfaceEnumType ocppInterface;
    /** @brief  */
    OCPPTransportEnumType ocppTransport;
    /** @brief Duration in seconds before a message send by the Charging Station via this network connection times-out.
The best setting depends on the underlying network and response times of the CSMS.
If you are looking for a some guideline: use 30 seconds as a starting point. */
    int messageTimeout;
    /** @brief URL of the CSMS(s) that this Charging Station communicates with, without the Charging Station identity part. +
The SecurityCtrlr.Identity field is appended to _ocppCsmsUrl_ to provide the full websocket URL. */
    ocpp::types::CiStringType<2000u> ocppCsmsUrl;
    /** @brief This field specifies the security profile used when connecting to the CSMS with this NetworkConnectionProfile. */
    int securityProfile;
    /** @brief *(2.1)* Charging Station identity to be used as the basic authentication username. */
    ocpp::types::Optional<ocpp::types::CiStringType<48u>> identity;
    /** @brief *(2.1)* BasicAuthPassword to use for security profile 1 or 2. */
    ocpp::types::Optional<ocpp::types::CiStringType<64u>> basicAuthPassword;
    /** @brief  */
    ocpp::types::Optional<VPNType> vpn;
    /** @brief  */
    ocpp::types::Optional<CustomDataType> customData;
};

/** @brief Converter class for NetworkConnectionProfileType type */
class NetworkConnectionProfileTypeConverter : public ocpp::messages::IMessageConverter<NetworkConnectionProfileType>
{
  public:
    /** @brief Clone the converter */
    ocpp::messages::IMessageConverter<NetworkConnectionProfileType>* clone() const override { return new NetworkConnectionProfileTypeConverter(); }

    /** @brief Convert a NetworkConnectionProfileType from a JSON representation */
    bool fromJson(const rapidjson::Value&       json,
                  NetworkConnectionProfileType&                data,
                  std::string&                  error_code,
                  [[maybe_unused]] std::string& error_message) override;

    /** @brief Convert a NetworkConnectionProfileType to a JSON representation */
    bool toJson(const NetworkConnectionProfileType& data, rapidjson::Document& json) override;
};

} // namespace ocpp21
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_OCPP21_NETWORKCONNECTIONPROFILETYPE_H