/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:NotifyChargingLimitRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_RATIONALNUMBERTYPE_H
#define OPENOCPP_OCPP21_RATIONALNUMBERTYPE_H


#include "CustomDataType21.h"

#include "Optional.h"
#include "IMessageConverter.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief Part of ISO 15118-20 price schedule.

 */
struct RationalNumberType
{
    /** @brief The exponent to base 10 (dec) */
    int exponent;
    /** @brief Value which shall be multiplied. */
    int value;
    /** @brief  */
    ocpp::types::Optional<CustomDataType> customData;
};

/** @brief Converter class for RationalNumberType type */
class RationalNumberTypeConverter : public ocpp::messages::IMessageConverter<RationalNumberType>
{
  public:
    /** @brief Clone the converter */
    ocpp::messages::IMessageConverter<RationalNumberType>* clone() const override { return new RationalNumberTypeConverter(); }

    /** @brief Convert a RationalNumberType from a JSON representation */
    bool fromJson(const rapidjson::Value&       json,
                  RationalNumberType&                data,
                  std::string&                  error_code,
                  [[maybe_unused]] std::string& error_message) override;

    /** @brief Convert a RationalNumberType to a JSON representation */
    bool toJson(const RationalNumberType& data, rapidjson::Document& json) override;
};

} // namespace ocpp21
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_OCPP21_RATIONALNUMBERTYPE_H