/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:NotifyReportRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_REPORTDATATYPE_H
#define OPENOCPP_OCPP21_REPORTDATATYPE_H


#include "ComponentType21.h"
#include "VariableType21.h"
#include "VariableAttributeType21.h"
#include "VariableCharacteristicsType21.h"
#include "CustomDataType21.h"

#include <vector>
#include "Optional.h"
#include "IMessageConverter.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief Class to report components, variables and variable attributes and characteristics.
 */
struct ReportDataType
{
    /** @brief  */
    ComponentType component;
    /** @brief  */
    VariableType variable;
    /** @brief  */
    std::vector<VariableAttributeType> variableAttribute;
    /** @brief  */
    ocpp::types::Optional<VariableCharacteristicsType> variableCharacteristics;
    /** @brief  */
    ocpp::types::Optional<CustomDataType> customData;
};

/** @brief Converter class for ReportDataType type */
class ReportDataTypeConverter : public ocpp::messages::IMessageConverter<ReportDataType>
{
  public:
    /** @brief Clone the converter */
    ocpp::messages::IMessageConverter<ReportDataType>* clone() const override { return new ReportDataTypeConverter(); }

    /** @brief Convert a ReportDataType from a JSON representation */
    bool fromJson(const rapidjson::Value&       json,
                  ReportDataType&                data,
                  std::string&                  error_code,
                  [[maybe_unused]] std::string& error_message) override;

    /** @brief Convert a ReportDataType to a JSON representation */
    bool toJson(const ReportDataType& data, rapidjson::Document& json) override;
};

} // namespace ocpp21
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_OCPP21_REPORTDATATYPE_H