/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:GetBaseReportRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_REPORTBASEENUMTYPE_H
#define OPENOCPP_OCPP21_REPORTBASEENUMTYPE_H

#include "EnumToStringFromString.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief This field specifies the report base. */
enum class ReportBaseEnumType
{
    ConfigurationInventory,
    FullInventory,
    SummaryInventory,
};

/** @brief Helper to convert a ReportBaseEnumType enum to string */
extern const EnumToStringFromString<ReportBaseEnumType> ReportBaseEnumTypeHelper;

} // namespace ocpp21
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_OCPP21_REPORTBASEENUMTYPE_H