/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:SendLocalListRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_SENDLOCALLISTSTATUSENUMTYPE_H
#define OPENOCPP_OCPP21_SENDLOCALLISTSTATUSENUMTYPE_H

#include "EnumToStringFromString.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief This indicates whether the Charging Station has successfully received and applied the update of the Local Authorization List. */
enum class SendLocalListStatusEnumType
{
    Accepted,
    Failed,
    VersionMismatch,
};

/** @brief Helper to convert a SendLocalListStatusEnumType enum to string */
extern const EnumToStringFromString<SendLocalListStatusEnumType> SendLocalListStatusEnumTypeHelper;

} // namespace ocpp21
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_OCPP21_SENDLOCALLISTSTATUSENUMTYPE_H