/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:SetVariablesRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_SETVARIABLEDATATYPE_H
#define OPENOCPP_OCPP21_SETVARIABLEDATATYPE_H


#include "AttributeEnumType21.h"
#include "ComponentType21.h"
#include "VariableType21.h"
#include "CustomDataType21.h"

#include "Optional.h"
#include "CiStringType.h"
#include "IMessageConverter.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief  */
struct SetVariableDataType
{
    /** @brief  */
    ocpp::types::Optional<AttributeEnumType> attributeType;
    /** @brief Value to be assigned to attribute of variable.
This value is allowed to be an empty string ("").

The Configuration Variable &lt;&lt;configkey-configuration-value-size,ConfigurationValueSize&gt;&gt; can be used to limit SetVariableData.attributeValue and VariableCharacteristics.valuesList. The max size of these values will always remain equal. */
    ocpp::types::CiStringType<2500u> attributeValue;
    /** @brief  */
    ComponentType component;
    /** @brief  */
    VariableType variable;
    /** @brief  */
    ocpp::types::Optional<CustomDataType> customData;
};

/** @brief Converter class for SetVariableDataType type */
class SetVariableDataTypeConverter : public ocpp::messages::IMessageConverter<SetVariableDataType>
{
  public:
    /** @brief Clone the converter */
    ocpp::messages::IMessageConverter<SetVariableDataType>* clone() const override { return new SetVariableDataTypeConverter(); }

    /** @brief Convert a SetVariableDataType from a JSON representation */
    bool fromJson(const rapidjson::Value&       json,
                  SetVariableDataType&                data,
                  std::string&                  error_code,
                  [[maybe_unused]] std::string& error_message) override;

    /** @brief Convert a SetVariableDataType to a JSON representation */
    bool toJson(const SetVariableDataType& data, rapidjson::Document& json) override;
};

} // namespace ocpp21
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_OCPP21_SETVARIABLEDATATYPE_H