/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:TransactionEventRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_SIGNEDMETERVALUETYPE_H
#define OPENOCPP_OCPP21_SIGNEDMETERVALUETYPE_H


#include "CustomDataType21.h"

#include "CiStringType.h"
#include "Optional.h"
#include "IMessageConverter.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief Represent a signed version of the meter value.
 */
struct SignedMeterValueType
{
    /** @brief Base64 encoded, contains the signed data from the meter in the format specified in _encodingMethod_, which might contain more then just the meter value. It can contain information like timestamps, reference to a customer etc. */
    ocpp::types::CiStringType<32768u> signedMeterData;
    /** @brief *(2.1)* Method used to create the digital signature. Optional, if already included in _signedMeterData_. Standard values for this are defined in Appendix as SigningMethodEnumStringType. */
    ocpp::types::Optional<ocpp::types::CiStringType<50u>> signingMethod;
    /** @brief Format used by the energy meter to encode the meter data. For example: OCMF or EDL. */
    ocpp::types::CiStringType<50u> encodingMethod;
    /** @brief *(2.1)* Base64 encoded, sending depends on configuration variable _PublicKeyWithSignedMeterValue_. */
    ocpp::types::Optional<ocpp::types::CiStringType<2500u>> publicKey;
    /** @brief  */
    ocpp::types::Optional<CustomDataType> customData;
};

/** @brief Converter class for SignedMeterValueType type */
class SignedMeterValueTypeConverter : public ocpp::messages::IMessageConverter<SignedMeterValueType>
{
  public:
    /** @brief Clone the converter */
    ocpp::messages::IMessageConverter<SignedMeterValueType>* clone() const override { return new SignedMeterValueTypeConverter(); }

    /** @brief Convert a SignedMeterValueType from a JSON representation */
    bool fromJson(const rapidjson::Value&       json,
                  SignedMeterValueType&                data,
                  std::string&                  error_code,
                  [[maybe_unused]] std::string& error_message) override;

    /** @brief Convert a SignedMeterValueType to a JSON representation */
    bool toJson(const SignedMeterValueType& data, rapidjson::Document& json) override;
};

} // namespace ocpp21
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_OCPP21_SIGNEDMETERVALUETYPE_H