/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:AuthorizeRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_TARIFFCONDITIONSFIXEDTYPE_H
#define OPENOCPP_OCPP21_TARIFFCONDITIONSFIXEDTYPE_H


#include "DayOfWeekEnumType21.h"
#include "EvseKindEnumType21.h"
#include "CustomDataType21.h"

#include <string>
#include "Optional.h"
#include <vector>
#include "CiStringType.h"
#include "IMessageConverter.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief These conditions describe if a FixedPrice applies at start of the transaction.

When more than one restriction is set, they are to be treated as a logical AND. All need to be valid before this price is active.

NOTE: _startTimeOfDay_ and _endTimeOfDay_ are in local time, because it is the time in the tariff as it is shown to the EV driver at the Charging Station.
A Charging Station will convert this to the internal time zone that it uses (which is recommended to be UTC, see section Generic chapter 3.1) when performing cost calculation.

 */
struct TariffConditionsFixedType
{
    /** @brief Start time of day in local time. +
Format as per RFC 3339: time-hour ":" time-minute  +
Must be in 24h format with leading zeros. Hour/Minute separator: ":"
Regex: ([0-1][0-9]\|2[0-3]):[0-5][0-9] */
    ocpp::types::Optional<std::string> startTimeOfDay;
    /** @brief End time of day in local time. Same syntax as _startTimeOfDay_. +
    If end time &lt; start time then the period wraps around to the next day. +
    To stop at end of the day use: 00:00. */
    ocpp::types::Optional<std::string> endTimeOfDay;
    /** @brief Day(s) of the week this is tariff applies. */
    std::vector<DayOfWeekEnumType> dayOfWeek;
    /** @brief Start date in local time, for example: 2015-12-24.
Valid from this day (inclusive). +
Format as per RFC 3339: full-date  + 

Regex: ([12][0-9]{3})-(0[1-9]\|1[0-2])-(0[1-9]\|[12][0-9]\|3[01]) */
    ocpp::types::Optional<std::string> validFromDate;
    /** @brief End date in local time, for example: 2015-12-27.
    Valid until this day (exclusive). Same syntax as _validFromDate_. */
    ocpp::types::Optional<std::string> validToDate;
    /** @brief  */
    ocpp::types::Optional<EvseKindEnumType> evseKind;
    /** @brief For which payment brand this (adhoc) tariff applies. Can be used to add a surcharge for certain payment brands.
    Based on value of _additionalIdToken_ from _idToken.additionalInfo.type_ = "PaymentBrand". */
    ocpp::types::Optional<ocpp::types::CiStringType<20u>> paymentBrand;
    /** @brief Type of adhoc payment, e.g. CC, Debit.
    Based on value of _additionalIdToken_ from _idToken.additionalInfo.type_ = "PaymentRecognition". */
    ocpp::types::Optional<ocpp::types::CiStringType<20u>> paymentRecognition;
    /** @brief  */
    ocpp::types::Optional<CustomDataType> customData;
};

/** @brief Converter class for TariffConditionsFixedType type */
class TariffConditionsFixedTypeConverter : public ocpp::messages::IMessageConverter<TariffConditionsFixedType>
{
  public:
    /** @brief Clone the converter */
    ocpp::messages::IMessageConverter<TariffConditionsFixedType>* clone() const override { return new TariffConditionsFixedTypeConverter(); }

    /** @brief Convert a TariffConditionsFixedType from a JSON representation */
    bool fromJson(const rapidjson::Value&       json,
                  TariffConditionsFixedType&                data,
                  std::string&                  error_code,
                  [[maybe_unused]] std::string& error_message) override;

    /** @brief Convert a TariffConditionsFixedType to a JSON representation */
    bool toJson(const TariffConditionsFixedType& data, rapidjson::Document& json) override;
};

} // namespace ocpp21
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_OCPP21_TARIFFCONDITIONSFIXEDTYPE_H