/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:NotifyChargingLimitRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_TAXRULETYPE_H
#define OPENOCPP_OCPP21_TAXRULETYPE_H


#include "RationalNumberType21.h"
#include "CustomDataType21.h"

#include "CiStringType.h"
#include "Optional.h"
#include "IMessageConverter.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief Part of ISO 15118-20 price schedule.

 */
struct TaxRuleType
{
    /** @brief Id for the tax rule. */
    int taxRuleID;
    /** @brief Human readable string to identify the tax rule. */
    ocpp::types::Optional<ocpp::types::CiStringType<100u>> taxRuleName;
    /** @brief Indicates whether the tax is included in any price or not. */
    ocpp::types::Optional<bool> taxIncludedInPrice;
    /** @brief Indicates whether this tax applies to Energy Fees. */
    bool appliesToEnergyFee;
    /** @brief Indicates whether this tax applies to Parking Fees. */
    bool appliesToParkingFee;
    /** @brief Indicates whether this tax applies to Overstay Fees. */
    bool appliesToOverstayFee;
    /** @brief Indicates whether this tax applies to Minimum/Maximum Cost. */
    bool appliesToMinimumMaximumCost;
    /** @brief  */
    RationalNumberType taxRate;
    /** @brief  */
    ocpp::types::Optional<CustomDataType> customData;
};

/** @brief Converter class for TaxRuleType type */
class TaxRuleTypeConverter : public ocpp::messages::IMessageConverter<TaxRuleType>
{
  public:
    /** @brief Clone the converter */
    ocpp::messages::IMessageConverter<TaxRuleType>* clone() const override { return new TaxRuleTypeConverter(); }

    /** @brief Convert a TaxRuleType from a JSON representation */
    bool fromJson(const rapidjson::Value&       json,
                  TaxRuleType&                data,
                  std::string&                  error_code,
                  [[maybe_unused]] std::string& error_message) override;

    /** @brief Convert a TaxRuleType to a JSON representation */
    bool toJson(const TaxRuleType& data, rapidjson::Document& json) override;
};

} // namespace ocpp21
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_OCPP21_TAXRULETYPE_H