/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:TransactionEventRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_TAXRATETYPE_H
#define OPENOCPP_OCPP21_TAXRATETYPE_H


#include "CustomDataType21.h"

#include "CiStringType.h"
#include "Optional.h"
#include "IMessageConverter.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief Tax percentage
 */
struct TaxRateType
{
    /** @brief Type of this tax, e.g.  "Federal ",  "State", for information on receipt. */
    ocpp::types::CiStringType<20u> type;
    /** @brief Tax percentage */
    float tax;
    /** @brief Stack level for this type of tax. Default value, when absent, is 0. +
_stack_ = 0: tax on net price; +
_stack_ = 1: tax added on top of _stack_ 0; +
_stack_ = 2: tax added on top of _stack_ 1, etc. */
    ocpp::types::Optional<int> stack;
    /** @brief  */
    ocpp::types::Optional<CustomDataType> customData;
};

/** @brief Converter class for TaxRateType type */
class TaxRateTypeConverter : public ocpp::messages::IMessageConverter<TaxRateType>
{
  public:
    /** @brief Clone the converter */
    ocpp::messages::IMessageConverter<TaxRateType>* clone() const override { return new TaxRateTypeConverter(); }

    /** @brief Convert a TaxRateType from a JSON representation */
    bool fromJson(const rapidjson::Value&       json,
                  TaxRateType&                data,
                  std::string&                  error_code,
                  [[maybe_unused]] std::string& error_message) override;

    /** @brief Convert a TaxRateType to a JSON representation */
    bool toJson(const TaxRateType& data, rapidjson::Document& json) override;
};

} // namespace ocpp21
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_OCPP21_TAXRATETYPE_H