/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:TransactionEventRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_TOTALPRICETYPE_H
#define OPENOCPP_OCPP21_TOTALPRICETYPE_H


#include "CustomDataType21.h"

#include "Optional.h"
#include "IMessageConverter.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief Total cost with and without tax. Contains the total of energy, charging time, idle time, fixed and reservation costs including and/or excluding tax.
 */
struct TotalPriceType
{
    /** @brief Price/cost excluding tax. Can be absent if _inclTax_ is present. */
    ocpp::types::Optional<float> exclTax;
    /** @brief Price/cost including tax. Can be absent if _exclTax_ is present. */
    ocpp::types::Optional<float> inclTax;
    /** @brief  */
    ocpp::types::Optional<CustomDataType> customData;
};

/** @brief Converter class for TotalPriceType type */
class TotalPriceTypeConverter : public ocpp::messages::IMessageConverter<TotalPriceType>
{
  public:
    /** @brief Clone the converter */
    ocpp::messages::IMessageConverter<TotalPriceType>* clone() const override { return new TotalPriceTypeConverter(); }

    /** @brief Convert a TotalPriceType from a JSON representation */
    bool fromJson(const rapidjson::Value&       json,
                  TotalPriceType&                data,
                  std::string&                  error_code,
                  [[maybe_unused]] std::string& error_message) override;

    /** @brief Convert a TotalPriceType to a JSON representation */
    bool toJson(const TotalPriceType& data, rapidjson::Document& json) override;
};

} // namespace ocpp21
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_OCPP21_TOTALPRICETYPE_H