/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:TransactionEventRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_TRANSACTIONLIMITTYPE_H
#define OPENOCPP_OCPP21_TRANSACTIONLIMITTYPE_H


#include "CustomDataType21.h"

#include "Optional.h"
#include "IMessageConverter.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief Cost, energy, time or SoC limit for a transaction.
 */
struct TransactionLimitType
{
    /** @brief Maximum allowed cost of transaction in currency of tariff. */
    ocpp::types::Optional<float> maxCost;
    /** @brief Maximum allowed energy in Wh to charge in transaction. */
    ocpp::types::Optional<float> maxEnergy;
    /** @brief Maximum duration of transaction in seconds from start to end. */
    ocpp::types::Optional<int> maxTime;
    /** @brief Maximum State of Charge of EV in percentage. */
    ocpp::types::Optional<int> maxSoC;
    /** @brief  */
    ocpp::types::Optional<CustomDataType> customData;
};

/** @brief Converter class for TransactionLimitType type */
class TransactionLimitTypeConverter : public ocpp::messages::IMessageConverter<TransactionLimitType>
{
  public:
    /** @brief Clone the converter */
    ocpp::messages::IMessageConverter<TransactionLimitType>* clone() const override { return new TransactionLimitTypeConverter(); }

    /** @brief Convert a TransactionLimitType from a JSON representation */
    bool fromJson(const rapidjson::Value&       json,
                  TransactionLimitType&                data,
                  std::string&                  error_code,
                  [[maybe_unused]] std::string& error_message) override;

    /** @brief Convert a TransactionLimitType to a JSON representation */
    bool toJson(const TransactionLimitType& data, rapidjson::Document& json) override;
};

} // namespace ocpp21
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_OCPP21_TRANSACTIONLIMITTYPE_H