/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:TransactionEventRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#include "TriggerReasonEnumType21.h"

namespace ocpp
{
namespace types
{
namespace ocpp21
{

/** @brief Helper to convert a TriggerReasonEnumType enum to string */
const EnumToStringFromString<TriggerReasonEnumType> TriggerReasonEnumTypeHelper = {
    { TriggerReasonEnumType::AbnormalCondition, "AbnormalCondition" },
    { TriggerReasonEnumType::Authorized, "Authorized" },
    { TriggerReasonEnumType::CablePluggedIn, "CablePluggedIn" },
    { TriggerReasonEnumType::ChargingRateChanged, "ChargingRateChanged" },
    { TriggerReasonEnumType::ChargingStateChanged, "ChargingStateChanged" },
    { TriggerReasonEnumType::CostLimitReached, "CostLimitReached" },
    { TriggerReasonEnumType::Deauthorized, "Deauthorized" },
    { TriggerReasonEnumType::EnergyLimitReached, "EnergyLimitReached" },
    { TriggerReasonEnumType::EVCommunicationLost, "EVCommunicationLost" },
    { TriggerReasonEnumType::EVConnectTimeout, "EVConnectTimeout" },
    { TriggerReasonEnumType::EVDeparted, "EVDeparted" },
    { TriggerReasonEnumType::EVDetected, "EVDetected" },
    { TriggerReasonEnumType::LimitSet, "LimitSet" },
    { TriggerReasonEnumType::MeterValueClock, "MeterValueClock" },
    { TriggerReasonEnumType::MeterValuePeriodic, "MeterValuePeriodic" },
    { TriggerReasonEnumType::OperationModeChanged, "OperationModeChanged" },
    { TriggerReasonEnumType::RemoteStart, "RemoteStart" },
    { TriggerReasonEnumType::RemoteStop, "RemoteStop" },
    { TriggerReasonEnumType::ResetCommand, "ResetCommand" },
    { TriggerReasonEnumType::RunningCost, "RunningCost" },
    { TriggerReasonEnumType::SignedDataReceived, "SignedDataReceived" },
    { TriggerReasonEnumType::SoCLimitReached, "SoCLimitReached" },
    { TriggerReasonEnumType::StopAuthorized, "StopAuthorized" },
    { TriggerReasonEnumType::TariffChanged, "TariffChanged" },
    { TriggerReasonEnumType::TariffNotAccepted, "TariffNotAccepted" },
    { TriggerReasonEnumType::TimeLimitReached, "TimeLimitReached" },
    { TriggerReasonEnumType::Trigger, "Trigger" },
    { TriggerReasonEnumType::TxResumed, "TxResumed" },
    { TriggerReasonEnumType::UnlockCommand, "UnlockCommand" },
};

} // namespace ocpp21
} // namespace types
} // namespace ocpp