/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:AFRRSignalRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_AFRRSIGNAL_H
#define OPENOCPP_OCPP21_AFRRSIGNAL_H

#include "IMessageConverter.h"

#include "CustomDataType21.h"
#include "GenericStatusEnumType21.h"
#include "StatusInfoType21.h"

namespace ocpp
{
namespace messages
{
namespace ocpp21
{

/** @brief Action corresponding to the AFRRSignal messages */
static const std::string AFRRSIGNAL_ACTION = "AFRRSignal";

/** @brief AFRRSignalReq message */
struct AFRRSignalReq
{
    /** @brief Time when signal becomes active. */
    ocpp::types::DateTime timestamp;
    /** @brief Value of signal in _v2xSignalWattCurve_. */
    int signal;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

/** @brief AFRRSignalConf message */
struct AFRRSignalConf
{
    /** @brief  */
    ocpp::types::ocpp21::GenericStatusEnumType status;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::StatusInfoType> statusInfo;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

// Message converters
MESSAGE_CONVERTERS(AFRRSignal)

} // namespace ocpp21
} // namespace messages
} // namespace ocpp

#endif // OPENOCPP_OCPP21_AFRRSIGNAL_H