/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:BootNotificationRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_BOOTNOTIFICATION_H
#define OPENOCPP_OCPP21_BOOTNOTIFICATION_H

#include "IMessageConverter.h"

#include "ChargingStationType21.h"
#include "BootReasonEnumType21.h"
#include "CustomDataType21.h"
#include "RegistrationStatusEnumType21.h"
#include "StatusInfoType21.h"

namespace ocpp
{
namespace messages
{
namespace ocpp21
{

/** @brief Action corresponding to the BootNotification messages */
static const std::string BOOTNOTIFICATION_ACTION = "BootNotification";

/** @brief BootNotificationReq message */
struct BootNotificationReq
{
    /** @brief  */
    ocpp::types::ocpp21::ChargingStationType chargingStation;
    /** @brief  */
    ocpp::types::ocpp21::BootReasonEnumType reason;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

/** @brief BootNotificationConf message */
struct BootNotificationConf
{
    /** @brief This contains the CSMS’s current time. */
    ocpp::types::DateTime currentTime;
    /** @brief When &lt;&lt;cmn_registrationstatusenumtype,Status&gt;&gt; is Accepted, this contains the heartbeat interval in seconds. If the CSMS returns something other than Accepted, the value of the interval field indicates the minimum wait time before sending a next BootNotification request. */
    int interval;
    /** @brief  */
    ocpp::types::ocpp21::RegistrationStatusEnumType status;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::StatusInfoType> statusInfo;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

// Message converters
MESSAGE_CONVERTERS(BootNotification)

} // namespace ocpp21
} // namespace messages
} // namespace ocpp

#endif // OPENOCPP_OCPP21_BOOTNOTIFICATION_H