/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:ClearDERControlRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_CLEARDERCONTROL_H
#define OPENOCPP_OCPP21_CLEARDERCONTROL_H

#include "IMessageConverter.h"

#include "DERControlEnumType21.h"
#include "CustomDataType21.h"
#include "DERControlStatusEnumType21.h"
#include "StatusInfoType21.h"

namespace ocpp
{
namespace messages
{
namespace ocpp21
{

/** @brief Action corresponding to the ClearDERControl messages */
static const std::string CLEARDERCONTROL_ACTION = "ClearDERControl";

/** @brief ClearDERControlReq message */
struct ClearDERControlReq
{
    /** @brief True: clearing default DER controls. False: clearing scheduled controls. */
    bool isDefault;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::DERControlEnumType> controlType;
    /** @brief Id of control setting to clear. When omitted all settings for _controlType_ are cleared. */
    ocpp::types::Optional<ocpp::types::CiStringType<36u>> controlId;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

/** @brief ClearDERControlConf message */
struct ClearDERControlConf
{
    /** @brief  */
    ocpp::types::ocpp21::DERControlStatusEnumType status;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::StatusInfoType> statusInfo;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

// Message converters
MESSAGE_CONVERTERS(ClearDERControl)

} // namespace ocpp21
} // namespace messages
} // namespace ocpp

#endif // OPENOCPP_OCPP21_CLEARDERCONTROL_H