/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:GetCertificateChainStatusRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_GETCERTIFICATECHAINSTATUS_H
#define OPENOCPP_OCPP21_GETCERTIFICATECHAINSTATUS_H

#include <vector>

#include "IMessageConverter.h"

#include "CertificateStatusRequestInfoType21.h"
#include "CustomDataType21.h"
#include "CertificateStatusType21.h"

namespace ocpp
{
namespace messages
{
namespace ocpp21
{

/** @brief Action corresponding to the GetCertificateChainStatus messages */
static const std::string GETCERTIFICATECHAINSTATUS_ACTION = "GetCertificateChainStatus";

/** @brief GetCertificateChainStatusReq message */
struct GetCertificateChainStatusReq
{
    /** @brief  */
    std::vector<ocpp::types::ocpp21::CertificateStatusRequestInfoType> certificateStatusRequests;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

/** @brief GetCertificateChainStatusConf message */
struct GetCertificateChainStatusConf
{
    /** @brief  */
    std::vector<ocpp::types::ocpp21::CertificateStatusType> certificateStatus;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

// Message converters
MESSAGE_CONVERTERS(GetCertificateChainStatus)

} // namespace ocpp21
} // namespace messages
} // namespace ocpp

#endif // OPENOCPP_OCPP21_GETCERTIFICATECHAINSTATUS_H