/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:GetLogRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_GETLOG_H
#define OPENOCPP_OCPP21_GETLOG_H

#include "IMessageConverter.h"

#include "LogParametersType21.h"
#include "LogEnumType21.h"
#include "CustomDataType21.h"
#include "LogStatusEnumType21.h"
#include "StatusInfoType21.h"

namespace ocpp
{
namespace messages
{
namespace ocpp21
{

/** @brief Action corresponding to the GetLog messages */
static const std::string GETLOG_ACTION = "GetLog";

/** @brief GetLogReq message */
struct GetLogReq
{
    /** @brief  */
    ocpp::types::ocpp21::LogParametersType log;
    /** @brief  */
    ocpp::types::ocpp21::LogEnumType logType;
    /** @brief The Id of this request */
    int requestId;
    /** @brief This specifies how many times the Charging Station must retry to upload the log before giving up. If this field is not present, it is left to Charging Station to decide how many times it wants to retry. If the value is 0, it means: no retries. */
    ocpp::types::Optional<int> retries;
    /** @brief The interval in seconds after which a retry may be attempted. If this field is not present, it is left to Charging Station to decide how long to wait between attempts. */
    ocpp::types::Optional<int> retryInterval;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

/** @brief GetLogConf message */
struct GetLogConf
{
    /** @brief  */
    ocpp::types::ocpp21::LogStatusEnumType status;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::StatusInfoType> statusInfo;
    /** @brief This contains the name of the log file that will be uploaded. This field is not present when no logging information is available. */
    ocpp::types::Optional<ocpp::types::CiStringType<255u>> filename;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

// Message converters
MESSAGE_CONVERTERS(GetLog)

} // namespace ocpp21
} // namespace messages
} // namespace ocpp

#endif // OPENOCPP_OCPP21_GETLOG_H