/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/* Generated by json2cpp */

#include "MessagesValidator21.h"
#include "Logger.h"
#include "AFRRSignal21.h"
#include "AdjustPeriodicEventStream21.h"
#include "CancelReservation21.h"
#include "CertificateSigned21.h"
#include "ChangeAvailability21.h"
#include "ChangeTransactionTariff21.h"
#include "ClearCache21.h"
#include "ClearChargingProfile21.h"
#include "ClearDERControl21.h"
#include "ClearDisplayMessage21.h"
#include "ClearTariffs21.h"
#include "ClearVariableMonitoring21.h"
#include "ClosePeriodicEventStream21.h"
#include "CustomerInformation21.h"
#include "DataTransfer21.h"
#include "DeleteCertificate21.h"
#include "Get15118EVCertificate21.h"
#include "GetBaseReport21.h"
#include "GetCertificateChainStatus21.h"
#include "GetCertificateStatus21.h"
#include "GetChargingProfiles21.h"
#include "GetCompositeSchedule21.h"
#include "GetDERControl21.h"
#include "GetDisplayMessages21.h"
#include "GetInstalledCertificateIds21.h"
#include "GetLocalListVersion21.h"
#include "GetLog21.h"
#include "GetMonitoringReport21.h"
#include "GetPeriodicEventStream21.h"
#include "GetReport21.h"
#include "GetTariffs21.h"
#include "GetTransactionStatus21.h"
#include "GetVariables21.h"
#include "InstallCertificate21.h"
#include "OpenPeriodicEventStream21.h"
#include "PublishFirmware21.h"
#include "RequestBatterySwap21.h"
#include "RequestStartTransaction21.h"
#include "RequestStopTransaction21.h"
#include "ReserveNow21.h"
#include "Reset21.h"
#include "SendLocalList21.h"
#include "SetChargingProfile21.h"
#include "SetDefaultTariff21.h"
#include "SetDERControl21.h"
#include "SetDisplayMessage21.h"
#include "SetMonitoringBase21.h"
#include "SetMonitoringLevel21.h"
#include "SetNetworkProfile21.h"
#include "SetVariableMonitoring21.h"
#include "SetVariables21.h"
#include "TriggerMessage21.h"
#include "UnlockConnector21.h"
#include "UnpublishFirmware21.h"
#include "UpdateDynamicSchedule21.h"
#include "UpdateFirmware21.h"
#include "UsePriorityCharging21.h"
#include "Authorize21.h"
#include "BatterySwap21.h"
#include "BootNotification21.h"
#include "ClearedChargingLimit21.h"
#include "CostUpdated21.h"
#include "DataTransfer21.h"
#include "FirmwareStatusNotification21.h"
#include "Heartbeat21.h"
#include "LogStatusNotification21.h"
#include "MeterValues21.h"
#include "NotifyAllowedEnergyTransfer21.h"
#include "NotifyChargingLimit21.h"
#include "NotifyCustomerInformation21.h"
#include "NotifyDERAlarm21.h"
#include "NotifyDERStartStop21.h"
#include "NotifyDisplayMessages21.h"
#include "NotifyEVChargingNeeds21.h"
#include "NotifyEVChargingSchedule21.h"
#include "NotifyEvent21.h"
#include "NotifyMonitoringReport21.h"
#include "NotifyPeriodicEventStream21.h"
#include "NotifyPriorityCharging21.h"
#include "NotifyReport21.h"
#include "NotifySettlement21.h"
#include "NotifyWebPaymentStarted21.h"
#include "PublishFirmwareStatusNotification21.h"
#include "PullDynamicScheduleUpdate21.h"
#include "ReportChargingProfiles21.h"
#include "ReportDERControl21.h"
#include "ReservationStatusUpdate21.h"
#include "SecurityEventNotification21.h"
#include "SignCertificate21.h"
#include "StatusNotification21.h"
#include "TransactionEvent21.h"
#include "VatNumberValidation21.h"

namespace ocpp
{
namespace messages
{
namespace ocpp21
{

/** @brief Constructor */
MessagesValidator21::MessagesValidator21() : m_req_validators(), m_resp_validators() { }

/** @brief Destructor */
MessagesValidator21::~MessagesValidator21() { }

/** @brief Load the messages validators */
bool MessagesValidator21::load(const std::string& schemas_path)
{
    bool ret = true;

    // Load validators for all the messages
    m_req_validators.clear();
    m_resp_validators.clear();
    ret = addValidator(schemas_path, AFRRSIGNAL_ACTION) && ret;
    ret = addValidator(schemas_path, ADJUSTPERIODICEVENTSTREAM_ACTION) && ret;
    ret = addValidator(schemas_path, CANCELRESERVATION_ACTION) && ret;
    ret = addValidator(schemas_path, CERTIFICATESIGNED_ACTION) && ret;
    ret = addValidator(schemas_path, CHANGEAVAILABILITY_ACTION) && ret;
    ret = addValidator(schemas_path, CHANGETRANSACTIONTARIFF_ACTION) && ret;
    ret = addValidator(schemas_path, CLEARCACHE_ACTION) && ret;
    ret = addValidator(schemas_path, CLEARCHARGINGPROFILE_ACTION) && ret;
    ret = addValidator(schemas_path, CLEARDERCONTROL_ACTION) && ret;
    ret = addValidator(schemas_path, CLEARDISPLAYMESSAGE_ACTION) && ret;
    ret = addValidator(schemas_path, CLEARTARIFFS_ACTION) && ret;
    ret = addValidator(schemas_path, CLEARVARIABLEMONITORING_ACTION) && ret;
    ret = addValidator(schemas_path, CLOSEPERIODICEVENTSTREAM_ACTION) && ret;
    ret = addValidator(schemas_path, CUSTOMERINFORMATION_ACTION) && ret;
    ret = addValidator(schemas_path, DATATRANSFER_ACTION) && ret;
    ret = addValidator(schemas_path, DELETECERTIFICATE_ACTION) && ret;
    ret = addValidator(schemas_path, GET15118EVCERTIFICATE_ACTION) && ret;
    ret = addValidator(schemas_path, GETBASEREPORT_ACTION) && ret;
    ret = addValidator(schemas_path, GETCERTIFICATECHAINSTATUS_ACTION) && ret;
    ret = addValidator(schemas_path, GETCERTIFICATESTATUS_ACTION) && ret;
    ret = addValidator(schemas_path, GETCHARGINGPROFILES_ACTION) && ret;
    ret = addValidator(schemas_path, GETCOMPOSITESCHEDULE_ACTION) && ret;
    ret = addValidator(schemas_path, GETDERCONTROL_ACTION) && ret;
    ret = addValidator(schemas_path, GETDISPLAYMESSAGES_ACTION) && ret;
    ret = addValidator(schemas_path, GETINSTALLEDCERTIFICATEIDS_ACTION) && ret;
    ret = addValidator(schemas_path, GETLOCALLISTVERSION_ACTION) && ret;
    ret = addValidator(schemas_path, GETLOG_ACTION) && ret;
    ret = addValidator(schemas_path, GETMONITORINGREPORT_ACTION) && ret;
    ret = addValidator(schemas_path, GETPERIODICEVENTSTREAM_ACTION) && ret;
    ret = addValidator(schemas_path, GETREPORT_ACTION) && ret;
    ret = addValidator(schemas_path, GETTARIFFS_ACTION) && ret;
    ret = addValidator(schemas_path, GETTRANSACTIONSTATUS_ACTION) && ret;
    ret = addValidator(schemas_path, GETVARIABLES_ACTION) && ret;
    ret = addValidator(schemas_path, INSTALLCERTIFICATE_ACTION) && ret;
    ret = addValidator(schemas_path, OPENPERIODICEVENTSTREAM_ACTION) && ret;
    ret = addValidator(schemas_path, PUBLISHFIRMWARE_ACTION) && ret;
    ret = addValidator(schemas_path, REQUESTBATTERYSWAP_ACTION) && ret;
    ret = addValidator(schemas_path, REQUESTSTARTTRANSACTION_ACTION) && ret;
    ret = addValidator(schemas_path, REQUESTSTOPTRANSACTION_ACTION) && ret;
    ret = addValidator(schemas_path, RESERVENOW_ACTION) && ret;
    ret = addValidator(schemas_path, RESET_ACTION) && ret;
    ret = addValidator(schemas_path, SENDLOCALLIST_ACTION) && ret;
    ret = addValidator(schemas_path, SETCHARGINGPROFILE_ACTION) && ret;
    ret = addValidator(schemas_path, SETDEFAULTTARIFF_ACTION) && ret;
    ret = addValidator(schemas_path, SETDERCONTROL_ACTION) && ret;
    ret = addValidator(schemas_path, SETDISPLAYMESSAGE_ACTION) && ret;
    ret = addValidator(schemas_path, SETMONITORINGBASE_ACTION) && ret;
    ret = addValidator(schemas_path, SETMONITORINGLEVEL_ACTION) && ret;
    ret = addValidator(schemas_path, SETNETWORKPROFILE_ACTION) && ret;
    ret = addValidator(schemas_path, SETVARIABLEMONITORING_ACTION) && ret;
    ret = addValidator(schemas_path, SETVARIABLES_ACTION) && ret;
    ret = addValidator(schemas_path, TRIGGERMESSAGE_ACTION) && ret;
    ret = addValidator(schemas_path, UNLOCKCONNECTOR_ACTION) && ret;
    ret = addValidator(schemas_path, UNPUBLISHFIRMWARE_ACTION) && ret;
    ret = addValidator(schemas_path, UPDATEDYNAMICSCHEDULE_ACTION) && ret;
    ret = addValidator(schemas_path, UPDATEFIRMWARE_ACTION) && ret;
    ret = addValidator(schemas_path, USEPRIORITYCHARGING_ACTION) && ret;
    ret = addValidator(schemas_path, AUTHORIZE_ACTION) && ret;
    ret = addValidator(schemas_path, BATTERYSWAP_ACTION) && ret;
    ret = addValidator(schemas_path, BOOTNOTIFICATION_ACTION) && ret;
    ret = addValidator(schemas_path, CLEAREDCHARGINGLIMIT_ACTION) && ret;
    ret = addValidator(schemas_path, COSTUPDATED_ACTION) && ret;
    ret = addValidator(schemas_path, DATATRANSFER_ACTION) && ret;
    ret = addValidator(schemas_path, FIRMWARESTATUSNOTIFICATION_ACTION) && ret;
    ret = addValidator(schemas_path, HEARTBEAT_ACTION) && ret;
    ret = addValidator(schemas_path, LOGSTATUSNOTIFICATION_ACTION) && ret;
    ret = addValidator(schemas_path, METERVALUES_ACTION) && ret;
    ret = addValidator(schemas_path, NOTIFYALLOWEDENERGYTRANSFER_ACTION) && ret;
    ret = addValidator(schemas_path, NOTIFYCHARGINGLIMIT_ACTION) && ret;
    ret = addValidator(schemas_path, NOTIFYCUSTOMERINFORMATION_ACTION) && ret;
    ret = addValidator(schemas_path, NOTIFYDERALARM_ACTION) && ret;
    ret = addValidator(schemas_path, NOTIFYDERSTARTSTOP_ACTION) && ret;
    ret = addValidator(schemas_path, NOTIFYDISPLAYMESSAGES_ACTION) && ret;
    ret = addValidator(schemas_path, NOTIFYEVCHARGINGNEEDS_ACTION) && ret;
    ret = addValidator(schemas_path, NOTIFYEVCHARGINGSCHEDULE_ACTION) && ret;
    ret = addValidator(schemas_path, NOTIFYEVENT_ACTION) && ret;
    ret = addValidator(schemas_path, NOTIFYMONITORINGREPORT_ACTION) && ret;
    ret = addValidator(schemas_path, NOTIFYPERIODICEVENTSTREAM_ACTION) && ret;
    ret = addValidator(schemas_path, NOTIFYPRIORITYCHARGING_ACTION) && ret;
    ret = addValidator(schemas_path, NOTIFYREPORT_ACTION) && ret;
    ret = addValidator(schemas_path, NOTIFYSETTLEMENT_ACTION) && ret;
    ret = addValidator(schemas_path, NOTIFYWEBPAYMENTSTARTED_ACTION) && ret;
    ret = addValidator(schemas_path, PUBLISHFIRMWARESTATUSNOTIFICATION_ACTION) && ret;
    ret = addValidator(schemas_path, PULLDYNAMICSCHEDULEUPDATE_ACTION) && ret;
    ret = addValidator(schemas_path, REPORTCHARGINGPROFILES_ACTION) && ret;
    ret = addValidator(schemas_path, REPORTDERCONTROL_ACTION) && ret;
    ret = addValidator(schemas_path, RESERVATIONSTATUSUPDATE_ACTION) && ret;
    ret = addValidator(schemas_path, SECURITYEVENTNOTIFICATION_ACTION) && ret;
    ret = addValidator(schemas_path, SIGNCERTIFICATE_ACTION) && ret;
    ret = addValidator(schemas_path, STATUSNOTIFICATION_ACTION) && ret;
    ret = addValidator(schemas_path, TRANSACTIONEVENT_ACTION) && ret;
    ret = addValidator(schemas_path, VATNUMBERVALIDATION_ACTION) && ret;

    return ret;
}

/** @brief Get the message validator corresponding to a given action */
ocpp::json::JsonValidator* MessagesValidator21::getValidator(const std::string& action, bool is_req) const
{
    ocpp::json::JsonValidator* validator = nullptr;

    // Get validators list
    const std::unordered_map<std::string, std::shared_ptr<ocpp::json::JsonValidator>>* validators = &m_resp_validators;
    if (is_req)
    {
        validators = &m_req_validators;
    }

    auto iter = validators->find(action);
    if (iter != validators->cend())
    {
        validator = iter->second.get();
    }

    return validator;
}

/** @brief Add a message validator for both request and response */
bool MessagesValidator21::addValidator(const std::string& schemas_path, const std::string& action)
{
    bool ret;

    // Add validator for request
    std::filesystem::path req_filepath(schemas_path);
    req_filepath.append(action + "Request.json");
    ret = addValidator(req_filepath, action, true);

    // Add validator for response
    std::filesystem::path resp_filepath(schemas_path);
    resp_filepath.append(action + "Response.json");
    ret = addValidator(resp_filepath, action, false) && ret;

    return ret;
}
/** @brief Add a message validator */
bool MessagesValidator21::addValidator(const std::filesystem::path& validator_path, const std::string& action, bool is_req)
{
    bool ret = false;

    // Load validator
    std::shared_ptr<ocpp::json::JsonValidator> validator = std::make_shared<ocpp::json::JsonValidator>();
    if (validator->init(validator_path.string()))
    {
        LOG_DEBUG << "[" << action << "] Validator loaded : " << validator_path;

        // Add validator
        if (is_req)
        {
            m_req_validators[action] = validator;
        }
        else
        {
            m_resp_validators[action] = validator;
        }

        ret = true;
    }
    else
    {
        LOG_ERROR << "[" << action << "] Unable to load validator : " << validator_path;
    }

    return ret;
}

} // namespace ocpp21
} // namespace messages
} // namespace ocpp