/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:NotifySettlementRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_NOTIFYSETTLEMENT_H
#define OPENOCPP_OCPP21_NOTIFYSETTLEMENT_H

#include "IMessageConverter.h"

#include "PaymentStatusEnumType21.h"
#include "AddressType21.h"
#include "CustomDataType21.h"

namespace ocpp
{
namespace messages
{
namespace ocpp21
{

/** @brief Action corresponding to the NotifySettlement messages */
static const std::string NOTIFYSETTLEMENT_ACTION = "NotifySettlement";

/** @brief NotifySettlementReq message */
struct NotifySettlementReq
{
    /** @brief The _transactionId_ that the settlement belongs to. Can be empty if the payment transaction is canceled prior to the start of the OCPP transaction. */
    ocpp::types::Optional<ocpp::types::CiStringType<36u>> transactionId;
    /** @brief The payment reference received from the payment terminal and is used as the value for _idToken_. */
    ocpp::types::CiStringType<255u> pspRef;
    /** @brief  */
    ocpp::types::ocpp21::PaymentStatusEnumType status;
    /** @brief Additional information from payment terminal/payment process. */
    ocpp::types::Optional<ocpp::types::CiStringType<500u>> statusInfo;
    /** @brief The amount that was settled, or attempted to be settled (in case of failure). */
    float settlementAmount;
    /** @brief The time when the settlement was done. */
    ocpp::types::DateTime settlementTime;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::CiStringType<50u>> receiptId;
    /** @brief The receipt URL, to be used if the receipt is generated by the payment terminal or the CS. */
    ocpp::types::Optional<ocpp::types::CiStringType<2000u>> receiptUrl;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::AddressType> vatCompany;
    /** @brief VAT number for a company receipt. */
    ocpp::types::Optional<ocpp::types::CiStringType<20u>> vatNumber;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

/** @brief NotifySettlementConf message */
struct NotifySettlementConf
{
    /** @brief The receipt URL if receipt generated by CSMS. The Charging Station can QR encode it and show it to the EV Driver. */
    ocpp::types::Optional<ocpp::types::CiStringType<2000u>> receiptUrl;
    /** @brief The receipt id if the receipt is generated by CSMS. */
    ocpp::types::Optional<ocpp::types::CiStringType<50u>> receiptId;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

// Message converters
MESSAGE_CONVERTERS(NotifySettlement)

} // namespace ocpp21
} // namespace messages
} // namespace ocpp

#endif // OPENOCPP_OCPP21_NOTIFYSETTLEMENT_H