/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:NotifyChargingLimitRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_NOTIFYCHARGINGLIMIT_H
#define OPENOCPP_OCPP21_NOTIFYCHARGINGLIMIT_H

#include <vector>

#include "IMessageConverter.h"

#include "ChargingScheduleType21.h"
#include "ChargingLimitType21.h"
#include "CustomDataType21.h"

namespace ocpp
{
namespace messages
{
namespace ocpp21
{

/** @brief Action corresponding to the NotifyChargingLimit messages */
static const std::string NOTIFYCHARGINGLIMIT_ACTION = "NotifyChargingLimit";

/** @brief NotifyChargingLimitReq message */
struct NotifyChargingLimitReq
{
    /** @brief  */
    std::vector<ocpp::types::ocpp21::ChargingScheduleType> chargingSchedule;
    /** @brief The EVSE to which the charging limit is set. If absent or when zero, it applies to the entire Charging Station. */
    ocpp::types::Optional<int> evseId;
    /** @brief  */
    ocpp::types::ocpp21::ChargingLimitType chargingLimit;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

/** @brief NotifyChargingLimitConf message */
struct NotifyChargingLimitConf
{
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

// Message converters
MESSAGE_CONVERTERS(NotifyChargingLimit)

} // namespace ocpp21
} // namespace messages
} // namespace ocpp

#endif // OPENOCPP_OCPP21_NOTIFYCHARGINGLIMIT_H