/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:NotifyDERStartStopRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_NOTIFYDERSTARTSTOP_H
#define OPENOCPP_OCPP21_NOTIFYDERSTARTSTOP_H

#include <vector>

#include "IMessageConverter.h"

#include "CustomDataType21.h"

namespace ocpp
{
namespace messages
{
namespace ocpp21
{

/** @brief Action corresponding to the NotifyDERStartStop messages */
static const std::string NOTIFYDERSTARTSTOP_ACTION = "NotifyDERStartStop";

/** @brief NotifyDERStartStopReq message */
struct NotifyDERStartStopReq
{
    /** @brief Id of the started or stopped DER control.
Corresponds to the _controlId_ of the SetDERControlRequest. */
    ocpp::types::CiStringType<36u> controlId;
    /** @brief True if DER control has started. False if it has ended. */
    bool started;
    /** @brief Time of start or end of event. */
    ocpp::types::DateTime timestamp;
    /** @brief List of controlIds that are superseded as a result of this control starting. */
    std::vector<std::string> supersededIds;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

/** @brief NotifyDERStartStopConf message */
struct NotifyDERStartStopConf
{
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

// Message converters
MESSAGE_CONVERTERS(NotifyDERStartStop)

} // namespace ocpp21
} // namespace messages
} // namespace ocpp

#endif // OPENOCPP_OCPP21_NOTIFYDERSTARTSTOP_H