/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:NotifyDERAlarmRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#include "NotifyDERAlarm21.h"

#include "IRpc.h"

namespace ocpp
{
namespace messages
{
namespace ocpp21
{

/** @brief Convert a NotifyDERAlarmReq from a JSON representation */
bool NotifyDERAlarmReqConverter::fromJson(const rapidjson::Value&       json,
                                     NotifyDERAlarmReq&                 data,
                                     std::string&                  error_code,
                                     std::string&                  error_message)
{
    bool ret = true;

    // controlType
    data.controlType = ocpp::types::ocpp21::DERControlEnumTypeHelper.fromString(json["controlType"].GetString());

    // gridEventFault
    if (json.HasMember("gridEventFault"))
    {
    data.gridEventFault = ocpp::types::ocpp21::GridEventFaultEnumTypeHelper.fromString(json["gridEventFault"].GetString());
    }

    // alarmEnded
    extract(json, "alarmEnded", data.alarmEnded);

    // timestamp
    ret = ret && extract(json, "timestamp", data.timestamp, error_message);

    // extraInfo
    extract(json, "extraInfo", data.extraInfo);

    // customData
    if (json.HasMember("customData"))
    {
    ocpp::types::ocpp21::CustomDataTypeConverter customData_converter;
    ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a NotifyDERAlarmReq to a JSON representation */
bool NotifyDERAlarmReqConverter::toJson(const NotifyDERAlarmReq& data, rapidjson::Document& json) 
{
    bool ret = true;

    // controlType
    fill(json, "controlType", ocpp::types::ocpp21::DERControlEnumTypeHelper.toString(data.controlType));

    // gridEventFault
    if (data.gridEventFault.isSet())
    {
    fill(json, "gridEventFault", ocpp::types::ocpp21::GridEventFaultEnumTypeHelper.toString(data.gridEventFault));
    }

    // alarmEnded
    fill(json, "alarmEnded", data.alarmEnded);

    // timestamp
    fill(json, "timestamp", data.timestamp);

    // extraInfo
    fill(json, "extraInfo", data.extraInfo);

    // customData
    if (data.customData.isSet())
    {
    ocpp::types::ocpp21::CustomDataTypeConverter customData_converter;
    customData_converter.setAllocator(allocator);
    rapidjson::Document customData_doc(rapidjson::kObjectType);
    ret = ret && customData_converter.toJson(data.customData, customData_doc);
    json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    return ret;
}

/** @brief Convert a NotifyDERAlarmConf from a JSON representation */
bool NotifyDERAlarmConfConverter::fromJson(const rapidjson::Value&       json,
                                     NotifyDERAlarmConf&                 data,
                                     std::string&                  error_code,
                                     std::string&                  error_message)
{
    bool ret = true;

    // customData
    if (json.HasMember("customData"))
    {
    ocpp::types::ocpp21::CustomDataTypeConverter customData_converter;
    ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a NotifyDERAlarmConf to a JSON representation */
bool NotifyDERAlarmConfConverter::toJson(const NotifyDERAlarmConf& data, rapidjson::Document& json) 
{
    bool ret = true;

    // customData
    if (data.customData.isSet())
    {
    ocpp::types::ocpp21::CustomDataTypeConverter customData_converter;
    customData_converter.setAllocator(allocator);
    rapidjson::Document customData_doc(rapidjson::kObjectType);
    ret = ret && customData_converter.toJson(data.customData, customData_doc);
    json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    return ret;
}

} // namespace ocpp21
} // namespace messages
} // namespace ocpp