/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:NotifyWebPaymentStartedRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#include "NotifyWebPaymentStarted21.h"

#include "IRpc.h"

namespace ocpp
{
namespace messages
{
namespace ocpp21
{

/** @brief Convert a NotifyWebPaymentStartedReq from a JSON representation */
bool NotifyWebPaymentStartedReqConverter::fromJson(const rapidjson::Value&       json,
                                     NotifyWebPaymentStartedReq&                 data,
                                     std::string&                  error_code,
                                     std::string&                  error_message)
{
    bool ret = true;

    // evseId
    extract(json, "evseId", data.evseId);

    // timeout
    extract(json, "timeout", data.timeout);

    // customData
    if (json.HasMember("customData"))
    {
    ocpp::types::ocpp21::CustomDataTypeConverter customData_converter;
    ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a NotifyWebPaymentStartedReq to a JSON representation */
bool NotifyWebPaymentStartedReqConverter::toJson(const NotifyWebPaymentStartedReq& data, rapidjson::Document& json) 
{
    bool ret = true;

    // evseId
    fill(json, "evseId", data.evseId);

    // timeout
    fill(json, "timeout", data.timeout);

    // customData
    if (data.customData.isSet())
    {
    ocpp::types::ocpp21::CustomDataTypeConverter customData_converter;
    customData_converter.setAllocator(allocator);
    rapidjson::Document customData_doc(rapidjson::kObjectType);
    ret = ret && customData_converter.toJson(data.customData, customData_doc);
    json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    return ret;
}

/** @brief Convert a NotifyWebPaymentStartedConf from a JSON representation */
bool NotifyWebPaymentStartedConfConverter::fromJson(const rapidjson::Value&       json,
                                     NotifyWebPaymentStartedConf&                 data,
                                     std::string&                  error_code,
                                     std::string&                  error_message)
{
    bool ret = true;

    // customData
    if (json.HasMember("customData"))
    {
    ocpp::types::ocpp21::CustomDataTypeConverter customData_converter;
    ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a NotifyWebPaymentStartedConf to a JSON representation */
bool NotifyWebPaymentStartedConfConverter::toJson(const NotifyWebPaymentStartedConf& data, rapidjson::Document& json) 
{
    bool ret = true;

    // customData
    if (data.customData.isSet())
    {
    ocpp::types::ocpp21::CustomDataTypeConverter customData_converter;
    customData_converter.setAllocator(allocator);
    rapidjson::Document customData_doc(rapidjson::kObjectType);
    ret = ret && customData_converter.toJson(data.customData, customData_doc);
    json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    return ret;
}

} // namespace ocpp21
} // namespace messages
} // namespace ocpp