/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:SetDERControlRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_SETDERCONTROL_H
#define OPENOCPP_OCPP21_SETDERCONTROL_H

#include <vector>

#include "IMessageConverter.h"

#include "DERControlEnumType21.h"
#include "DERCurveType21.h"
#include "EnterServiceType21.h"
#include "FixedPFType21.h"
#include "FixedPFType21.h"
#include "FixedVarType21.h"
#include "FreqDroopType21.h"
#include "GradientType21.h"
#include "LimitMaxDischargeType21.h"
#include "CustomDataType21.h"
#include "DERControlStatusEnumType21.h"
#include "StatusInfoType21.h"

namespace ocpp
{
namespace messages
{
namespace ocpp21
{

/** @brief Action corresponding to the SetDERControl messages */
static const std::string SETDERCONTROL_ACTION = "SetDERControl";

/** @brief SetDERControlReq message */
struct SetDERControlReq
{
    /** @brief True if this is a default DER control */
    bool isDefault;
    /** @brief Unique id of this control, e.g. UUID */
    ocpp::types::CiStringType<36u> controlId;
    /** @brief  */
    ocpp::types::ocpp21::DERControlEnumType controlType;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::DERCurveType> curve;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::EnterServiceType> enterService;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::FixedPFType> fixedPFAbsorb;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::FixedPFType> fixedPFInject;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::FixedVarType> fixedVar;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::FreqDroopType> freqDroop;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::GradientType> gradient;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::LimitMaxDischargeType> limitMaxDischarge;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

/** @brief SetDERControlConf message */
struct SetDERControlConf
{
    /** @brief  */
    ocpp::types::ocpp21::DERControlStatusEnumType status;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::StatusInfoType> statusInfo;
    /** @brief List of controlIds that are superseded as a result of setting this control. */
    std::vector<std::string> supersededIds;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

// Message converters
MESSAGE_CONVERTERS(SetDERControl)

} // namespace ocpp21
} // namespace messages
} // namespace ocpp

#endif // OPENOCPP_OCPP21_SETDERCONTROL_H