/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:SetMonitoringBaseRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#include "SetMonitoringBase21.h"

#include "IRpc.h"

namespace ocpp
{
namespace messages
{
namespace ocpp21
{

/** @brief Convert a SetMonitoringBaseReq from a JSON representation */
bool SetMonitoringBaseReqConverter::fromJson(const rapidjson::Value&       json,
                                     SetMonitoringBaseReq&                 data,
                                     std::string&                  error_code,
                                     std::string&                  error_message)
{
    bool ret = true;

    // monitoringBase
    data.monitoringBase = ocpp::types::ocpp21::MonitoringBaseEnumTypeHelper.fromString(json["monitoringBase"].GetString());

    // customData
    if (json.HasMember("customData"))
    {
    ocpp::types::ocpp21::CustomDataTypeConverter customData_converter;
    ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a SetMonitoringBaseReq to a JSON representation */
bool SetMonitoringBaseReqConverter::toJson(const SetMonitoringBaseReq& data, rapidjson::Document& json) 
{
    bool ret = true;

    // monitoringBase
    fill(json, "monitoringBase", ocpp::types::ocpp21::MonitoringBaseEnumTypeHelper.toString(data.monitoringBase));

    // customData
    if (data.customData.isSet())
    {
    ocpp::types::ocpp21::CustomDataTypeConverter customData_converter;
    customData_converter.setAllocator(allocator);
    rapidjson::Document customData_doc(rapidjson::kObjectType);
    ret = ret && customData_converter.toJson(data.customData, customData_doc);
    json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    return ret;
}

/** @brief Convert a SetMonitoringBaseConf from a JSON representation */
bool SetMonitoringBaseConfConverter::fromJson(const rapidjson::Value&       json,
                                     SetMonitoringBaseConf&                 data,
                                     std::string&                  error_code,
                                     std::string&                  error_message)
{
    bool ret = true;

    // status
    data.status = ocpp::types::ocpp21::GenericDeviceModelStatusEnumTypeHelper.fromString(json["status"].GetString());

    // statusInfo
    if (json.HasMember("statusInfo"))
    {
    ocpp::types::ocpp21::StatusInfoTypeConverter statusInfo_converter;
    ret = ret && statusInfo_converter.fromJson(json["statusInfo"], data.statusInfo, error_code, error_message);
    }

    // customData
    if (json.HasMember("customData"))
    {
    ocpp::types::ocpp21::CustomDataTypeConverter customData_converter;
    ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a SetMonitoringBaseConf to a JSON representation */
bool SetMonitoringBaseConfConverter::toJson(const SetMonitoringBaseConf& data, rapidjson::Document& json) 
{
    bool ret = true;

    // status
    fill(json, "status", ocpp::types::ocpp21::GenericDeviceModelStatusEnumTypeHelper.toString(data.status));

    // statusInfo
    if (data.statusInfo.isSet())
    {
    ocpp::types::ocpp21::StatusInfoTypeConverter statusInfo_converter;
    statusInfo_converter.setAllocator(allocator);
    rapidjson::Document statusInfo_doc(rapidjson::kObjectType);
    ret = ret && statusInfo_converter.toJson(data.statusInfo, statusInfo_doc);
    json.AddMember(rapidjson::StringRef("statusInfo"), statusInfo_doc.Move(), *allocator);
    }

    // customData
    if (data.customData.isSet())
    {
    ocpp::types::ocpp21::CustomDataTypeConverter customData_converter;
    customData_converter.setAllocator(allocator);
    rapidjson::Document customData_doc(rapidjson::kObjectType);
    ret = ret && customData_converter.toJson(data.customData, customData_doc);
    json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    return ret;
}

} // namespace ocpp21
} // namespace messages
} // namespace ocpp