/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:SetVariablesRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_SETVARIABLES_H
#define OPENOCPP_OCPP21_SETVARIABLES_H

#include <vector>

#include "IMessageConverter.h"

#include "SetVariableDataType21.h"
#include "CustomDataType21.h"
#include "SetVariableResultType21.h"

namespace ocpp
{
namespace messages
{
namespace ocpp21
{

/** @brief Action corresponding to the SetVariables messages */
static const std::string SETVARIABLES_ACTION = "SetVariables";

/** @brief SetVariablesReq message */
struct SetVariablesReq
{
    /** @brief  */
    std::vector<ocpp::types::ocpp21::SetVariableDataType> setVariableData;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

/** @brief SetVariablesConf message */
struct SetVariablesConf
{
    /** @brief  */
    std::vector<ocpp::types::ocpp21::SetVariableResultType> setVariableResult;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

// Message converters
MESSAGE_CONVERTERS(SetVariables)

} // namespace ocpp21
} // namespace messages
} // namespace ocpp

#endif // OPENOCPP_OCPP21_SETVARIABLES_H