/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:UnpublishFirmwareRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_UNPUBLISHFIRMWARE_H
#define OPENOCPP_OCPP21_UNPUBLISHFIRMWARE_H

#include "IMessageConverter.h"

#include "CustomDataType21.h"
#include "UnpublishFirmwareStatusEnumType21.h"

namespace ocpp
{
namespace messages
{
namespace ocpp21
{

/** @brief Action corresponding to the UnpublishFirmware messages */
static const std::string UNPUBLISHFIRMWARE_ACTION = "UnpublishFirmware";

/** @brief UnpublishFirmwareReq message */
struct UnpublishFirmwareReq
{
    /** @brief The MD5 checksum over the entire firmware file as a hexadecimal string of length 32. */
    ocpp::types::CiStringType<32u> checksum;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

/** @brief UnpublishFirmwareConf message */
struct UnpublishFirmwareConf
{
    /** @brief  */
    ocpp::types::ocpp21::UnpublishFirmwareStatusEnumType status;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

// Message converters
MESSAGE_CONVERTERS(UnpublishFirmware)

} // namespace ocpp21
} // namespace messages
} // namespace ocpp

#endif // OPENOCPP_OCPP21_UNPUBLISHFIRMWARE_H