/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:UpdateFirmwareRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#ifndef OPENOCPP_OCPP21_UPDATEFIRMWARE_H
#define OPENOCPP_OCPP21_UPDATEFIRMWARE_H

#include "IMessageConverter.h"

#include "FirmwareType21.h"
#include "CustomDataType21.h"
#include "UpdateFirmwareStatusEnumType21.h"
#include "StatusInfoType21.h"

namespace ocpp
{
namespace messages
{
namespace ocpp21
{

/** @brief Action corresponding to the UpdateFirmware messages */
static const std::string UPDATEFIRMWARE_ACTION = "UpdateFirmware";

/** @brief UpdateFirmwareReq message */
struct UpdateFirmwareReq
{
    /** @brief This specifies how many times Charging Station must retry to download the firmware before giving up. If this field is not present, it is left to Charging Station to decide how many times it wants to retry.
If the value is 0, it means: no retries. */
    ocpp::types::Optional<int> retries;
    /** @brief The interval in seconds after which a retry may be attempted. If this field is not present, it is left to Charging Station to decide how long to wait between attempts. */
    ocpp::types::Optional<int> retryInterval;
    /** @brief The Id of this request */
    int requestId;
    /** @brief  */
    ocpp::types::ocpp21::FirmwareType firmware;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

/** @brief UpdateFirmwareConf message */
struct UpdateFirmwareConf
{
    /** @brief  */
    ocpp::types::ocpp21::UpdateFirmwareStatusEnumType status;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::StatusInfoType> statusInfo;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp21::CustomDataType> customData;
};

// Message converters
MESSAGE_CONVERTERS(UpdateFirmware)

} // namespace ocpp21
} // namespace messages
} // namespace ocpp

#endif // OPENOCPP_OCPP21_UPDATEFIRMWARE_H