/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2025:1:VatNumberValidationRequest
                                 OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International Public License
*/

#include "VatNumberValidation21.h"

#include "IRpc.h"

namespace ocpp
{
namespace messages
{
namespace ocpp21
{

/** @brief Convert a VatNumberValidationReq from a JSON representation */
bool VatNumberValidationReqConverter::fromJson(const rapidjson::Value&       json,
                                     VatNumberValidationReq&                 data,
                                     std::string&                  error_code,
                                     std::string&                  error_message)
{
    bool ret = true;

    // vatNumber
    extract(json, "vatNumber", data.vatNumber);

    // evseId
    extract(json, "evseId", data.evseId);

    // customData
    if (json.HasMember("customData"))
    {
    ocpp::types::ocpp21::CustomDataTypeConverter customData_converter;
    ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a VatNumberValidationReq to a JSON representation */
bool VatNumberValidationReqConverter::toJson(const VatNumberValidationReq& data, rapidjson::Document& json) 
{
    bool ret = true;

    // vatNumber
    fill(json, "vatNumber", data.vatNumber);

    // evseId
    fill(json, "evseId", data.evseId);

    // customData
    if (data.customData.isSet())
    {
    ocpp::types::ocpp21::CustomDataTypeConverter customData_converter;
    customData_converter.setAllocator(allocator);
    rapidjson::Document customData_doc(rapidjson::kObjectType);
    ret = ret && customData_converter.toJson(data.customData, customData_doc);
    json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    return ret;
}

/** @brief Convert a VatNumberValidationConf from a JSON representation */
bool VatNumberValidationConfConverter::fromJson(const rapidjson::Value&       json,
                                     VatNumberValidationConf&                 data,
                                     std::string&                  error_code,
                                     std::string&                  error_message)
{
    bool ret = true;

    // company
    if (json.HasMember("company"))
    {
    ocpp::types::ocpp21::AddressTypeConverter company_converter;
    ret = ret && company_converter.fromJson(json["company"], data.company, error_code, error_message);
    }

    // statusInfo
    if (json.HasMember("statusInfo"))
    {
    ocpp::types::ocpp21::StatusInfoTypeConverter statusInfo_converter;
    ret = ret && statusInfo_converter.fromJson(json["statusInfo"], data.statusInfo, error_code, error_message);
    }

    // vatNumber
    extract(json, "vatNumber", data.vatNumber);

    // evseId
    extract(json, "evseId", data.evseId);

    // status
    data.status = ocpp::types::ocpp21::GenericStatusEnumTypeHelper.fromString(json["status"].GetString());

    // customData
    if (json.HasMember("customData"))
    {
    ocpp::types::ocpp21::CustomDataTypeConverter customData_converter;
    ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a VatNumberValidationConf to a JSON representation */
bool VatNumberValidationConfConverter::toJson(const VatNumberValidationConf& data, rapidjson::Document& json) 
{
    bool ret = true;

    // company
    if (data.company.isSet())
    {
    ocpp::types::ocpp21::AddressTypeConverter company_converter;
    company_converter.setAllocator(allocator);
    rapidjson::Document company_doc(rapidjson::kObjectType);
    ret = ret && company_converter.toJson(data.company, company_doc);
    json.AddMember(rapidjson::StringRef("company"), company_doc.Move(), *allocator);
    }

    // statusInfo
    if (data.statusInfo.isSet())
    {
    ocpp::types::ocpp21::StatusInfoTypeConverter statusInfo_converter;
    statusInfo_converter.setAllocator(allocator);
    rapidjson::Document statusInfo_doc(rapidjson::kObjectType);
    ret = ret && statusInfo_converter.toJson(data.statusInfo, statusInfo_doc);
    json.AddMember(rapidjson::StringRef("statusInfo"), statusInfo_doc.Move(), *allocator);
    }

    // vatNumber
    fill(json, "vatNumber", data.vatNumber);

    // evseId
    fill(json, "evseId", data.evseId);

    // status
    fill(json, "status", ocpp::types::ocpp21::GenericStatusEnumTypeHelper.toString(data.status));

    // customData
    if (data.customData.isSet())
    {
    ocpp::types::ocpp21::CustomDataTypeConverter customData_converter;
    customData_converter.setAllocator(allocator);
    rapidjson::Document customData_doc(rapidjson::kObjectType);
    ret = ret && customData_converter.toJson(data.customData, customData_doc);
    json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    return ret;
}

} // namespace ocpp21
} // namespace messages
} // namespace ocpp