[AlignedDataCtrlr]
Available=true
Enabled=true
Interval=0
Measurands=
PublicKeyWithSignedMeterValue=
RegisterValuesWithoutPhases=true
SignReadings=false
TxEndedInterval=0
TxEndedMeasurands=
[AlignedDataCtrlr.1]
SendDuringIdle=false
[AuthCacheCtrlr]
Available=true
DisablePostAuthorize=false
Enabled=true
LifeTime=86400
Policy=LRU
Storage=1000000
[AuthCtrlr]
AdditionalInfoItemsPerMessage=10
AuthorizeRemoteStart=true
DisableRemoteAuthorization=false
Enabled=true
LocalAuthorizeOffline=true
LocalPreAuthorize=true
MasterPassGroupId=
OfflineTxForUnknownIdEnabled=false
[ChargePoint]
; ConnexionUrl=wss://192.168.31.60:8443/
BasicAuthPassword=OpenOCPP-cp001-2026
CallRequestTimeout=2000
ChargePointIdentifier=test01
ChargePointModel=Open OCPP CP
ChargePointSerialNumber=S/N0123456789
ChargePointVendor=Open OCPP
ConnectionTimeout=2000
ConnexionUrl=ws://192.168.31.60:8081/
DatabasePath=../config/quick_start_chargepoint21.db
FirmwareVersion=0.1
Iccid=
Imsi=
JsonSchemasPath=../schemas/ocpp21/
LogMaxEntriesCount=2000
RetryInterval=1000
SecurityProfile=0
TlsAcceptNonTrustedCertificates=false
TlsAllowExpiredCertificates=false
TlsAllowSelfSignedCertificates=false
TlsClientCertificate=../certs/client-cert.pem
TlsClientCertificatePrivateKey=../certs/client-key.pem
TlsClientCertificatePrivateKeyPassphrase=
TlsServerCertificateCa=../certs/rootCertificate.pem
TlsSkipServerNameCheck=true
Tlsv12CipherList=ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:PSK-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:PSK-AES128-GCM-SHA256
Tlsv13CipherList=TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384
WebSocketPingInterval=10
[ChargingStation]
AllowNewSessionsPendingFirmwareUpdate=false
Available=true
[ClockCtrlr]
NextTimeOffsetTransitionDateTime=
NtpServerUri.1=
NtpSource=manual
TimeAdjustmentReportingThreshold=5
TimeOffset=+01:00
TimeSource=Heartbeat
TimeZone=Europe/Paris
dateTime=
[Connector.1.1]
AvailabilityState=true
Available=true
ConnectorType=cType2
PhaseRotation=RST
Power=22000
SupplyPhases=3
[CustomizationCtrlr]
CustomImplementationEnabled.<VendorId>=
[DeviceDataCtrlr]
BytesPerMessage.GetReport=10000
BytesPerMessage.GetVariables=10000
BytesPerMessage.SetVariables=10000
ConfigurationValueSize=1000
ItemsPerMessage.GetReport=100
ItemsPerMessage.GetVariables=100
ItemsPerMessage.SetVariables=100
ReportingValueSize=
[DisplayMessageCtrlr]
Available=true
DisplayMessages=10
Enabled=true
SupportedFormats=ASCII,UTF8
SupportedPriorities=AlwaysFront
[EVSE.EVSE1.1]
AllowReset=false
AvailabilityState=Available
Available=true
PhaseRotation=RST
Power=22000
SupplyPhases=3
[ISO15118Ctrlr]
CentralContractValidationAllowed=true
ContractCertificateInstallationEnabled=true
ContractValidationOffline=false
PnCEnabled=false
RequestMeteringReceipt=false
V2GCertificateInstallationEnabled=true
[ISO15118Ctrlr.1]
CountryName=
ISO15118EvseId=
OrganizationName=
ProtocolAgreed=
ProtocolSupportedByEV=
SeccId=
[LocalAuthListCtrlr]
Available=true
BytesPerMessage=10000
DisablePostAuthorize=true
Enabled=true
Entries=1000
ItemsPerMessage=200
Storage=1000000
SupportsExpiryDateTime=true
[LocalTest]
EvseCount=2
MaxChargingStationCurrent=32
MaxEvseCurrent=32
[MonitoringCtrlr]
ActiveMonitoringBase=All
ActiveMonitoringLevel=0
Available=true
BytesPerMessage.ClearVariableMonitoring=10000
BytesPerMessage.SetVariableMonitoring=10000
Enabled=true
ItemsPerMessage.ClearVariableMonitoring=100
ItemsPerMessage.SetVariableMonitoring=100
OfflineQueuingSeverity=0
[OCPPCommCtrlr]
ActiveNetworkProfile=0
FieldLength.<message>.<field>=
FileTransferProtocols=FTP,FTPS,HTTP,HTTPS
HeartbeatInterval=60
MessageAttemptIntervalTransactionEvent.TransactionEvent=30
MessageAttemptsTransactionEvent.TransactionEvent=
MessageTimeout.Default=10
NetworkConfigurationPriority=0,1,2
NetworkProfileConnectionAttempts=3
OfflineThreshold=300
QueueAllMessages=false
ResetRetries=3
RetryBackOffRandomRange=30
RetryBackOffRepeatTimes=10
RetryBackOffWaitMinimum=30
UnlockOnEVSideDisconnect=true
WebSocketPingInterval=10
[ReservationCtrlr]
Available=true
Enabled=true
NonEvseSpecific=false
[SampledDataCtrlr]
Available=false
Enabled=true
SignReadings=false
TxEndedInterval=0
TxEndedMeasurands=
TxStartedMeasurands=
TxUpdatedInterval=5
TxUpdatedMeasurands=
[SecurityCtrlr]
AdditionalRootCertificateCheck=false
BasicAuthPassword=
CertSigningRepeatTimes=3
CertSigningWaitMinimum=30
CertificateEntries=20
Identity=ChargePointTest
MaxCertificateChainSize=10000
OrganizationName=
[SmartChargingCtrlr]
ACPhaseSwitchingSupported=false
Available=true
Enabled=true
Entries=100
ExternalControlSignalsEnabled=false
LimitChangeSignificance=0
NotifyChargingLimitWithSchedules=false
PeriodsPerSchedule=100
Phases3to1=false
ProfileStackLevel=100
RateUnit=A
[TariffCostCtrlr]
Available.Cost=false
Available.Tariff=false
Currency=eur
Enabled.Cost=false
Enabled.Tariff=false
TariffFallbackMessage=
TotalCostFallbackMessage=
[TxCtrlr]
EVConnectionTimeOut=30
MaxEnergyOnInvalidId=0
StopTxOnEVSideDisconnect=true
StopTxOnInvalidId=true
TxBeforeAcceptedEnabled=false
TxStartPoint=PowerPathClosed
TxStopPoint=EVConnected,Authorized
